### ISSUE TITLE
showTodayButton does not work

### ISSUE THREAD

**Issue by angelxmoreno** [rajeshwarpatlolla/ionic-datepicker#101]
settings it to `'false'` or to `false` does not work. is `showTodayButton` the right parameter name?

**Comment by angelxmoreno** [comment]
Ah, it looks like that feature is not in the latest release. Any idea when it will be pushed to `v0.9.1` ?

**Comment by rajeshwarpatlolla** [comment]
It will be available soon. I am working on few other things also. All together i will release a new version.

**Comment by schgressive** [comment]
doesnt work but you can do ```todayButtonType: "ng-hide" ```

**Comment by rajeshwarpatlolla** [comment]
I have already mentioned that this is not yet available in the last release. It will be available in the next release.

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
