### ISSUE TITLE
inputDate issue!

### ISSUE THREAD

**Issue by comapedrosa** [rajeshwarpatlolla/ionic-datepicker#103]
When I set the inputDate property to a specific day, let's say next monday, the datepicker shows the blue date as the specified one but it doesn't select the correct day on the calendar. Here you have a picture of what I'm talking about. 
![screen shot 2015-11-03 at 17 53 53](https://cloud.githubusercontent.com/assets/3918797/10914700/e1587818-8253-11e5-925f-473e24899c27.png)

As you can see it's a bit confusing...The blue date it's specified for the 9th (because is what I put on the inputDate property) but the calendar doesn't select the date. I think that the correct behaviour sholud be this one: (Notice this only happens if I click on the 9th day)
![screen shot 2015-11-03 at 17 55 18](https://cloud.githubusercontent.com/assets/3918797/10914759/12948a70-8254-11e5-99a9-ef916846c811.png)

**Comment by renekorss** [comment]
Could you share you config object (`datepickerObject`) with us? I thought I fixed it today. Do you have master branch version? If not, update to master and see if it fixes it.

**Comment by comapedrosa** [comment]
Hello @renekorss my config object looks like this (note that I use moment.js):
```
    $scope.nextMonday = moment().day(8)
    $scope.nextMondayDate = $scope.nextMonday._d
    $scope.yesterday = moment().subtract(1, 'days');

    $scope.datepickerObject = {
      titleLabel: 'Select a date to begin the program',
      mondayFirst: true,
      inputDate:  $scope.nextMondayDate,
      templateType: 'popup',
      showTodayButton: 'true',
      from: $scope.yesterday._d,
      callback: function (val) {
        datePickerCallback(val);
      }
    };
```
Yesterday I downloaded this library and I guess I was a few minutes ago of the new release, today I updated it to the master branch but I went back to the previous version because when I change the ionic-datepicker.bundle.min.js file, my datepicker with this configuration looks as it follows:
![screen shot 2015-11-04 at 09 39 27](https://cloud.githubusercontent.com/assets/3918797/10933448/d563f1b0-82d8-11e5-820e-ad7182d56dad.png)
Notice that neither the months/years select box are visible (if I click on them the month/year selection apperas though) nor none of the days is selected on the calendar.

**Comment by comapedrosa** [comment]
Sorry I closed the issue by mistake! :)

**Comment by rajeshwarpatlolla** [comment]
For now i suggest you not use the master branch code. There are few PR's merged which i haven't tested. As of now you can use the latest release.

**Comment by comapedrosa** [comment]
Ok for now I'm gonna go with the latest release. Looking forward to the next one and congrats for this awesome project! ;)

**Comment by renekorss** [comment]
If @rajeshwarpatlolla will merge this PR, your problem will be resolved.

**Comment by comapedrosa** [comment]
@rajeshwarpatlolla @renekorss works like a charm!Thank you guys!
