### ISSUE TITLE
Pass model on callback

### ISSUE THREAD

**Issue by Hacktivista** [rajeshwarpatlolla/ionic-datepicker#104]
I think that would be great if one could use the model of an element as parameter on callback, since if for example you need to add 10 dates in a form, with the current approach you would need to create 10 inputObjects, am I right?

**Comment by renekorss** [comment]
You could create only one and clone other 9, for example with [underscore clone](http://underscorejs.org/#clone).

If datepicker would send `inputObject` back to callback, it still would be reference to that. So you still have to clone it.

**Comment by Hacktivista** [comment]
I say that you could pass the model ur'e using, not the JS object
