### ISSUE TITLE
TypeError: e.getFullYear is not a function

### ISSUE THREAD

**Issue by metasean** [rajeshwarpatlolla/ionic-datepicker#11]
I have two modal forms, a "create" and an "update".  ionic-datepicker is working superbly on the "create" form; but I'm having problems on the "update" form.

The date pulls in and displays perfectly when the "update" form loads.  However, when I click on the datepicker field to edit it, the console shows the following message: 
`TypeError: e.getFullYear is not a function"` which points to `lib/ionic-datepicker/dist/ionic-datepicker.js 1:640`

I'm running ionic 1.0.0-rc.5, angular 1.3.13, and bower's version 0.1.3 of ionic-datepicker (differs from your package.json version number of 0.0.1).

Any ideas what might be causing this error?

**Comment by rajeshwarpatlolla** [comment]
May be you are not passing values i mentioned in the description.
