### ISSUE TITLE
dateFormat does not work fully

### ISSUE THREAD

**Issue by AndresKessler** [rajeshwarpatlolla/ionic-datepicker#110]
The date inside the datepicker popup is not formatted according to dateFormat. There is a hardcoded "dd-MM-yyyy"

**Comment by rajeshwarpatlolla** [comment]
Could you add a screenshot of the same?

**Comment by AndresKessler** [comment]
My formatting string is "dd.MM.yyyy" and after selecting the date the date is represented according to this format. but inside the popup it is "05-11-2015"

<img width="1059" alt="screenshot 2015-11-05 12 10 03" src="https://cloud.githubusercontent.com/assets/12291647/10965522/45c71bf2-83b6-11e5-8756-197bc9486031.png">

**Comment by rajeshwarpatlolla** [comment]
As of now there is no customization for this? where you are setting the date format to show on the modal ?

**Comment by AndresKessler** [comment]
Inside the datepicker settings object

$scope.datepickerStart = {
        mondayFirst: true,
        dateFormat: "dd.MM.yyyy",
        closeOnSelect: true,
        titleLabel: $scope.translations.datePicker_selectDate,
        todayLabel: $scope.translations.datePicker_today,
        closeLabel: $scope.translations.datePicker_close,
        setLabel: $scope.translations.datePicker_set,
        weekDaysList: $locale.DATETIME_FORMATS.SHORTDAY,
        monthList: $locale.DATETIME_FORMATS.MONTH,
        modalHeaderColor: "bg-light-green",
        modalFooterColor: "bg-light-green",
        inputDate: $scope.operation.startDate,
        callback = function (val) {
               datePickerCallback(true, val);
        }
    };

**Comment by AndresKessler** [comment]
Actually "closeOnSelect" does not seem to do anything either, but that is already another issue.

**Comment by rajeshwarpatlolla** [comment]
Please don't use the recently committed code. That latest code on the master branch is from the PR's merged. Please use the latest release only.

**Comment by renekorss** [comment]
@AndresKessler I think that you installed release 0.9.0, and that's why both `dateFormat` and `closeOnSelect` dosen't work. They are only available right now in master branch version.

**Comment by AndresKessler** [comment]
Yes, I did the regular bower install. Will they be available in regular install version at some point?

**Comment by renekorss** [comment]
If @rajeshwarpatlolla makes release, then it will be available by default. Meanwhile you could install it with `bower install ionic-datepicker#master --save` to get install master branch version. 

**Note:** I have [open PR](https://github.com/rajeshwarpatlolla/ionic-datepicker/pull/113) for fixing little error. But it works withput it too, just console would have one error on datepicker load.

**Comment by AndresKessler** [comment]
All right. Thank you for the really quick responses. I'll wait for the release.

**Comment by renekorss** [comment]
No problem. You sohuld close your issue, if it's no problem anymore.

**Comment by AndresKessler** [comment]
Hopefully this will be then in the next version...
