### ISSUE TITLE
closeOnSelect doesn't work

### ISSUE THREAD

**Issue by chompunut** [rajeshwarpatlolla/ionic-datepicker#111]
I installed the latest commit (b26ca2ecc151d2583316ecd7a46ea6eb0c2272d6) to use the `closeOnSelect` option.
When I set `closeOnselect = true`, many bugs showing:

1) The callback function is executed at the first loading the picker (this doesn't happen if I set `closeOnSelect = false`)

2) It shows error `TypeError: Cannot read property 'close' of undefined` 
on `ionic-datepicker.bundle.min.js` at 
```javascript
a.dateSelected(y), a.$watch("date_selection.selectedDate", function (e, t) {
     a.closeOnSelect && (c(), "modal" === a.templateType.toLowerCase() ? a.closeModal() : a.popup.close())
})
```
3) When I select a date or Today/Close button, the popup doesn't close but the callback function still be executed.

Here is my options settings:
```
$scope.datepickerObject = {
    closeOnSelect: true, 
    templateType: 'popup',
    to: new Date(),
    callback: function (date) { 
          console.log('callback');
    }
};
```
in html:
```
<div class="col" ionic-datepicker input-obj="datepickerObject">
        {{item.personbirthdate | bdate}}
</div>
```

Please help. Thank you in advance.

**Comment by rajeshwarpatlolla** [comment]
Please don't use that code. Its not yet tested. Please use the latest release.

**Comment by chompunut** [comment]
Which is the latest release? I installed version 0.9.0 the closeOnSelect doesn't work as well. I set it to true but when I select a date, the popup doesn't close and no error message.
