### ISSUE TITLE
dateFormat does not work in v.0.9.0

### ISSUE THREAD

**Issue by tavishledesma** [rajeshwarpatlolla/ionic-datepicker#115]
I changed dateFormat from its default ('dd-MM-yyyy') to other variants, including:

- 'MM-dd-yyyy' 
- 'MMMM dd, yyyy'

None of these are being reflected in the popup box. It still shows as dd-MM-yyyy.

**Comment by rajeshwarpatlolla** [comment]
This is not available in v0.9.0. As of now this is only available in master branch. And kindly please take a look at the closed bugs/openbugs before raising a bug. Few of the bugs might have addresses in those issues.
