### ISSUE TITLE
Typo in "How to use" guide

### ISSUE THREAD

**Issue by tavishledesma** [rajeshwarpatlolla/ionic-datepicker#116]
The "How to use" guide is missing a comma after the callback function, which took me a while to figure out when implementing:

    $scope.datepickerObject = {
     ...
      callback: function (val) {  //Mandatory
        datePickerCallback(val);
      }, <----- missing comma
      dateFormat: 'dd-MM-yyyy', //Optional
      closeOnSelect: false, //Optional
    };

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
