### ISSUE TITLE
from: new Date() and to: new Date()

### ISSUE THREAD

**Issue by comapedrosa** [rajeshwarpatlolla/ionic-datepicker#117]
When you set the properties of the $scope.datepickerObject if you put `to: new Date()` everything works fine, you can select all the days that are before the date and you can also select the today date.
```
    $scope.datepickerObject = {
      titleLabel:  $scope.datePickerTitle,
      todayLabel: $scope.todayText,
      closeLabel: $scope.closeText,
      setLabel: $scope.setText,
      inputDate: new Date(),
      mondayFirst: true,
      templateType: 'popup',
      showTodayButton: 'true',
      to: new Date(),
      callback: function (val) {
        datePickerCallback(val);
      }
    };
```
But when you use the` from: new Date()` you are able to select all the upcoming dates but not the today date. What I have done to fix it is to create an object date with the yesterday's date. It would be great that the ` from: new Date()` wuld let you select all the upcoming days including today.

Note that for the example I'm using moment.js
```
    $scope.yesterday = moment().subtract(1, 'days');
    $scope.datepickerObject = {
      titleLabel: $scope.datePickerTitle,
      todayLabel: $scope.todayText,
      closeLabel: $scope.closeText,
      setLabel: $scope.setText,
      mondayFirst: true,
      inputDate: new Date(),
      templateType: 'popup',
      showTodayButton: 'true',
      from: $scope.yesterday._d,
      callback: function (val) {
        datePickerCallback(val);
      }
    };
```

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
