### ISSUE TITLE
Bug: Dates are not refreshed when switching months 

### ISSUE THREAD

**Issue by evtaylor** [rajeshwarpatlolla/ionic-datepicker#119]
Bug occurs in the following scenario:

1. Select a date that occurs in October (but don't press Set)
2. Press the previous month arrow
3. Use the month select dropdown to switch the month back to October
4. Dates do not refresh for October

**Comment by rajeshwarpatlolla** [comment]
Could you please share a codepen?

**Comment by evtaylor** [comment]
This bug occurs even on the demo page for the ionic datepicker if you follow the steps I mentioned above:

http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker

**Comment by sckoh** [comment]
year is not updated too.

1. open datepicker with inputDate = 1-1-2016
2. select year 2017
3. press cancel.
4. open datepicker with inputDate = 1-1-2016 again
5. but the year is showing 2017
6. select date 25-1 without changing month or year.
7. the callback will return 25-1-2016
