### ISSUE TITLE
Date format change

### ISSUE THREAD

**Issue by Jigar1984** [rajeshwarpatlolla/ionic-datepicker#120]
Hi I try to change date format but I am not able to change..
Please help me.
I need required format is 'yyyy - MM - dd' instead of 'Sat Nov 14 2015 00:00:00 GMT+0530 (IST)'

I try to change this way but not working.

<button class="button button-block button-calm item-positive" >Date :
		{{datepickerObject.inputDate | date:'yyyy - MM - dd'}}</button>

Thanks..

**Comment by emirdeliz** [comment]
+1

**Comment by renanss** [comment]
+1

**Comment by rajeshwarpatlolla** [comment]
You have a ** dateFormat** property when you create an object. Please check  the documentation.

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
