### ISSUE TITLE
closeOnSelect

### ISSUE THREAD

**Issue by KevinGF** [rajeshwarpatlolla/ionic-datepicker#121]
When I set closeOnSelect to true, meet error "TypeError: Cannot call method 'close' of undefined"

**Comment by kerosin** [comment]
https://github.com/rajeshwarpatlolla/ionic-datepicker/blob/master/src/ionic-datepicker.directive.js#L317-L320
Are you using popup or modal datepicker?

**Comment by KevinGF** [comment]
@kerosin I am using popup. But, when use modal, the error will occur too

**Comment by kerosin** [comment]
Can you provide your code somewhere? (e.g. codepen)

**Comment by gebidesign** [comment]
Getting the same error using popup with closeOnSelect enabled. For whatever reason popup is undefined here https://github.com/rajeshwarpatlolla/ionic-datepicker/blob/master/src/ionic-datepicker.directive.js#L320

**Comment by KevinGF** [comment]
@kerosin , please refer to following code

	var datePickerCallback = function (val) {
		  if (typeof(val) === 'undefined') {
		    console.log('No date selected');
		  } else {
			$scope.testDate = $filter('date')(val,'yyyy-MM-dd');
		    console.log('Selected date is : ', $scope.testDate);
		  }
		};
	var weekDaysList = ["日", "一", "二", "三", "四", "五", "六"];
	var monthList = ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"];
	var disabledDates = [];
	$scope.datepickerObject = {
		      titleLabel: '购买日期',  //Optional
		      todayLabel: '当前',  //Optional
		      closeLabel: '关闭',  //Optional
		      setLabel: '确定',  //Optional
		      setButtonType : 'button-positive',  //Optional
		      todayButtonType : 'button-assertive',  //Optional
		      closeButtonType : 'button-stable',  //Optional
		      inputDate: new Date(),  //Optional
		      mondayFirst: true,  //Optional
		      disabledDates: disabledDates, //Optional
		      weekDaysList: weekDaysList, //Optional
		      monthList: monthList, //Optional
		      templateType: 'popup', //Optional, 'popup' or 'modal'
		      showTodayButton: 'false', //Optional
		      modalHeaderColor: 'bar-positive', //Optional
		      modalFooterColor: 'bar-positive', //Optional
		      callback: function (val) {  //Mandatory
		        datePickerCallback(val);
		      },
		      dateFormat: 'yyyy-MM-dd', //Optional
		      closeOnSelect: false, //Optional
	};

**Comment by b3na** [comment]
For me it doesn't give any errors, but I have it set to true and the 'Set' button still there, and the the modal doesn't close on select.

       $scope.datepickerObject = {
         titleLabel: 'Title',  //Optional
         todayLabel: 'Today',  //Optional
         closeLabel: 'Close',  //Optional
         setLabel: 'Set',  //Optional
         setButtonType : 'button-positive-bbteal',  //Optional
         todayButtonType : 'button-positive-bbteal',  //Optional
         closeButtonType : 'button-positive-bbteal',  //Optional
         inputDate: new Date($scope.lastImageDate),  //Optional
         mondayFirst: true,  //Optional
         templateType: 'popup', //Optional
         showTodayButton: 'true', //Optional
         modalHeaderColor: 'bar-bbteal', //Optional
         modalFooterColor: 'bar-bbteal', //Optional
         from: new Date(2012, 8, 2), //Optional
         to: new Date(2018, 8, 25),  //Optional
         callback: function (val) {  //Mandatory
           datePickerCallback(val);
         },
         dateFormat: 'dd-MM-yyyy', //Optional
         closeOnSelect: true, //Optional
       };

     var datePickerCallback = function (val) {
       if (typeof(val) === 'undefined') {
         console.log('No date selected');
       } else {
         console.log('Selected date is : ', val)
         $scope.datepickerObject.inputDate = val;
         $scope.loadphoto(val);

       }
     };

**Comment by b3na** [comment]
On popup the date changes on select, but the popup doesn't close and if i choose modal, the modal appears and closes immediately staying on the same date.

**Comment by rajeshwarpatlolla** [comment]
Same as https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/112
