### ISSUE TITLE
Scroll and edit feature

### ISSUE THREAD

**Issue by fmiboy** [rajeshwarpatlolla/ionic-datepicker#122]
Is it possible to use input instead of buttons so that user can edit as well?
Or
Allow scrolling during selection would be great, similar swipe or scroll effect in here:
![screenshot_2015-11-16-19-45-10](https://cloud.githubusercontent.com/assets/3015990/11209051/c220f26c-8d44-11e5-83c4-7111c3282329.png)

**Comment by kerosin** [comment]
![Image of Datepicker of Sencha Touch 2](http://i63.tinypic.com/343m15u.png)

Sencha Touch 2 has a nice datepicker with different roller slots

**Comment by fmiboy** [comment]
but how i can use it in ionic project without too much library dependencies?

**Comment by rajeshwarpatlolla** [comment]
In order to have this feature we may need to add few third party plugins, which will make this component heavy.
