### ISSUE TITLE
Getting wrong dates in Ionic Android Project With Crosswalk

### ISSUE THREAD

**Issue by WendellAdriel** [rajeshwarpatlolla/ionic-datepicker#123]
Hi, I don't know if this happened with someone before.

I have an app that I'm creating with Ionic and I export the app for Android and iOS. I have a screen that has two date fields with this plugin. In iOS and in the browser (Ionic lab) the dates are correct (when I send them to my API), but when I select and send the dates with an Android device, both dates are one day less.

***Example:
When I select the dates From: 12/10/2015 To: 12/25/2015***

In browser and iOS the dates stay the same, but when I select the same dates in Android, the dates become:

***From: 12/09/2015 To: 12/24/2015***

Anyone else experienced this already?

**Comment by rajeshwarpatlolla** [comment]
This should not happen. Which timezone you are in?

**Comment by WendellAdriel** [comment]
Brazilian time (UTC-03). I don't know if this is caused by the plugin or if this is caused by some server configuration. I wanted to know if this happened with someone else, but seems that I'm the only one with this problem, so maybe it's not a plugin issue...I don't know yet...

**Comment by rajeshwarpatlolla** [comment]
This plugin will return only the selected dates. And also it is not related to any server configuration. Please cross check you system date.

**Comment by sijovijayan** [comment]
I have the same issue, If i select 17-04-2016 then it return 16-04-2016

**Comment by rajeshwarpatlolla** [comment]
I tried selecting those dates, but i didn't had this issue. Please check the screenshot.

![screen shot 2016-04-17 at 6 20 28 pm](https://cloud.githubusercontent.com/assets/9896335/14587067/21527d90-04c9-11e6-8508-637f7338df75.png)

**Comment by sijovijayan** [comment]
The problem occur when i convert this value using "toISOString" method. This is because of the timezone difference.
But i have fixed this issue using the following code.

	var dateObj = new Date(val);
	$scope.game.date = dateObj.getFullYear()+'-'+("0" + (dateObj.getMonth()+1)).slice(-2)+'-'+("0" + (dateObj.getDate())).slice(-2);

It will return the the date in YYYY-MM-DD format. 
Thank you @rajeshwarpatlolla

**Comment by rajeshwarpatlolla** [comment]
This will give u the local time. If you want to convert to some other time zone, try to play with the timezone offset. Hope that will help you.
