### ISSUE TITLE
offset days of the week

### ISSUE THREAD

**Issue by borodatych** [rajeshwarpatlolla/ionic-datepicker#124]
When the two choices of dates on the same page there is a shift weekdays. 
We must declare so:
var weekDaysList = ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"];
instead:
var weekDaysList = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

Let the bonus question on iOS but to click on the outside as much as possible and close the month_dropdown year_dropdown? Buttons not any there, a little inconvenient.

**Comment by rajeshwarpatlolla** [comment]
I have tested in both android and iPhone. It's working fine. Could you please check the demo i mentioned in the repository.
