### ISSUE TITLE
How i disable all previous date ?

### ISSUE THREAD

**Issue by Haideralee** [rajeshwarpatlolla/ionic-datepicker#125]
i can't find a way to disable all previous date and today button are not hide when i'm set 'false' in 'showTodayButton' key. can anyone help me ?

**Comment by b3na** [comment]
You can set the 'from' parameter to the date you want, so all dates before that will be disabled.

from(Optional) : This is a date object, from which you wish to enable the dates. You can use this property to disable previous dates by specifying from: new Date(). 

I can help you if you paste your code here or in a Codepen.

**Comment by Haideralee** [comment]
@b3na thanks it's working. :+1:  and today button are not disable from the datapicker's popup. i set the 
"showTodayButton: 'false'" and it's still showing on popup.

**Comment by rajeshwarpatlolla** [comment]
This feature is there in the last release. Can you please share you code?

**Comment by rajeshwarpatlolla** [comment]
You can use the `to : new Date()` to disable all the previous dates. You can adjust the days you pass to the from property to handle the disable dates.
