### ISSUE TITLE
Error: [$compile:nonassign] Expression 'undefined' used with directive 'ionicDatepicker' is non-assignable!

### ISSUE THREAD

**Issue by vivekpandey0460** [rajeshwarpatlolla/ionic-datepicker#126]
After implementation of date picker, i am stuck with the error .
Error: [$compile:nonassign] Expression 'undefined' used with directive 'ionicDatepicker' is non-assignable!

Please help me on this.

Thanks

**Comment by rajeshwarpatlolla** [comment]
Could you share the code snippet?

**Comment by vivekpandey0460** [comment]
View File: 
<ionic-datepicker input-obj="customer.datepickerObject">
          <a class="button button-outline icon-left ion-android-calendar button-balanced">Select Date</a>
        </ionic-datepicker>


In Controller: 
vm.datepickerObject = {			
			callback: function (val) {				
	        datePickerCallback(val);
	      }
		};

		var datePickerCallback = function (val) {
		  if (typeof(val) === 'undefined') {
		    console.log('No date selected');
		  } else {
		    console.log('Selected date is : ', val)
		  }
		};

And i am using [[  ]] bracket for angularjs expression instead of {{  }}, is that causing the problem?

**Comment by rajeshwarpatlolla** [comment]
Try removing and check it. It depends on the version of ionic you are using.

**Comment by vivekpandey0460** [comment]
How it depend upon the ioinc version, It should not be the problem because i am just changing the angularjs expression syntax using $interpolateProvider , how it depend on your directive which you have written.

**Comment by rajeshwarpatlolla** [comment]
The square brackets does not work. Try with {{}}.
