### ISSUE TITLE
Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by ulion** [rajeshwarpatlolla/ionic-datepicker#127]
function(e,t){a.closeOnSelect&&(c(),"modal"===a.templateType.toLowerCase()?a.closeModal():a.popup.close())}

the a.popup is undefined, templateType is not specified. current master code

**Comment by rajeshwarpatlolla** [comment]
You are inside a function, which is taking two arguments `e` and `t`. There is no `a`. That's the reason you are getting this error. There is no reference to `a`.
