### ISSUE TITLE
Make the corresponding service

### ISSUE THREAD

**Issue by hlehmann** [rajeshwarpatlolla/ionic-datepicker#128]
Hi,

It would be very useful to make the datepicker available on a service like `$ionicDatePicker.show(options)` with the exact same set of options. Is it possible ?

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
