### ISSUE TITLE
set max range 

### ISSUE THREAD

**Issue by anshulklr** [rajeshwarpatlolla/ionic-datepicker#13]
can you please help me in how to set up a range of selected dates in datepicker?
and how can i change the minimum selection date to today , so that user don't select the previous date

**Comment by rajeshwarpatlolla** [comment]
As of now this component does not support setting ranges.

**Comment by anshulklr** [comment]
is there anything available to stop the user from selecting an expired date??/

**Comment by rajeshwarpatlolla** [comment]
I designed it by assuming people can use even the past dates like for credit card. So i didn't implemented such functionality for now. But once the date has been selected then you can get the date value and display some error message. I am little busy these days. If i can get some time i will implement this feature. Few people also suggested this feature.

**Comment by anshulklr** [comment]
thankyou
