### ISSUE TITLE
not working with ionic 1.2

### ISSUE THREAD

**Issue by tbro028** [rajeshwarpatlolla/ionic-datepicker#130]
Doesn't appear to be working with ionic 1.2

**Comment by rajeshwarpatlolla** [comment]
I havn't tested it with ionic v1.2. Once it's officially released, i will test in v1.2 also.

**Comment by HyundoKim** [comment]
Same here. It worked fine with Ionic 1.1.1 but it looks broken in 1.2.1.

![ionic-datepicker screenshot](https://cloud.githubusercontent.com/assets/16457416/12110472/d0c82176-b3cf-11e5-9d71-a39e63796a37.png)

**Comment by rajeshwarpatlolla** [comment]
I think this is purely CSS issue. I have already defined a few css classes, which will help you to resolve this issue. For now you can play with the css classes defined there. In future releases i can do that in this component itself.

**Comment by HyundoKim** [comment]
Hi. Thank you for the fast response.
Apart from the digits displaying in two rows, the two boxes (month_dropdown, year_dropdown?) above the {S, M, T, ...} line displays nothing.

**Comment by rajeshwarpatlolla** [comment]
I have added the css classes for the cells as well as for the dropdowns. So you can override them to have the proper UI.

**Comment by rajeshwarpatlolla** [comment]
Tested with `v1.2.4`. Working fine.
![screen shot 2016-01-17 at 10 49 29 am](https://cloud.githubusercontent.com/assets/9896335/12376083/058c8c80-bd08-11e5-80d2-3c9d6f3d5428.png)
