### ISSUE TITLE
Disable Select Date but can change Month

### ISSUE THREAD

**Issue by arafay696** [rajeshwarpatlolla/ionic-datepicker#131]
Hi,

i want to disable calendar for select date but not want to disable Left arrow,month_dropdown,year_dropdown. user just change/select month.

Thanks,
Abdul Rafay

**Comment by rajeshwarpatlolla** [comment]
When you mention **to** and **from** in the object, that will disable the dates along with the arrows too, so that the user will not be able to navigate to the disabled dates.
