### ISSUE TITLE
Date picker is completely broken on Android 4.1.2

### ISSUE THREAD

**Issue by janigorse** [rajeshwarpatlolla/ionic-datepicker#132]
Hi, Just look at the picture:

![picker_android_412](https://cloud.githubusercontent.com/assets/1881039/11898687/1c7b6eaa-a59a-11e5-83b8-e4df8a23716b.jpg)

**Comment by rajeshwarpatlolla** [comment]
This component completely depends on the Ionic CSS. Android version before kitkat won't render the components as they intended. You need to override the CSS to work with it. It renders properly from android kitkat onwards.
