### ISSUE TITLE
Some styles are not customisable

### ISSUE THREAD

**Issue by mcintosh101** [rajeshwarpatlolla/ionic-datepicker#133]
There are certain classes like `.color_blue` which have `!important` on them making it hard to overwrite some of the styles for the navigation arrows (amongst other things) without editing the core code.

**Comment by olasfar** [comment]
+1 can't we use sass with variables ? customization will be much more easier :)

**Comment by rajeshwarpatlolla** [comment]
Thanks for your suggestion @olasfar.

**Comment by olasfar** [comment]
@rajeshwarpatlolla any ETA for this feature ? :)

**Comment by mcintosh101** [comment]
Yeah, this would be a great feature to have. I'm also interested in an ETA.

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
