### ISSUE TITLE
Datepicker doesot show up on edit date screen

### ISSUE THREAD

**Issue by Karabi-Choudhury** [rajeshwarpatlolla/ionic-datepicker#135]
Hi,

Thanks for creating this wondeful datepicker. I am facing and issue in it.
The first time i set the date it works fine , the next time when i come to the page to edit the date, it throws me an error and the calendar doesn't open.
The error shown in the console in
" c.setHours is not a function".
I get the date in the format 2015-12-28T18:30:00.000Z. How do i rectify it?

Thanks,
Karabi

**Comment by rajeshwarpatlolla** [comment]
You need to pass some date to the input object. Are you doing the same in the edit date page? Please check by logging the passed object before passing it to this component.

**Comment by shuhankuang** [comment]
make sure that your inputDate is not a string.
https://github.com/rajeshwarpatlolla/ionic-datepicker/pull/142
