### ISSUE TITLE
Datepicker and timepicker reverts back to original view upon clicking

### ISSUE THREAD

**Issue by cornstar94** [rajeshwarpatlolla/ionic-datepicker#136]
Hi, thanks for the great tool you've created. Im facing some minor issues whereby everytime the datepicker and timepicker are clicked, it reverts back from my "Add Items" page to my "Items" page and it automatically creates a new item without me clicking "Create". 

This is my HTML code:

       <ion-view view-title="Items">
           <div ng-if="!tb.isCreating && !tb.isEditing">
               <ion-content class="padding has-header">

               <div class="bar bar-header">
                 <span><button class="button button-positive" ng-click="tb.goToBackand()">Need Help?       </button></span>
                <span ng-click="tb.isCreating = true"><i class='icon ion-plus-round new-item'> Add Item</i>   </span>
            </div>
            <div class="bar bar-subheader">
                <div class="list card" ng-repeat="object in tb.data"
                     ng-class="{'active':tb.isCurrent(object.id)}">
                    <div class="item item-icon-right item-icon-left">
                        <i class="ion-compose icon" ng-click="tb.setEdited(object)"></i>

                        <h2 class="text-center">{{object.name}}</h2>
                        <i class="icon ion-close-round" ng-click="tb.delete(object.id)"></i>
                    </div>
                    <div class="item item-body">
                        {{object.description}}
                    </div>
                </div>
            </div>
        </ion-content>
    </div>
    <div ng-if="tb.isCreating">

        <ion-content class="padding has-header">
            
            <div class="bar bar-subheader">
    <form class="create-form" role="form" ng-submit="tb.create(tb.newObject)">
                <div class="list">

                    <div class="row">
                        <div class="col">
                            <label class="item item-input">
                                <input  
                                type="text" 
                                ng-model="tb.newObject.name" 
                                placeholder="Name of Event">
                            </label>
                        </div>
                    </div>

                    <div class="row">
                      <div class="col">
                            <label class="item item-input">
                                <input name="location" 
                                type="text" 
                                ng-model="tb.newObject.location"
                                placeholder="Location">
                            </label>
                        </div>
                      </div>

                      <div class="row">
                            <div class="col" >
                                <label class="item item-input small-word" >
                                Start Date: <br> 
                                                <ionic-datepicker input-obj="datepickerObject" ng-click="tb.isCreating = true" >
                                                      <button class="button button-block button-positive" > {{datepickerObject.inputDate | date:'dd-MMM-yy'}}</button> 
                                                    </ionic-datepicker>                            

                                </label>
                            </div>

                            <div class="col">
                                <label class="item item-input small-word" ng-model="tb.newObject.startTime">
                                Start Time: <br>                                 
                                    <ionic-timepicker input-obj="timePickerObject">
                                        <button class="button button-block button-positive overflowShow" >{{timePickerObject.inputEpochTime * 1000 | date:"hh:mm a": 'GMT'}}
                                          <standard-time-meridian etime='timePickerObject.inputEpochTime'></standard-time-meridian>
                                        </button>
                                      </ionic-timepicker>
                                </label>

                            </div>
                          </div>
                       
                        
                            <div class="row">
                                <div class="col">
                                    <label class="item item-input small-word">
                                    End Date: <br> 
                                                <ionic-datepicker input-obj="datepickerObject2">
                                                      <button class="button button-block button-positive"> {{datepickerObject2.inputDate | date:'dd-MMM-yy'}}</button>
                                                    </ionic-datepicker>
                                </label>
                                </div>

                            <div class="col">
                                <label class="item item-input small-word">
                                End Time: <br>                                 
                                    <ionic-timepicker input-obj="timePickerObject2">
                                        <button class="button button-block button-positive overflowShow">{{timePickerObject2.inputEpochTime * 1000 | date:"hh:mm a": 'GMT'}}
                                          <standard-time-meridian etime='timePickerObject2.inputEpochTime'></standard-time-meridian>
                                        </button>
                                      </ionic-timepicker>
                                </label>
                            </div>               
                          </div>

                          </div>

                          <div class= "col">
                                 <button class="button button-block button-positive" type="submit"> 
                                 Create Event 
                                 </button>
                            </div>

                            <div class= "col">
                                 <button class="button button-large button-calm"> Invite Friends </button>
                            </div>
                        </form>
                        </div>

                        
    <div ng-if="tb.isEditing && !tb.isCreating">
        <ion-content class="padding has-header">

        
            
            <div class="bar bar-header bar-secondary">
                <h1 class="title">Editing {{tb.edited.name}}</h1>
                <span ng-click="tb.cancelEditing()" class="cancel-create">Cancel</span>
            </div>
            <div class="bar bar-subheader">
                <form class="edit-form" role="form"
                      ng-submit="tb.update(tb.edited)" novalidate>
                    <div class="list">
                        <label class="item item-input item-stacked-label">
                            <span class="input-label">Name</span>
                            <input type="text" class="form-control"
                                   ng-model="tb.edited.name"
                                   placeholder="Enter name">
                        </label>
                        <label class="item item-input item-stacked-label">
                            <span class="input-label">Description</span>
                    <textarea class="form-control"
                              ng-model="tb.edited.description"
                              placeholder="Enter description"></textarea>

                        </label>
                    </div>
                    <button class="button button-block button-positive" type="submit">Save</button>
                </form>
            </div>
        </ion-content>
    </div>
</ion-view>

**Comment by rajeshwarpatlolla** [comment]
I don't think this is an issue from the plugin. This should not happen. The only thing this can do is giving you some date when you select it. I think some things needs to be checked from the code. If possible could you please post a plunker?

**Comment by cornstar94** [comment]
Thanks for your prompt reply, but I am unable to access plunker now. I'll post one up once its working.

**Comment by cornstar94** [comment]
@rajeshwarpatlolla sorry I still can't access it and I am not good with fiddle either. Will a link to my github suffice? Thanks for your help!

https://github.com/cornstar94/mycorn123

**Comment by cornstar94** [comment]
@rajeshwarpatlolla Hi, here's my github repo for your reference. I still can't access plunker.

https://github.com/cornstar94/finalproj

**Comment by rajeshwarpatlolla** [comment]
Please cross check the instructions i mentioned in the repo. The navigation to some other page is not at all related to this component. I think, there is something missing in your code. It's really hard for me to take a look at your code, as it needs some time for me to understand and find the issue.
I can suggest you to take  a look at the component instructions and follow the exact same way.
