### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by buymybm100** [rajeshwarpatlolla/ionic-datepicker#139]
Hi Rajesh, 

Thanks for sharing this plugin, it is very useful.

Was wondering if you can add an "id" attribute to the Directive ?
Then, pass the "id" to the  callback.    eg.  callback(selectedDate, id)
It will be useful when a page has multiple <ionic-datepicker>s in one Form.

My problem is : I have a list of Dates , which I update on-the-fly after <ionic-datepicker> is Closed.
Currently, the callback only passes the SelectedDate , but I don't know which input date  it was for.

The proposed solution would look like this : 

Eg. 
<ionic-datepicker id="startDate" ... input-obj="datepickerObject">
<ionic-datepicker id="endDate" ... input-obj="datepickerObject">

  $scope.datepickerObject = {
      ...
       callback: function (val, id ) {     // pass back "id" 
        console.log ("The unique id is " + id );
        console.log ("Selected date is " + val );
       },

Many Thanks,
Beemer

**Comment by rajeshwarpatlolla** [comment]
If you have multiple date-pickers, you need to have multiple objects for each one, so that the callback will be invoked in the respected object's callback.
