### ISSUE TITLE
getting selected value to the controller

### ISSUE THREAD

**Issue by anshulklr** [rajeshwarpatlolla/ionic-datepicker#14]
i'm unable to get the user selected date at the controller , it always giving the right now time rather than the selected time. In the view it shows the correct selected date , but not at the controller

**Comment by anshulklr** [comment]
can you help me with this, its a little urgent?

**Comment by rajeshwarpatlolla** [comment]
It will be stored in the `$scope.currentDate` variable.

**Comment by anshulklr** [comment]
i tried checking , the value gets shown on the view after the set date, but if you check the value in the controller,its still the same

**Comment by rajeshwarpatlolla** [comment]
Call back function is added in `ionic-datepicker v0.3.0`. Please install this version to get the correct values in to the controller.
