### ISSUE TITLE
Week number feature

### ISSUE THREAD

**Issue by hastursan** [rajeshwarpatlolla/ionic-datepicker#140]
It'll be a great feature to have the option to show the week number. I had some users asking me for this feature in apps with calendars.

**Comment by smika01** [comment]
Hi, I got same request from my users. Is there someone working on this?
If not may be I can start here to create a PR on this. Any ideas here?

**Comment by rajeshwarpatlolla** [comment]
As of now, you don't have a feature to see the week numbers.
