### ISSUE TITLE
double click result to closing the parent modal

### ISSUE THREAD

**Issue by leizard** [rajeshwarpatlolla/ionic-datepicker#143]
I use ionic datepicker inside a ionic modal. 
If I single-click to ionic-datepicker, it appears properly, but if I double click to ionic-datepicker, it appears but close the parent modal at the same time.
How could I fix this ?

**Comment by rajeshwarpatlolla** [comment]
May i know what is the exact need to double click it. You can only click it once. If you don't want to allow users to click multiple times, then you can disable the button on first click.

**Comment by leizard** [comment]
Thank you for your reply!
It 's not a usual use case when user double click the datepicker. But if they do, the issue happen, so I just want to prevent them from doing that. Is it possible to disable the button in the end of the ng-click function ?

**Comment by rajeshwarpatlolla** [comment]
Yes, you can disable the button. Check [this link](https://docs.angularjs.org/api/ng/directive/ngDisabled). Once the user clicks on a button you can make it disable.
