### ISSUE TITLE
when change from parameters view doesn't change

### ISSUE THREAD

**Issue by elia-c** [rajeshwarpatlolla/ionic-datepicker#145]
I have two ionic-datepicker object: "start" and "end", I want that when someone change "end" date the start date change his from parameter according to end date minus some months. I create a watch to the value but when I change from parameter the view doesn't change according new value.

    $scope.$watch('endDate.inputDate', function (value) {
            if (value && $scope.maxMonths){
                var newStartDate = new Date(value);
                newStartDate.setMonth(newStartDate.getMonth() - $scope.maxMonths);
                $scope.startDate.from = newStartDate;
                if ($scope.StartDate.inputDate < newStartDate){
                    $scope.startDate.inputDate = null;
                }
            }
        });

**Comment by deckerj** [comment]
the reason for this is that the directive has an isolated scope and most scope variables from the controller are loaded once when the directive is created.

I had a similar issue with the label texts. Eventually, I forked the project and "refresh" the labels just before the popup is shown.

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
