### ISSUE TITLE
Feature Request - Make inputDate reactive

### ISSUE THREAD

**Issue by konsultaner** [rajeshwarpatlolla/ionic-datepicker#146]
It should be possible to change the inputDate from outside the datepicker. Maybe a ng-model would be helpful.

**Comment by ostruk** [comment]
:+1: Currently have to keep track of the date in two places - in my model and in the datepicker.

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
