### ISSUE TITLE
how to compile?

### ISSUE THREAD

**Issue by fgolemo** [rajeshwarpatlolla/ionic-datepicker#149]
Hi Rajeshwar,

thanks for your great Ionic module! :)

I did some modifications to the raw code (in the `src` folder), but now I don't know how to compile it into the minified version and include the HTML templates like you did. Could you elaborate please?

What I mean: how do I get from the contents of the `src` folder to the content of the `dist` folder?

Thanks a bunch in advance,
Florian

**Comment by rajeshwarpatlolla** [comment]
Just run `gulp build` command. It will do serve the purpose.
