### ISSUE TITLE
Year selection

### ISSUE THREAD

**Issue by lior-greenblatt** [rajeshwarpatlolla/ionic-datepicker#15]
Thanks for this :)
Just wanted to inquire if there are any plans of selecting a year?
e.g. to set birth date (think 20, 30, 40 years back)

**Comment by rajeshwarpatlolla** [comment]
For now, there is no such functionality. But i will try to implement in the future releases.

**Comment by lior-greenblatt** [comment]
Thanks for the prompt reply.

I took the liberty of playing around with it and added a selection with the following changes.
in the template:
  <div class="col col-80 text-center">{{currentMonth}} - <select ng-model="currentYear" ng-options="y as y for y in years" ng-change="changedYear(currentYear)"></select></div>
in the directive:
added to scope:
        yearsLow: '@'
        yearsHigh: '@'
added to link:
var i;
i = scope.yearsLow;
while (i >= 0) {
  scope.years.push(scope.today.year - i);
  i--;
}
i = 1;
while (i <= scope.yearsHigh) {
  scope.years.push(scope.today.year + i);
  i++;
}
scope.changedYear = function(newYear) {
  currentDate.setYear(newYear);
  scope.currentYear = currentDate.getFullYear();
  return refreshDateList(currentDate);
};
And finally used:
<ionic-datepicker idate="date" disablepreviousdates="false" years-low="50" years-high="10">
            <button class="button button-block button-positive"> {{ date | date:'dd - MMMM - yyyy' }} </button>
</ionic-datepicker>

Hope it helps :)

**Comment by lior-greenblatt** [comment]
One small thing I also noticed was the height of the calendar.
since some months show 6 weeks 180px wasn't enough (in case set was clicked before selecting a date) and the error message was under the last days of the month so I used 210px

**Comment by rajeshwarpatlolla** [comment]
Drop downs are added for selecting both month and year in the new version `v0.3.0`.

**Comment by lior-greenblatt** [comment]
Great!!
Thank you

**Comment by arumuganainar** [comment]
Error: [$compile:nonassign] Expression 'undefined' in attribute 'idate' used with directive 'ionicDatepicker' is non-assignable!
