### ISSUE TITLE
Pressing 'Enter' on other input fields open Calendar dialog

### ISSUE THREAD

**Issue by sufyan297** [rajeshwarpatlolla/ionic-datepicker#150]
Hello,
as i mentioned in title pressing 'Enter' on any other fields will open this Calendar dialog, this thing happens on PC and Mobile Keyboard...
Please fix this issue..

Thanks.
![beforepressingenter](https://cloud.githubusercontent.com/assets/836773/12551219/e7fe5abc-c38e-11e5-9d2e-afa5fd5cce8c.png)
![afterpressingenter](https://cloud.githubusercontent.com/assets/836773/12551221/ec02b4fa-c38e-11e5-9330-ebfab5924eb1.png)

**Comment by rajeshwarpatlolla** [comment]
This is not an issue from this component. You might have mentioned the type as submit on the button where you ara using this component. So please make the type as button instead of submit.
