### ISSUE TITLE
Feature Request: Disable days of the Week

### ISSUE THREAD

**Issue by Wakie87** [rajeshwarpatlolla/ionic-datepicker#151]
a simple function to disable a certain day. Eg. All mondays. 
disableDaysOfWeek: [0,1] // will disable all Sunday and Monday. (0 - Sunday, 1 - Monday)

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
