### ISSUE TITLE
Bug: Popup Datepicker 

### ISSUE THREAD

**Issue by danielschifano** [rajeshwarpatlolla/ionic-datepicker#152]
When you select the popup datepicker button in the demo it also selects the year dropdown in the datepicker popup. In order to replicate this you need to tap above "2016" on the button when the view is set to replicate the iPhone 6 Plus. I am using chrome but this also happens when I incorporated into my Ionic based project for a client.

**Comment by rajeshwarpatlolla** [comment]
This should not happen. If possible could you please provide me a codepen?

**Comment by rajeshwarpatlolla** [comment]
I tried to replicate this issue. But i didn't find this issue. Could you please add a codepen or a video?
