### ISSUE TITLE
Featured: deselect date on not mandatory date field

### ISSUE THREAD

**Issue by elia-c** [rajeshwarpatlolla/ionic-datepicker#153]
It would be very useful, especially for not mandatory date field, to have a way (like a X button next to the date) to deselect the current date and set it to null or undefined.

**Comment by peresbruno** [comment]
+1

**Comment by rajeshwarpatlolla** [comment]
null or undefined cannot be set, with this component. Either it will select whatever the date you pass to the input object or the one the user selects.
