### ISSUE TITLE
Todays Date is not setting in the title

### ISSUE THREAD

**Issue by jtoms** [rajeshwarpatlolla/ionic-datepicker#154]
When the date picker is open, todays date is showing as default selected and the "selected_date_full" also showing the taday's date. But when we select any other date and then click on 'Today' button todays date column is selected, but selected date is not reflecting in the top section  ('selected_date_full').

**Comment by ekaram** [comment]
Another note- the format is hard coded.  Can you please change this to use the format provided by dateFormat option?

<div class="selected_date_full">{{selectedDateFull | date: dateFormat }}</div>

For now, as a workaround, I am hiding this entirely: 

.selected_date_full{
  display:none
}

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
