### ISSUE TITLE
Number wrap in devices

### ISSUE THREAD

**Issue by galcivar** [rajeshwarpatlolla/ionic-datepicker#156]
I have run on iOS and Android, in both the days are "wrapped" turning the calendar basically unusable. 

![screenshot-2016-02-01_00 57 34 877](https://cloud.githubusercontent.com/assets/1395392/12709919/c20314ca-c87e-11e5-9b91-b92a8fbd5640.png)

**Comment by rajeshwarpatlolla** [comment]
I am not sure about the version of android, in which you are testing. I have provided a few css classes, to handle this kind situations. Please use those css classes to make the look and feel as you wish. Please take a look at the css classes [here](https://github.com/rajeshwarpatlolla/ionic-datepicker#css-classes)

**Comment by galcivar** [comment]
You're right, managed to fix it by using white-space:nowrap;

Should be part of the original css as I don't see a situation when the dates should be wrapped
