### ISSUE TITLE
losing date format when writing and reading back from localStorage

### ISSUE THREAD

**Issue by louisdoe** [rajeshwarpatlolla/ionic-datepicker#157]
Hi

I would like to save the date chosen by the user in the localStorage.

For now I am doing this:

           function datePickerCallback(val){
                $scope.datepickerObject.inputDate = val;
                localStorage.set('paramBirthday', $scope.datepickerObject.inputDate);
            }

the date is saved in the localStorage with the format:  "1984-07-19T22:00:00.000Z".

But then when I try to read it to initialize `datepickerObject` with the following code, it doesn't display in the 'dd-MM-yyyy' format.
    
    $scope.initializeBirthday = function() {
       var dum = localStorage.get('paramBirthday');
       dum = Date(dum);
       $filter('date')(dum, 'dd-MM-yyyy');
    }

    $scope.datepickerObject = {
             ...
             inputDate: $scope.initializeBirthday(),
             ...
             callback: function (val) {  //Mandatory
                datePickerCallback(val);
             },
             ...
    }

Do you know how to fix this ?
Maybe it's when I write it in the localStorage that I should convert it ?

Thanks

**EDIT**
I think I found an issue :

     function datePickerCallback(val){
                console.log('val:',val);
                console.log('valtoGMTString():',val.toGMTString());
    }

gives

    val: Wed Feb 05 1975 00:00:00 GMT+0100 (CET)
    valtoGMTString(): Tue, 04 Feb 1975 23:00:00 GMT

it's not the same day !

Maybe

**Comment by rajeshwarpatlolla** [comment]
You are saving the date in the string format. When you get it back then you need to convert it to the date object using `new Date(< selected date >)`.
