### ISSUE TITLE
Validation before closing Date or Time Picker

### ISSUE THREAD

**Issue by JayT82** [rajeshwarpatlolla/ionic-datepicker#158]
The time and Date picker close after pressing the set button.
Is there anyway to prevent this for example for validation purposes.
If validated then Set button is enabled is the requested functionality.

**Comment by mmimpen** [comment]
Indeed, that would be very helpful :)

**Comment by rajeshwarpatlolla** [comment]
There is no validation for this plugin. Based on the returned value, you can show some message to the users.
