### ISSUE TITLE
Calendar api also we can give in single full page.

### ISSUE THREAD

**Issue by altaf933** [rajeshwarpatlolla/ionic-datepicker#159]
I have made a single full page Calendar please find attached file .
 Please consider as enhancement. 

 
![screenshot_20160219-161840](https://cloud.githubusercontent.com/assets/5979711/13173602/7db8faaa-d724-11e5-88bf-f94ad878ace4.png)

**Comment by rajeshwarpatlolla** [comment]
For now this only supports popup and modal. You can use any one of the two.
