### ISSUE TITLE
cut a new release?

### ISSUE THREAD

**Issue by jtmarmon** [rajeshwarpatlolla/ionic-datepicker#161]
a lot of useful features that i'm reading about and realizing they're not actually available in 0.9.0 (e.g. I didn't know updating `from` doesn't work until recent commits)

**Comment by alphen87** [comment]
yes please release the new helpful features!

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
