### ISSUE TITLE
Feature request: Min and Max Dates

### ISSUE THREAD

**Issue by 3melectronicmonitoring** [rajeshwarpatlolla/ionic-datepicker#162]
Could this be added? I need a date picker to select dates in the past and I need to be able to disable selection of dates that are past the current day.

**Comment by rajeshwarpatlolla** [comment]
Could you please elaborate this. You mentioned you need to be able to select as well as disable the past dates. What exactly you are expecting here?

**Comment by 3melectronicmonitoring** [comment]
Sure, I can elaborate. I need to have a max allowable date property and for my use I would set it to the current day. No dates after today's date could be selected.

**Comment by rajeshwarpatlolla** [comment]
Please check the **from** and **to** properties of the input object. Please take a look at [this link](https://github.com/rajeshwarpatlolla/ionic-datepicker#how-to-use)
Eg :  If `inputDate: new Date()` , then **from** will disable the past dates and **to** will disable to future dates.

**Comment by 3melectronicmonitoring** [comment]
Ok the "to" property does what I need. Thanks!
