### ISSUE TITLE
Installing from Bower do not have the latest version's code

### ISSUE THREAD

**Issue by tlkiong** [rajeshwarpatlolla/ionic-datepicker#166]
I install this component from bower (its v 0.9.0). However, the codes within:

'ionic-datepicker.directive.js' do not contain the latest code. I am not sure about the rest. Would be great if you can update the bower with the latest code.

Thanks :)

**Comment by jackvial** [comment]
+1

**Comment by Vercryger** [comment]
Once the plugin is installed, IT IS NOT READY TO USE IT! I have to go to the plugin folder, run npm install, build the dist folder and only then, we are able to use it, that's wrong!!!
Please, update the bower module with the dist folder included!

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
