### ISSUE TITLE
Question: Is it possible to embed in page without modal or popup?

### ISSUE THREAD

**Issue by skotturi** [rajeshwarpatlolla/ionic-datepicker#167]
Hi, 

I'd like the embed this directive directly into my page view instead of rendering it as a popup or as a modal. Is there an easy way to accomplish this? 

I tried specifying a templateUrl for the directive but couldnt build the bundle file to pull in this change. 

TIA,
Sante

**Comment by rajeshwarpatlolla** [comment]
This is not possible as of now. May be you can customise it to use in that way you mentioned.
