### ISSUE TITLE
Please update tags to reflect latest changes. 

### ISSUE THREAD

**Issue by forest2087** [rajeshwarpatlolla/ionic-datepicker#168]
The last tag 0.9.0 is from 7 months ago.

**Comment by rajeshwarpatlolla** [comment]
Hi @forest2087, i am working on a big change in the next release. I will try to release once i am done with all those changes.

**Comment by forest2087** [comment]
@rajeshwarpatlolla Do you mind if I add a tag now? I want to version lock my app with you current code on master. Thanks.

**Comment by forest2087** [comment]
#169

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
