### ISSUE TITLE
Styling is a bit broken

### ISSUE THREAD

**Issue by madvas** [rajeshwarpatlolla/ionic-datepicker#17]
Default ionic popup window width is too small
![screen shot 2015-06-11 at 08 29 51](https://cloud.githubusercontent.com/assets/3857155/8101113/578a7656-1014-11e5-9aa9-fc36133e4f14.png)

Thanks

**Comment by rajeshwarpatlolla** [comment]
In the next release i am planning to add some CSS classes for you to customize.

**Comment by madvas** [comment]
Sorry, this was my bad. I had some styling issues on my page. But that sounds good anyways, thanks!
