### ISSUE TITLE
Delay showing template after including the date picker

### ISSUE THREAD

**Issue by milen-3web** [rajeshwarpatlolla/ionic-datepicker#171]
I have an Ionic project with a side menu. When I pressed "Add Ad" it shows a template which contains the ionic datepicker but there is delay of 3-4 seconds before showing it up (it's like freezing). When I remove the date picker from template it works well without delay. In my controller I have basic configuration as described in the documentation - nothing custom/spacial. Any ideas why this is happening? Thank you in advance!

```
<ionic-datepicker input-obj="datepickerObject">
     <div class="list list-inset">
            <div class="item item-input disabled">
                   <i class="icon ion-ios-calendar-outline placeholder-icon"></i>
                   <div class="note">&nbsp;Start date</div>
            </div>
     </div>
</ionic-datepicker>
```

![screen shot 2016-03-11 at 1 56 11 pm](https://cloud.githubusercontent.com/assets/7533241/13701519/13f96cee-e791-11e5-896c-4ce62bddbddc.png)

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.

**Comment by milen-3web** [comment]
It works very well. Thank you for the fast fix!
