### ISSUE TITLE
1.0.0 doesn't work

### ISSUE THREAD

**Issue by lmoncany** [rajeshwarpatlolla/ionic-datepicker#173]
Hi Community, 

I'm looking for a solution, i installed 0.9.0 wich worked nice but closeonselect wasn't working.  So after google researches, i decided to install the last version with bower : 1.0.0 and now : datepicker is not working.
Can you help me ?

**Comment by rajeshwarpatlolla** [comment]
Please take a look at the demo and how to use guide. Please follow the exact same steps. It should work for sure.

**Comment by rajeshwarpatlolla** [comment]
Did you tested with the demo code?

**Comment by emps** [comment]
it works but where i can plz change this green color .. looking for a field to assign class name like with ver 0.9

**Comment by rajeshwarpatlolla** [comment]
I have cross checked it and it is working fine. If you still have any issues please do let me know.
