### ISSUE TITLE
disabledDates not refresh

### ISSUE THREAD

**Issue by kicsiKAPA** [rajeshwarpatlolla/ionic-datepicker#174]
Hey!

It's an awesome plugin and thank You! But in the new version has a little bug. When use ionicDatePicker.openDatePicker() function to show another picker with different disabled dates the old disabled date array still remain and just push new elements.

```
function setDisabledDates(mainObj) {
        if (!mainObj.disabledDates || mainObj.disabledDates.length === 0) {
          $scope.disabledDates = [];
        } else {
          /***** I think this could solve the problem start ******/
          $scope.disabledDates = [];
          /***** I think this could solve the problem end ******/
          angular.forEach(mainObj.disabledDates, function (val, key) {
            val = resetHMSM(new Date(val));
            $scope.disabledDates.push(val.getTime());
          });
        }
      }
```

Or You can put this line in function setInitialObj(ipObj) before setDisabledDates call.

Thank You!

**Comment by rajeshwarpatlolla** [comment]
Could you please add a plunker or codepen for your example?

**Comment by kicsiKAPA** [comment]
Yes. Here it is.
[http://codepen.io/MolnarBence/pen/dMvZgE/](http://codepen.io/MolnarBence/pen/dMvZgE/l)

**Comment by rajeshwarpatlolla** [comment]
It's giving me 404 error.

**Comment by kicsiKAPA** [comment]
hmm.. dunno why but in chrome see too. Try test it on firefox or safari. 
[http://codepen.io/MolnarBence/pen/aNJVgX](http://codepen.io/MolnarBence/pen/aNJVgXl)

**Comment by kicsiKAPA** [comment]
Sorry but the is my first codepen example i'm pretty noob with it :)

**Comment by rajeshwarpatlolla** [comment]
Please check the attachment.

![screen shot 2016-03-21 at 12 27 44 pm](https://cloud.githubusercontent.com/assets/9896335/13912182/5de03a28-ef60-11e5-8654-9ffd4f4ffa26.png)

**Comment by kicsiKAPA** [comment]
Ahh i forgot verify my email on codeine maybe that was the problem. i hope now works
[http://codepen.io/MolnarBence/pen/aNJVgX](http://codepen.io/MolnarBence/pen/aNJVgXl)

**Comment by rajeshwarpatlolla** [comment]
Still the same issue.

**Comment by kicsiKAPA** [comment]
can't understand i tested it on different browser without log in. I changed my username ignore uppercase letters. 
[http://codepen.io/molnarbence/pen/dMvZgE](http://codepen.io/molnarbence/pen/dMvZgE)

Here is my profile with only 1 pen. Maybe u can navigate from here
[http://codepen.io/molnarbence/](http://codepen.io/molnarbence/)

Sorry for waisting ur time

**Comment by rajeshwarpatlolla** [comment]
There is some error with this code pen. Please check the screenshot.

![screen shot 2016-03-21 at 12 41 22 pm](https://cloud.githubusercontent.com/assets/9896335/13912361/4011e1e8-ef62-11e5-86ff-ea1586dbaab0.png)

**Comment by kicsiKAPA** [comment]
its only in chrome cos include MIME type. How can i include ur library correctly?

Chrome console error here  (in firefox and safari works fine.)
Refused to execute script from 'https://raw.githubusercontent.com/rajeshwarpatlolla/ionic-datepicker/master/dist/ionic-datepicker.bundle.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by rajeshwarpatlolla** [comment]
Download the file and save it in your local.

**Comment by kicsiKAPA** [comment]
Ok, now works in chrome too

**Comment by rajeshwarpatlolla** [comment]
I can see the issue. I will fix this issue and will make a new release shortly.

**Comment by kicsiKAPA** [comment]
Thank You for Your Time, and sorry about this mess. Next time if i find something i will start with a working CodePen. :)

**Comment by rajeshwarpatlolla** [comment]
That would be the great way to makes things easier for us to debug.

**Comment by rajeshwarpatlolla** [comment]
This has been fixed in v1.1.0

**Comment by kicsiKAPA** [comment]
Thank You!

**Comment by vicky1404** [comment]
How we can disabledDates after getting server response on runtime?
