### ISSUE TITLE
Feature Suggestion : Swipe and transition animations

### ISSUE THREAD

**Issue by KholofeloMoyaba** [rajeshwarpatlolla/ionic-datepicker#177]
Since this is an ionic project, it would be nice to add ionic swiping functionality. To achieve this use `on-swipe-left` and `on-swipe-right`.

I modified the source and added `on-swipe-left="nextMonth()" on-swipe-right="prevMonth()` to the `calendar_grid` div. i.e the div looks like this:

```
<div class="calendar_grid" on-swipe-left="nextMonth()" on-swipe-right="prevMonth()">
//.. calendar stuff
</div>
```

Also, to accompany the swiping adding transition animations would be a huge plus. I haven't done this at this moment otherwise I was gonna post the code.

**Comment by rajeshwarpatlolla** [comment]
Please take a look at [this comment](https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/95#issuecomment-269197643)
