### ISSUE TITLE
setting the labels doesn't work on modals

### ISSUE THREAD

**Issue by Ingokoepp** [rajeshwarpatlolla/ionic-datepicker#179]
Hi,

i figured out that
`
datePickerObj.todayLabel = "test";
datePickerObj.closeLabel = "anotherTest"
`
only works when the TemplateType equals popup.

**Comment by rajeshwarpatlolla** [comment]
Thank you so much for finding and posting the issue @Ingokoepp. I will fix this issue in the next release.

**Comment by douglaszaltron** [comment]
@Ingokoepp https://github.com/rajeshwarpatlolla/ionic-datepicker/pull/176
already solves this problem, and is changing the theme default with the colors of ionic.

**Comment by rajeshwarpatlolla** [comment]
This has been fixed in v1.1.0
