### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by amrigo** [rajeshwarpatlolla/ionic-datepicker#18]
Hi

I am a fan of this component, a feature request would be to enable just the month selection, and hide weekdays and monthdays.

Maybe just with variables called :disableWeekdays and disableMonthDays: maybe just in this way :<ionic-datepicker idate="currentDate" disablepreviousdates="false" disableWeekdays="false" disableMonthDays="false">

**Comment by rajeshwarpatlolla** [comment]
This component is to select the date, month and year. Not just month. You can play with  some validation logic in your controller if the user selects other than month.
