### ISSUE TITLE
Change the month dates are not changed (Changed to FEB)

### ISSUE THREAD

**Issue by ilahir** [rajeshwarpatlolla/ionic-datepicker#180]
If click to open the date picker in modal

Now current month is **Mar** in date picker, if you can change the month exactly **Feb** below dates are not changed, (**First time**)

After that you change any month working properly

**Comment by rajeshwarpatlolla** [comment]
This has been fixed in v1.1.0

**Comment by ilahir** [comment]
Than you , your support
