### ISSUE TITLE
Problem in Android 4.1

### ISSUE THREAD

**Issue by ThiagoSPereira** [rajeshwarpatlolla/ionic-datepicker#181]
I tested on a tablet and a phone, both Android 4.1 had the same problem.

What to do?

![datapicker](https://cloud.githubusercontent.com/assets/17937925/14214385/273164d2-f813-11e5-9fec-efbd0460d758.jpg)

**Comment by ThiagoSPereira** [comment]
When used a 6.0. I had no problems

**Comment by rajeshwarpatlolla** [comment]
This supports at it's best from android 4.4 i.e. kitkat version of OS.
