### ISSUE TITLE
Set selected date in datepicker

### ISSUE THREAD

**Issue by ilahir** [rajeshwarpatlolla/ionic-datepicker#182]
Hi,

How do** set given date is selected**  in date picker(Define manual date)

**Comment by renekorss** [comment]
If I understand you correctly, then use `inputDate`. For example `inputDate: new Date(2016, 4, 20)` would select 20th April 2016 by default.

**Comment by ilahir** [comment]
For example inputDate: new Date(2016, 4, 20) working correctly,

Thank u for support
