### ISSUE TITLE
[$injector:nomod] Error

### ISSUE THREAD

**Issue by ElaHo** [rajeshwarpatlolla/ionic-datepicker#183]
Hi there,

thank you for development.
I found an error

`[$injector:nomod] Module 'ionic-datepicker.templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod`

probably ionic-datepicker.templates was there before and you forgot to remove it completely?

I see it's commented out in src/ionic-datepicker.module.js
but there are lots of references in dist/ionic-datepicker.bundle.min.js

Thankyou so much

**Comment by rajeshwarpatlolla** [comment]
The `dist` is completely different from the `src`. If you want to make dist with the new changes, then you can uncomment and build the dist folder. Once you are done, then you can comment it, as this is not needed in the src folder.
