### ISSUE TITLE
Modal issue with year selection

### ISSUE THREAD

**Issue by DawidMyslak** [rajeshwarpatlolla/ionic-datepicker#188]
This issue appears only in modal view.

Steps to reproduce:
1. Open http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/ (I'm using Chrome)
2. Click "Open Date Picker Modal"
3. Click "Set"
4. Click "Open Date Picker Modal" again
5. Change year to 2015, do not select any day from calendar, press "Set"
6. Click "Open Date Picker Modal" again
7. Try to change year to 2015 again, calendar will stay in the same place as it is instead of moving to proper month in 2015.

**Comment by DawidMyslak** [comment]
I was also trying to apply some changes to the source code and I run `gulp build`. After this I'm getting the error that modal template file (html) can not be loaded (404). Is there anything I have to change in the source code before I run gulp build command?

**Comment by DawidMyslak** [comment]
Basically

**Comment by KixS** [comment]
I got the same issue.
In the .min file look for
`["ionic", "ionic-datepicker.service", "ionic-datepicker.provider"]`
and replace it by:
`["ionic", "ionic-datepicker.service", "ionic-datepicker.provider", "ionic-datepicker.templates"]`

**Comment by rajeshwarpatlolla** [comment]
Hi @DawidMyslak, to address your first issue. Even you change the date for the first time, the object you are passing to `ionicDatePicker.openDatePicker(<object>)` is not changing. If you change that in your controller, then it will work.

When you run the gulp task you have to un comment the line number 5 in `ionic-datepicker.module.js` and once you build it you can un comment it. But if you wish to use the source files, then you have to comment this line, and then you can use the files from the src folder.

**Comment by DawidMyslak** [comment]
@KixS, @rajeshwarpatlolla Thanks!

**Comment by DawidMyslak** [comment]
@rajeshwarpatlolla According to my first issue, I was trying to change date picker object in my controller and pass a new version of it each time, but I still have the same issue. Could you try to give me any hint how to solve it? I can't reproduce this issue in popup view, it's happening only in modal, which is bit strange.
