### ISSUE TITLE
Feature request - "sticky" date

### ISSUE THREAD

**Issue by finster** [rajeshwarpatlolla/ionic-datepicker#190]
A couple of my users have been confused when trying to select a date. They first select a date, then change the month or year, expecting the days to remain the same.

For example, they select 11-Apr-16 then change the month to June, expecting the selected date to be 11-Jun-16. They then close the datepicker but haven't selected the date they thought they had.

This is repeatable on the demo page.

Is it possible to have an option for a "sticky" date?

I think that this is related to issue #88 

Thanks.

**Comment by rajeshwarpatlolla** [comment]
We are already showing the selected date in the header to avoid such confusion.
