### ISSUE TITLE
IOS 9.3, not showing picker 

### ISSUE THREAD

**Issue by fabuhelow** [rajeshwarpatlolla/ionic-datepicker#192]
Hi,

I have added ionic-datepicker and ionic-timepicker to my project

The timepicker component is working perfectly, but the datepicker does not work yet !! any help?

Code: "home.html"

<div ng-click="openDatePicker()" class="item item-icon-right ng-pristine ng-untouched ng-valid">
                <i class="icon ion-ios-calendar-outline positive"></i>
                Order Date: <b>{{datepickerObject | date:'dd - MMMM - yyyy'}}</b>

</div>

Code: "homeController":

$scope.datepickerObject;    
     var ipObj1 = {
      callback: function (val) {  //Mandatory
        
        if (typeof(val) === 'undefined') 
        {
            $scope.disabledContinueDateButton = true;
        } 
        else {
            console.log('Return value from the datepicker popup is : ' + val, new Date(val));

            $scope.datepickerObject = val;
            $scope.disabledContinueDateButton  = false;
        }
        
      },
      disabledDates: new Date(),
      from: date, //Optional
      to: nextYear, //Optional
      inputDate: new Date(),      //Optional
      mondayFirst: true,          //Optional
      disableWeekdays: [0],       //Optional
      closeOnSelect: true,       //Optional
      templateType: 'popup',       //Optional
      dateFormat: 'dd-MM-yyyy'
    };

    $scope.openDatePicker = function(){
      ionicDatePicker.openDatePicker(ipObj1);
    };

**Comment by rajeshwarpatlolla** [comment]
Please check the demo link in iOS 9.3, it is working fine.
And in your case are you getting any errors on the console?

**Comment by fabuhelow** [comment]
I have checked the demo from my phone browser "Safari" and it does not work, and i didn't got any error in console.

Anyhelp about this problem @rajeshwarpatlolla  ?

**Comment by rajeshwarpatlolla** [comment]
![image](https://cloud.githubusercontent.com/assets/9896335/14569727/133716ce-035e-11e6-8233-5723bc484f53.png)
![image](https://cloud.githubusercontent.com/assets/9896335/14569728/133c0206-035e-11e6-8bb5-21d44532a0c2.png)

**Comment by fabuhelow** [comment]
I have checked it from my both browsers "chrome & Safari", but still it does not work.
![thumb_img_1781_1024](https://cloud.githubusercontent.com/assets/6513214/14569910/3e45f79a-034a-11e6-9659-000c94ae59e1.jpg)
![thumb_img_1782_1024](https://cloud.githubusercontent.com/assets/6513214/14569905/3e43af3a-034a-11e6-8e93-60cf2abca5d3.jpg)
![thumb_img_1783_1024](https://cloud.githubusercontent.com/assets/6513214/14569906/3e45039e-034a-11e6-92ce-df5ba98b13f7.jpg)
![thumb_img_1784_1024](https://cloud.githubusercontent.com/assets/6513214/14569907/3e450eb6-034a-11e6-8d0b-924022610703.jpg)
![thumb_img_1785_1024](https://cloud.githubusercontent.com/assets/6513214/14569908/3e457360-034a-11e6-990d-e632437839f6.jpg)
![thumb_img_1786_1024](https://cloud.githubusercontent.com/assets/6513214/14569909/3e45e0a2-034a-11e6-8e19-862725c5776f.jpg)
![thumb_img_1787_1024](https://cloud.githubusercontent.com/assets/6513214/14569911/3e66dabe-034a-11e6-9666-e3342ee2c03d.jpg)

**Comment by rajeshwarpatlolla** [comment]
No one has raised this issue so far. Check it in PC browser.

**Comment by fabuhelow** [comment]
It works fine in my PC browser and same thing working fine on my android device, but still i don't know why it does not work on IOS 9.3.1, IPhone 6 :(

**Comment by rajeshwarpatlolla** [comment]
I also tested in version 9.3.1 only. It was working fine for me., as i shown in the above screenshots.

**Comment by fabuhelow** [comment]
Hi @rajeshwarpatlolla , i have enabled safari web inspector and i have got an error in my console tab.

So.. this is why the datepicker does not work fine.

Please check attached image "Error":

![screen shot 2016-04-16 at 1 00 54 pm](https://cloud.githubusercontent.com/assets/6513214/14580315/97a08c96-03d2-11e6-8ac0-7372e0153419.png)

![screen shot 2016-04-16 at 1 03 26 pm](https://cloud.githubusercontent.com/assets/6513214/14580323/bb0543d4-03d2-11e6-8d77-5f5e2b9900a4.png)

Could you please help me to fix this issue ?

Thanks,

**Comment by rajeshwarpatlolla** [comment]
Could you please try with the files in src folder and see what's the exact error?

**Comment by fabuhelow** [comment]
I have access your online demo, so it's not possible to me to edit your files.

Could you please push a new demo "new demo url" with src directory and i will check it and let you know the exact issue.

**Comment by fabuhelow** [comment]
![screen shot 2016-04-16 at 1 27 32 pm](https://cloud.githubusercontent.com/assets/6513214/14580455/1bd5910c-03d6-11e6-86cd-d5a8e193736a.png)

It may this screenshot will help you @rajeshwarpatlolla  :)

**Comment by fabuhelow** [comment]
@rajeshwarpatlolla Any update ?

**Comment by rajeshwarpatlolla** [comment]
Unable to reproduce this issue in the same version of OS.

**Comment by karandpr** [comment]
Hey there, 
I was facing the same issue. Turns out it's not an issue with the plugin but with Date function in iOS.
This format wont work in iOS "yyyy-mm-dd HH:mm:ss".
inputDate , to and from fields parse use date object. 
Passing undefined value in inputDate threw that error for me.
It works fine , once correct date value is passed.

**Comment by KalaniParapitiya** [comment]
ionic datetimepicker not works for me in ios mobile app.
