### ISSUE TITLE
Please support other language in title when set monthList

### ISSUE THREAD

**Issue by zMADCATz** [rajeshwarpatlolla/ionic-datepicker#193]
![screen shot 2016-04-19 at 10 27 19](https://cloud.githubusercontent.com/assets/9088059/14626873/8b0d3c92-0619-11e6-9db8-c8231db74342.png)

in title it could be 1 一月 2016

**Comment by MartinZid** [comment]
+1

**Comment by elewin** [comment]
What would be great is if instead of specifying a MM/DD/YYYY format directly, we could instead apply a function to the date that would do this formatting for us for those using something like moment.js for example

**Comment by mvidailhet** [comment]
This would be a really great feature !

**Comment by rajeshwarpatlolla** [comment]
Thanks for adding the solution @mvidailhet

**Comment by rajeshwarpatlolla** [comment]
You can pass the translated text to the input object to the component, in order to see the translated text.
