### ISSUE TITLE
Clear button

### ISSUE THREAD

**Issue by krusk8** [rajeshwarpatlolla/ionic-datepicker#194]
It's impossible to clear input. You may select at least one date to close calendar. Can you please let me know if there is a way to do it? Thank you

**Comment by rajeshwarpatlolla** [comment]
There is no feature for clearing the input. But you can close the datepicker, without selecting any date, by clicking on the close button.

**Comment by krusk8** [comment]
Thank you for reply, but my problem is when you have a date selected and you want to remove it. If you reopen datepicker you can't clear the input selected before. In Chrome I can see a css button ''X for remove input but the model dosen't update value. Bye
