### ISSUE TITLE
Doens't show year in datepicker

### ISSUE THREAD

**Issue by thedoorbell** [rajeshwarpatlolla/ionic-datepicker#197]
![image](https://cloud.githubusercontent.com/assets/18674216/14821416/579bcb02-0bd3-11e6-8ba8-12426ed5df5f.png)

There is code:
```
var ipObj1 = {
        callback: function (val) {  //Mandatory
        },
        from: new Date(1950, 0, 1),
        to: new Date(2009, 0, 1),
        inputDate: new Date(1957, 2, 15), 
        setLabel: 'Выбрать',
        closeLabel: 'Отмена',
        mondayFirst: true,
        dateFormat: 'yyyy-MM-dd',
        closeOnSelect: false,
        templateType: 'popup' 
    };

    $scope.openDatePicker = function(){
        ionicDatePicker.openDatePicker(ipObj1);
    };
```

As you see at screenshot, inputDate is ok, but if month and day are selected, year is not. There is no any error. Can you help me?

**Comment by yaoyonstudio** [comment]
![datepicker](https://cloud.githubusercontent.com/assets/13121726/14906410/a81824a6-0ded-11e6-9d90-1c0f3a7789a8.jpg)

I have the same issue.
need help. Thanks very much.

**Comment by Manduro** [comment]
Same issue for me.

**Comment by rajeshwarpatlolla** [comment]
Can anyone make a codepen and paste the link here?

**Comment by yaoyonstudio** [comment]
`//日期选择
    function getLocalTime(nS) {
      return new Date(parseInt(nS)).toLocaleString().replace(/年|月/g, "-").replace(/日/g, " ");
    }
    //alert(getLocalTime(1177824835));

    var ipObj1 = {
      callback: function (val) {  //Mandatory
        console.log('Return value from the datepicker popup is : ' + val, new Date(val));
        $scope.selectedDate = val;
        console.log(getLocalTime($scope.selectedDate));
      },
      from: new Date(2016, 1, 1), //Optional
      to: new Date(2030, 12, 31), //Optional
      inputDate: new Date(),      //Optional
      mondayFirst: true,          //Optional
      closeOnSelect: false,       //Optional
      templateType: 'popup'       //Optional
    };

    $scope.openDatePicker = function(){
      ionicDatePicker.openDatePicker(ipObj1);
    };`

Hello,This is my code, I can open the date picker, but it can't display the year .

**Comment by rajeshwarpatlolla** [comment]
Please take a look at the demo page. It will show correctly. And also please double check the properties `from` and `to`, which should have the current year in the range or it should be in the range of `inputDate`.

**Comment by Manduro** [comment]
This is still an issue. Even with correct from and to within the range. I'm trying to figure out why it does work in your demo, but I can't trace it.

**Comment by thedoorbell** [comment]
You should't close the issue. Demo works correct because its based on older version of Ionic, where used an older version of angular.
After I updated for Ionic 1.3 - year doesn't show correctly. And I guess you just need to change and unpdate some things in plugin... Try to test at Ionic 1.3.
Still waiting for solution :) Thanks.

**Comment by yaoyonstudio** [comment]
@rajeshwarpatlolla 

The problem seems only show on the new ionic version .
