### ISSUE TITLE
Ionic 1.3 issue

### ISSUE THREAD

**Issue by DawidMyslak** [rajeshwarpatlolla/ionic-datepicker#199]
After updating to Ionic 1.3 (http://blog.ionic.io/announcing-ionic-1-3/) calendar is not working properly in popup mode (year drop-down is not populated with year from inputDate param). They have also updated Angular to version 1.5 so I'm guessing it's more Angular problem.

**Comment by Zozos** [comment]
+1

**Comment by dvlasenko96** [comment]
+1

**Comment by fonini** [comment]
+1

**Comment by rajeshwarpatlolla** [comment]
I have updated the ionic version to 1.3.0, but there is no issue. Please check the [demo page](http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/home). And also have a look at the attached image.
![screen shot 2016-05-09 at 5 02 12 pm](https://cloud.githubusercontent.com/assets/9896335/15112091/81ca2bcc-1609-11e6-9d9a-fb9e323cb1ae.png)
