### ISSUE TITLE
year in select option has empty option

### ISSUE THREAD

**Issue by zMADCATz** [rajeshwarpatlolla/ionic-datepicker#200]
![screen shot 2016-05-04 at 14 48 59](https://cloud.githubusercontent.com/assets/9088059/15008001/2ff16c94-1207-11e6-95e5-1b095291851d.png)

when openDatePicker first time
it has empty option on first year

found in [demo](http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/home)

**Comment by rajeshwarpatlolla** [comment]
It is working fine in the demo page. Please cross check again.

**Comment by zMADCATz** [comment]
![screenshot_8](https://cloud.githubusercontent.com/assets/9088059/15112640/af713bbe-1619-11e6-808b-2908cd321511.png)

on Google Chrome 
Version 50.0.2661.94 m

**Comment by DaniloPolani** [comment]
Same here. I just ran bower to install it and I'm using an input with ng-click to show the popup/modal where ( with ng-model ) I set its default date.

With or without config, modal or popup, the current year in the select is not selected.

**Comment by DaniloPolani** [comment]
@zMADCATz @rajeshwarpatlolla please check this out: https://gist.github.com/DaniloPolani/d6b019784f63812b0d26507315374642

I fixed it simply replacing `<option ng-repeat>` with `<select ng-options="year for year in yearsList">` also for months. It works to me.

Please update the repo.

**Comment by zMADCATz** [comment]
it seem has been fix on https://github.com/rajeshwarpatlolla/ionic-datepicker/commit/6b748ab1920db41d72371ed92b4edf2a83648484

waiting for new release

**Comment by mmillet** [comment]
+1

**Comment by DaniloPolani** [comment]
@mmillet have you tried my gist?

**Comment by mmillet** [comment]
@DaniloPolani I tried 6b748ab and it works.

**Comment by djoufouf007** [comment]
for me this link does not work ,
https://github.com/rajeshwarpatlolla/ionic-datepicker/commit/6b748ab1920db41d72371ed92b4edf2a83648484 

i donwloaded the lasted version and i have this one in the ionic-datepicker-provider.js

` $scope.data.currentMonth = $scope.mainObj.monthsList[currentDate.getMonth()];
        $scope.data.currentYear = currentDate.getFullYear()
        $scope.data.currentMonthSelected = angular.copy($scope.data.currentMonth);
        $scope.currentYearSelected = angular.copy($scope.data.currentYear);
        $scope.numColumns = 7;`

even if i put like this 

 `$scope.data.currentYear = currentDate.getFullYear().toString()`

i have the same issue , the field year stay no selected when i open 

solution ?

thanks
