### ISSUE TITLE
Add npm package

### ISSUE THREAD

**Issue by jgerstle** [rajeshwarpatlolla/ionic-datepicker#201]
There seems to already be support for npm install using a path: [pr 191](https://github.com/rajeshwarpatlolla/ionic-datepicker/pull/191), but can you add an actual package in npm

**Comment by rajeshwarpatlolla** [comment]
Please check [this link](https://www.npmjs.com/package/ionic-datepicker)

**Comment by sandorfr** [comment]
@rajeshwarpatlolla is there any chance you can update the npm package with the latest version anytime soon?
