### ISSUE TITLE
Disabled date can select.

### ISSUE THREAD

**Issue by go2hyder** [rajeshwarpatlolla/ionic-datepicker#206]
First of all thank you for this amazing date picker.I have an issue.
I already disabled all Fridays. And my 'inputDate' is today's date.But I can select Friday if today is Friday..How I can fix that?

**Comment by rajeshwarpatlolla** [comment]
In which device you are testing?

**Comment by louisdoe** [comment]
Is it possible to not show in the year list, all the years that are excluded by the "from" and "to" options ?

Example:

if I use : 

    ```
from: new Date("01-01-1936"), //Optional
              to: new Date(2016, 8, 25),  //O
```

I would like the list not to display the years before 1936.

Is that possible ?

Thanks !

**Comment by rajeshwarpatlolla** [comment]
Yes, it works. I think you already gave that `from` and `to`, which should work fine.

**Comment by louisdoe** [comment]
No I still see the years from 1900 to 2100 in the list !

**Comment by rajeshwarpatlolla** [comment]
In [demo](http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/home) it's working fine. Can you cross check once again?

**Comment by int21ve** [comment]
Halo
I'm having the same issues like @go2hyder commented
