### ISSUE TITLE
Feature: MomentJS Integration

### ISSUE THREAD

**Issue by mtpultz** [rajeshwarpatlolla/ionic-datepicker#209]
Would it be worth integrating the date picker to use momentjs so the dates returned and passed in are moment objects.

**Comment by Arxi** [comment]
I use MomentJS too, but since it's easy to manually convert the input and return dates from and to moment objects, wouldn't this add an unnecessary dependency for this plugin?

**Comment by mtpultz** [comment]
Hey @Arxi, yah that's a good point.
