### ISSUE TITLE
Error setting date from timestamp

### ISSUE THREAD

**Issue by rafaelbecks** [rajeshwarpatlolla/ionic-datepicker#21]
Hi, your date picker had been very useful to my development, but I have a little issue.

I set the value of the datepicker from a timestamp that i get from a service. The datepicker set the date, but when I want to change the model value I get this on javascript console:

     e.setHours is not a function

This is my code

     var mydate=$scope.orden.fecha_tope; // formated 2012-02-02
     $scope.orden.currentDate=Date.parse(mydate.replace(/-/g,"/")); //Update the model of the datepicker

**Template:**

            <ionic-datepicker idate="orden.currentDate" disablepreviousdates="true"  callback="datePickerCallback">
             <button class="button button-block button-positive" type="button"> {{ orden.currentDate | date:'dd - MMMM - yyyy' }} </button>
               </ionic-datepicker>

What can I do to fix this?

Thanks a lot!

**Comment by pinoyyid** [comment]
I'm seeing the same thing. Otherwise I'm loving the library.

**Comment by rajeshwarpatlolla** [comment]
Are you defining the callback in the respected controller?

**Comment by rafaelbecks** [comment]
Yes.  I don't have problem when I want to send the date, that's ok, I can handle the value. The problem is when I want to set a previous value that I get from a service and I want to change it.. The datepicker is set but I can't change the value, the modal window doesn't show. Sorry my english btw.

This is my callback in the edit controller

           $scope.datePickerCallback = function (val) {
                if(typeof(val)==='undefined'){      
                     console.log('Date not selected');
                }else{
            zeroMonth=""; zeroDay="";
            if((val.getMonth())<10) zeroMonth="0";
            if((val.getDate()+1)<10) zeroDay="0";
           $scope.orden.fecha_tope=val.getFullYear()+"-"+zeroMonth+(val.getMonth()+1)+"-"+zeroDay+(val.getDate());
         }
};

**Comment by rajeshwarpatlolla** [comment]
There could be a little chance to get this error while you are getting the date from some service. Could you please check the value, may be by logging it to console before passing to the date picker?

**Comment by rafaelbecks** [comment]
I get the date in this format from service

              2015-06-10

Then I parse the date string to a date javascript object (timestamp)

              $scope.orden.currentDate=Date.parse(mystringdate.replace(/-/g,"/"));
              1433910600000 (this is what I set to the datepicker)

**Comment by rajeshwarpatlolla** [comment]
In your controller make a Date object with the epoch you have like `$scope.orden.currentDate = new Date(<your epoch time>)`, and then pass this in the template.

**Comment by rafaelbecks** [comment]
That was the solution, now is working.. thanks a lot!
