### ISSUE TITLE
Date picker UI issue

### ISSUE THREAD

**Issue by mjibril** [rajeshwarpatlolla/ionic-datepicker#211]
![screen shot 2016-05-18 at 21 09 54](https://cloud.githubusercontent.com/assets/6002285/15373364/2647a406-1d3d-11e6-9b21-dfe7bc759067.png)

Set -Today-Close buttons seem to have misplaced alignment.

**Comment by DaniloPolani** [comment]
I had the same problem. Solved with this:

```
ion-modal-view.ionic_datepicker_modal ion-footer-bar .button {
  width: inherit;
  max-width: none;
}
```

**Comment by rajeshwarpatlolla** [comment]
Thanks for adding the solution @DaniloPolani
