### ISSUE TITLE
Converting this awesome Date picker to Persian calendar 

### ISSUE THREAD

**Issue by amirtutunchi** [rajeshwarpatlolla/ionic-datepicker#214]
Hello every one 
this datepicker is awesome and i love it .but now days  i want to use it as a date picker of persian calendar . for those who may not know what is persian calendar i will put a wikipedia link to understand how it works.[Persian Calendar-Wiki](https://en.wikipedia.org/wiki/Iranian_calendars)
its very useful calendar and over  200 million people use it especially in Iran , Afghanistan ,India , Pakistan , .... and it has some fixed rules and more depend on solar system.the major problem here is to change the logic of datepicker from Georgian to Pesrian.  hope you guys help me and middle east people also can use this awesome datepicker thanks a lot.

**Comment by amirtutunchi** [comment]
i have convert it my self
if any one intrested go to this [link](https://github.com/Loopersgroup/PersianIonicDatepicker)

**Comment by hjn66** [comment]
> i have convert it my self
> if any one intrested go to this [link](https://github.com/Loopersgroup/PersianIonicDatepicker)

Please tell us how to use your module in ionic project, your repository has not any documentation

**Comment by mostafa8026** [comment]
Hey, Could you please add more details to your project?
