### ISSUE TITLE
Year not selected

### ISSUE THREAD

**Issue by amilino** [rajeshwarpatlolla/ionic-datepicker#215]
Year not preselected on opening datepicker in new version 1.1.0.

**Comment by chanondb** [comment]
Got same problem, but just figure it out. In ionic-datepicker-popup.html, ionic-datepicker-modal.html change select year from :
`<select ng-model="currentYear" ng-change="yearChanged(currentYear)">
              <option ng-repeat="year in yearsList" ng-selected="year==currentYearSelected" value="{{year}}">
                {{year}}
              </option>
            </select>`
to be :
 `<select ng-model="currentYear" ng-options="year for year in yearsList track by year" ng-change="yearChanged(currentYear)"></select>`

**Comment by amilino** [comment]
Doesn't work for me.

**Comment by amilino** [comment]
I'll have to switch to some other datepicker.

**Comment by amilino** [comment]
I tried to delete both files:
ionic-datepicker-popup.html
ionic-datepicker-modal.html 

And datepicker is still working. Don't understand.

**Comment by amilino** [comment]
Is it possible to add template-url and customize html, because currently it is bundled in js file.

**Comment by chanondb** [comment]
ahh ok, just a guess but in your index.html it's pointing to bundle file
: ionic-datepicker.bundle.min.js
First, I'm new for how to make bundle file, so I just fix those <select>
code in ionic-datepicker.bundle.min.js, and forget that part :p

You can try to search in ionic-datepicker.bundle.min.js with keyword :
<select ng-model=currentYear

You should find 2 of them, which u can just replace with code below and try
to clean project and build again

<select ng-model=currentYear ng-options="year for year in yearsList track
by year" ng-change=yearChanged(currentYear)></select>

On Fri, May 27, 2016 at 2:06 PM, Alan <notifications@github.com> wrote:

> I tried to delete both files:
> ionic-datepicker-popup.html
> ionic-datepicker-modal.html
>
> And datepicker is still working. Don't understand.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/215#issuecomment-222075485>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALcz8b8o2QDQ-vjprAaJ12wUUAo7XqDMks5qFpfsgaJpZM4IlJIf>
> .
>



-- 
Regards,

Chanond Buranabunpot (Tai)(ต่าย) | *Business Technology Consultant @ App
Alive*
524/2 Soi Matanusorn, Mahaisawan Rd, Bangkorlaem, Bangkok 10120

Mobile : +(66)9-9352-9096
email : chanond.b@app-alive.com

**Comment by amilino** [comment]
Yes, I just did and now it's working. But It would be nice if that can be fixed in next release. :)

Tnx for help.

**Comment by chanondb** [comment]
Your welcome, well for the release gotta wait for @rajeshwarpatlolla to fix it again. I'm also just a user too :D

**Comment by amilino** [comment]
I know. :D

**Comment by amilino** [comment]
@rajeshwarpatlolla it's also very hard to move through months with "<" and ">" icons. Because ng-click event is added on that small button icon. I would put click event on parent (div) element.

Hope @rajeshwarpatlolla is reading this. :P

**Comment by peterwong0613** [comment]
+1

**Comment by theroymind** [comment]
+1

**Comment by amilino** [comment]
Rajesh, where are you? :)

**Comment by olegwn** [comment]
yep +1

**Comment by cklaffer** [comment]
+1

**Comment by amilino** [comment]
Hi @rajeshwarpatlolla,

to be proactive, I created a pull request for this issue. Please merge it with the master branch and compile bundle.min.js file.

Thank you in advance.

Regards,
Alan

**Comment by amilino** [comment]
This is already fixed on master branch. So I removed pull request and added new one just for moving ng-click events on parent div, because they where hard to trigger due to smallness of ">" and "<" buttons.

**Comment by arturokunder** [comment]
@amilino Your change moving ng-click events  broke pointer_event_none in those buttons. Now the button accepts clicks even when the date is before/after fromDate/toDate
It's fixed in my branch. I'll make PR as soon as I test all the cases

**Comment by amilino** [comment]
@arturokunder I don't have any problems with my change. However, lookong forward to your PR.

**Comment by arturokunder** [comment]
At modal.html, you had this:

```js
  <ion-content class="ionic_datepicker_modal_content">
    <div class="">
      <div class="row text-center">
        <div class="col col-10 left_arrow" ng-click="prevMonth()">
          <button class="button-clear font_22px" ng-class="{'pointer_events_none':((firstDayEpoch - 86400000) < fromDate)}">
```

when the condition `firstDayEpoch - 86400000) < fromDate` is true, `pointer_events_none` class is added by ng-class`

**Comment by arturokunder** [comment]
At modal.html, you had this:

```html
  <ion-content class="ionic_datepicker_modal_content">
    <div class="">
      <div class="row text-center">
        <div class="col col-10 left_arrow" ng-click="prevMonth()">
          <button class="button-clear font_22px" ng-class="{'pointer_events_none':((firstDayEpoch - 86400000) < fromDate)}">
```

when the condition `firstDayEpoch - 86400000) < fromDate` is true, `pointer_events_none` class is added by `ng-class`

`pointer_events_none` disables all clicks on the button but the tag that has the event is the parent div so it's never disabled and the event is fired anyway, allowing the user to go back (or forward) months that should not be in the calendar

The solution is to repeat the condition at the parent element

```html
  <ion-content class="ionic_datepicker_modal_content">
    <div class="">
      <div class="row text-center">
        <div class="col col-10 left_arrow" ng-click="prevMonth()" ng-class="{'pointer_events_none':((firstDayEpoch - 86400000) < fromDate)}">
          <button class="button-clear font_22px" ng-class="{'pointer_events_none':((firstDayEpoch - 86400000) < fromDate)}">
```

I already opened PR #233 which solves this issue and adds a new feature.

**Comment by amilino** [comment]
@arturokunder Very nice, thank you for your explanation.
