### ISSUE TITLE
before open ionic-datepicker model , another  $ionicModal.fromTemplateUrl has been open . sometimes ionic-datepicker model can't   In front of the phone screen

### ISSUE THREAD

**Issue by tongyigang** [rajeshwarpatlolla/ionic-datepicker#216]
before open ionic-datepicker model , another  $ionicModal.fromTemplateUrl has been opened . sometimes ionic-datepicker model can't   In front of the phone screen.. U must close the other model to see ionic-datepicker model.. Please fix this bug . Thank u very much .. I am Chinees. My English is very poor . Please forgive me ^_^..

**Comment by rajeshwarpatlolla** [comment]
This is not reproducible.
