### ISSUE TITLE
Default value for disableWeekdays option

### ISSUE THREAD

**Issue by maniolek** [rajeshwarpatlolla/ionic-datepicker#218]
Hi guys,
Is a 6th day (Saturday) of the week is set as disabled by default? I'm using only the mandatory options, like callback and templateType. Although I didn't set disableWeekdays, or when I set this on an empty array, Saturday is always disabled. 

any help?

**Comment by rajeshwarpatlolla** [comment]
No, the weekday is not disabled by default.

**Comment by vivek9593** [comment]
Is a 6th day (Saturday) of the week is set as disabled by default? I'm using only the mandatory options, like callback and templateType. Although I didn't set disableWeekdays, or when I set this on an empty array, Saturday is always disabled.


My code is 

var ipObj1 = {
            callback: function (val) {  //Mandatory
                console.log('Return value from the datepicker modal is : ' + val, new Date(val));
                $scope.selectedDate1 = moment(val).format('DD MMM YYYY');
            },
            from: moment(),
            to: moment().add(2,'years'),
            showTodayButton: false,
            closeOnSelect: false,
            templateType: 'modal'
        };
        ionicDatePicker.openDatePicker(ipObj1);

![calender](https://cloud.githubusercontent.com/assets/12856243/17676068/49c766e8-634a-11e6-8387-ae8113860437.PNG)

**Comment by rajeshwarpatlolla** [comment]
Check your config method. You might have added the `disableWeekdays` as i mentioned in the documentation. That is just for demonstration purpose. Please check the demo also.
