### ISSUE TITLE
IE next/previous buttons fire twice

### ISSUE THREAD

**Issue by mboegem** [rajeshwarpatlolla/ionic-datepicker#219]
When navigating through different months (prevMonth/nextMonth) the arrows will fire the function twice.
This is because of the <div> containing the ng-click will fire the click event, and the <button> inside it will fire the pointer event on the same function.

It's obvious that the double execution will cause navigation to increase/decrease months in steps of 2 months.

**Comment by rajeshwarpatlolla** [comment]
Can you propose a fix with a PR for this if you can spend some time?

**Comment by rajeshwarpatlolla** [comment]
Please take a look at the latest version [v1.2.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.2.0)
