### ISSUE TITLE
opposite of "disablepreviousdates"

### ISSUE THREAD

**Issue by dayaki** [rajeshwarpatlolla/ionic-datepicker#22]
Implement a opposite of "disablepreviousdates" for future dates, say "disablefuturedates" to disable future dates, useful for date of birth scenarios.

**Comment by rajeshwarpatlolla** [comment]
I will try to implement this feature in the next release. Thanks for the suggestion.

**Comment by dayaki** [comment]
Thanks for the awesome work.

**Comment by loiseau-elegante** [comment]
In addition to this, can you enable a feature that will only allow a certain period of dates? For instance, 7 days from the current date, with everything else grayed out?

**Comment by rajeshwarpatlolla** [comment]
This feature is implemented in the latest version v0.4.0.
