### ISSUE TITLE
Bug with TODAY button

### ISSUE THREAD

**Issue by gartorware** [rajeshwarpatlolla/ionic-datepicker#220]
Hi,

I think I found a bug. Callback function is not fired when today button (showTodayButton:true) is pressed. This is a problem when you have closeOnSelect:true, since popup is closed when you press today button without any callback. If instead of today button you select today date (I mean, click on today number date) callback is indeed fire.

Regards.

**Comment by niccord** [comment]
Same here.
Unless you already did it, I will try to fix this in the next days.

**Comment by mariokreeft** [comment]
Hi, 

Did you already have the time to fix it? 
Would be helpfull.

Thanks

**Comment by niccord** [comment]
This is src/ionic-datepicker.provider.js file with my fix.
Hope it will be helpful.

[ionic-datepicker.provider.zip](https://github.com/rajeshwarpatlolla/ionic-datepicker/files/612296/ionic-datepicker.provider.zip)

**Comment by mariokreeft** [comment]
Thank you a lot!!

**Comment by chiragandroid** [comment]
Not working for me. after updating provider.js. i am using older version of this plugin #1.1.0

**Comment by rajeshwarpatlolla** [comment]
Fixed with [282](https://github.com/rajeshwarpatlolla/ionic-datepicker/pull/282) PR
