### ISSUE TITLE
Allow to specify location of buttons

### ISSUE THREAD

**Issue by philonor** [rajeshwarpatlolla/ionic-datepicker#221]
Depending on platform, RTL or LTR script and app design guidelines, it might be necessary to switch the locations of `button_set` and `button_close`.

**Possible solution:**
- Create `$scope.buttons` object for modal
```
{
  left: {.., isVisible: true}, // left button
  center: {.., isVisible: ..}, // center button
  right: {.., isVisible, ..} // right button
}
```
- In `ionic-datepicker-modal.html`, change
  - `ng-if`s to `buttons.left.isVisible` etc.
  - `ng-click`s to a `button.onTap`
- Change `button.onTap` functions to check whether rendered as modal; if yes, call `closeModal()`
- New config option `buttonLayout` which allows option, e.g. `swapped`

**Comment by cklaffer** [comment]
Please make an option in the config object to switch close and set button positions. I find it much more intuitive to have the set button on the right hand side. Especially in the popup. Thx! :-)

**Comment by rajeshwarpatlolla** [comment]
As of now you can only specify the color of the buttons.
