### ISSUE TITLE
ionic-datepicker: Disable dates are clickable in windowsPhone8 

### ISSUE THREAD

**Issue by kamakshi417** [rajeshwarpatlolla/ionic-datepicker#222]
Hi, 
I'm using this js in android,ios and windows for selecting date ,Disable dates are working fine in android and ios , buts in windows disable dates are still able to select . 

can you please help me on this . 
if possible please provide  unminified   js version

**Comment by rajeshwarpatlolla** [comment]
There must be some issue with pointer events css.
For those dates which are disabled i am applying `pointer_events_none` css class which has css as below.

````css
pointer-events: none;
color: #aaaaaa !important;
````
[This link](http://stackoverflow.com/questions/17441810/pointer-events-none-does-not-work-in-ie9-and-ie10) might help you
