### ISSUE TITLE
How to style buttons now?

### ISSUE THREAD

**Issue by cklaffer** [rajeshwarpatlolla/ionic-datepicker#223]
In earlier versions i could easily style the buttons with my custom colors.

        setButtonType : 'button-energized', // the constant is defined elsewhere but contains color value
        todayButtonType : 'button-calm',
        closeButtonType : 'button-dark',
        modalHeaderColor:'bar-royal',
        modalFooterColor:'bar-royal',

How can I do it now? Thx in advance!

**Comment by rajeshwarpatlolla** [comment]
Please check the attached screenshot. You can use `button_set`,`button_today` and `button_close` classes to add custom styles to the buttons

![screen shot 2016-06-22 at 1 04 48 pm](https://cloud.githubusercontent.com/assets/9896335/16258144/0ac13654-387a-11e6-970d-e1b34b85c803.png)
