### ISSUE TITLE
Error: undefined is not a function (evaluating 'a.getYearsList(u.mainObj.from,u.mainObj.to)')

### ISSUE THREAD

**Issue by peterwong0613** [rajeshwarpatlolla/ionic-datepicker#227]
Anyone facing this issue on angular v1.5.3?

$scope.openDatePicker = function(event) {
    ionicDatePicker.openDatePicker({
      callback: function(val) {
        $scope.contact.dob = val;
        $scope.submit(true);
      },
      from: new Date().setFullYear(new Date().getFullYear() - 100),
      to: new Date(),
      templateType: 'popup'
    });
  };

**Comment by peterwong0613** [comment]
The IonicDatepickerService is undefined. It's only happened in devices. It's worked fine in browser

**Comment by rajeshwarpatlolla** [comment]
This is working fine. Please take a look at the latest version [v1.2.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.2.0)
