### ISSUE TITLE
year not select default

### ISSUE THREAD

**Issue by ricardofanetto** [rajeshwarpatlolla/ionic-datepicker#229]
The year not default select, the field empty

**Comment by greenlaw110** [comment]
We have encountered the same issue.

The code we use:

```javascript
    this.ionicDatePicker.openDatePicker({
      inputDate: this.customer.person.kvMap.dob ? new Date(this.customer.person.kvMap.dob) : new Date(1980, 0, 1),
      from: new Date(1900, 0, 1),
      to: new Date(),
      callback: (value) => {
        if (typeof value !== 'undefined') {
          this.customer.person.kvMap.dob = new Date(value);
          this.dobString = this.getDobString();
        }
      }
    });
```

And it shows:

![image](https://cloud.githubusercontent.com/assets/216930/16440792/75af0390-3e08-11e6-9e68-3fb32a480f15.png)


Any idea how to workaround this issue?

**Comment by deliverymanager** [comment]
+1

**Comment by koreem** [comment]
I've encountered the same issue.

**Comment by ricardofanetto** [comment]
some resolution?

**Comment by greenlaw110** [comment]
It's actually fixed on master already. Just not released. So our solution is to clone this project, then create a release in our own repository and update `bower.json` to make it point to that release: 

`ionic-datepicker": "https://github.com/ThinkingStudio/ionic-datepicker.git#v1.1.0x`

**Comment by koreem** [comment]
What was the fix exactly? @greenlaw110

**Comment by ricardofanetto** [comment]
Perfect, thank you @greenlaw110

**Comment by greenlaw110** [comment]
@koreem see https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/215

**Comment by rajeshwarpatlolla** [comment]
Please take a look at the latest version [v1.2.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.2.0)
