### ISSUE TITLE
ionic2

### ISSUE THREAD

**Issue by gbelmm** [rajeshwarpatlolla/ionic-datepicker#234]
Do you plan to create plugins for ionic 2?

**Comment by scorpnode** [comment]
I need one for ionic2 as well please

**Comment by Manduro** [comment]
Ionic 2 already has an [epic datetimepicker](http://ionicframework.com/docs/v2/components/#checkbox) included.

**Comment by peterpeterparker** [comment]
@Manduro right there is a default calendar selector from Ionic2, but it isn't that epic and user-friendly

**Comment by gbelmm** [comment]
http://ideas.ionic.io/idea/25 

"Functions - show events in month-view - create new events with multiple date selection - swipe between months Examples - Android Calendar Month-View: http://thenextweb.com/wp-content/blogs.dir/1/files/2015/04/google-calendar-android-month.png - iOS Canendar Month-View: https://cms-images.idgesg.net/images/article/2015/06/ios-calendar-month-details_2-100588310-orig.jpg - Angular Material Calendar: https://angular-material-calendar.bradb.net/"
