### ISSUE TITLE
showTodayButton is always true

### ISSUE THREAD

**Issue by louisdoe** [rajeshwarpatlolla/ionic-datepicker#237]
Hi,

thanks for this great plugin !

There is a small bug, I can't hide the Today button.... it seems like 
showTodayButton is always set to `true`, even if I remove this line:

```
showTodayButton: true
```

or if I use this line:

```
showTodayButton: false
```

Any idea what's wrong ?
Thanks

**Comment by jonathan-chin** [comment]
I can confirm this is still an issue. solution?

**Comment by louisdoe** [comment]
Yes, can you fix this @ajeshwarpatlolla ? ;) Thanks

**Comment by louisdoe** [comment]
Any news on this ? @rajeshwarpatlolla

**Comment by rajeshwarpatlolla** [comment]
You can expect this fix in the next version.

**Comment by louisdoe** [comment]
ok thank you @rajeshwarpatlolla  great job !

**Comment by postb99** [comment]
May you close the issue now? Which version solves it?
