### ISSUE TITLE
Pop up calendar alignment issue after adding bootstrap

### ISSUE THREAD

**Issue by Zscorp** [rajeshwarpatlolla/ionic-datepicker#239]
after adding bootstrap calendar is not aligned properly please let me how i can fix this.
i have attached the file that shows the issue.

thank you
![popupcalendar](https://cloud.githubusercontent.com/assets/5310536/17170506/1516d4ee-540c-11e6-858c-ac63a9426dc6.jpg)

**Comment by rajeshwarpatlolla** [comment]
This is intended for ionic, which doesn't use bootstrap. If you wish to override this component css, you have the classes which i mentioned in the readme.

**Comment by Zscorp** [comment]
thanks a lot.

is it possible to change colours using css?
