### ISSUE TITLE
Date being set to prior date because of daylight savings time

### ISSUE THREAD

**Issue by pinoyyid** [rajeshwarpatlolla/ionic-datepicker#24]
If I set the date to 2nd June 2015, what is being stored is the midnight (00:00:00.0) time. Because I'm BST (GMT -1 hour for daylight savings), the ISO date string that is being stored is 1st June 2015 at 23:00.

I've worked around it by setting the value in the call back to 12-midday with val.setHours(12).

**Comment by rajeshwarpatlolla** [comment]
May be in that case you can manually add an hour for now, in the callback. I will look in to this issue in the upcoming releases.

**Comment by rajeshwarpatlolla** [comment]
You can add the respected time to the input. May be by adding the time different because of the day light saving.
