### ISSUE TITLE
Changing only YEAR doesn't update the date

### ISSUE THREAD

**Issue by louisdoe** [rajeshwarpatlolla/ionic-datepicker#241]
Hi

I made a short video of the bug: [datepicker bug](https://www.youtube.com/watch?v=KPBXH2Jn-Wg)

When I go to the date picker, the YEAR doesn't display in the dedicated field.

And if I change only the year, the "date" is not updated accordingly.

Can you check this please ?

Thanks a lot for this plugin ;)

**Comment by rajeshwarpatlolla** [comment]
You need to select a day to get that date in the callback function.

**Comment by louisdoe** [comment]
Hi Raj

but if the user only want to come back here to change the date only ?

2016-08-25 9:44 GMT+02:00 Rajeshwar <notifications@github.com>:

**Comment by louisdoe** [comment]
Hi @rajeshwarpatlolla , please reopen this issue !
Because, if we think UX : the user sets a month, yeard and day, then presses OK. Then he realizes he chose the wrong year. He comes back, changes the year, and the day number must still be the same without reselecting it.
Can you please do this you think ?
