### ISSUE TITLE
Default disableWeekdays

### ISSUE THREAD

**Issue by vivek9593** [rajeshwarpatlolla/ionic-datepicker#243]
Is a 6th day (Saturday) of the week is set as disabled by default? I'm using only the mandatory options, like callback and templateType. Although I didn't set disableWeekdays, or when I set this on an empty array, Saturday is always disabled.

My code is

var ipObj1 = {
callback: function (val) { //Mandatory
console.log('Return value from the datepicker modal is : ' + val, new Date(val));
$scope.selectedDate1 = moment(val).format('DD MMM YYYY');
},
from: moment(),
to: moment().add(2,'years'),
showTodayButton: false,
closeOnSelect: false,
templateType: 'modal',
disableWeekdays:[]
};
ionicDatePicker.openDatePicker(ipObj1);
![calender](https://cloud.githubusercontent.com/assets/12856243/17676165/daf85dca-634a-11e6-8929-04d5a91a9472.PNG)

**Comment by rajeshwarpatlolla** [comment]
No weekday will be disabled by default.
