### ISSUE TITLE
Any way to add a time picker?

### ISSUE THREAD

**Issue by keithpickering** [rajeshwarpatlolla/ionic-datepicker#248]
I'm using the Mobiscroll plugin in my app, and I'd like to add it to this datepicker so users can select a time as well as a date. How can I go about editing the HTML output by this plugin? I see it in the `src` folder but I'm not sure how to build `ionic-datepicker.bundle.min.js` from that.

**Comment by rajeshwarpatlolla** [comment]
Both time picker and the date picker are different. You can install both the plugins and once you get the callback of one component, call the other components function which will open the second one, once the first one is closed. But both of them can not be added into one.
If you still wish to merge both of them into one component, you need to modify the source code as you mentioned, which takes considerable time and efforts.
