### ISSUE TITLE
Adding classes to buttons

### ISSUE THREAD

**Issue by jonathan-chin** [rajeshwarpatlolla/ionic-datepicker#249]
#223 
There's no easy way to style buttons or elements now. Instead of individual style properties, it would be immensely more useful to be able to add / edit css classes. This way, I can style them easily to match updated ionic classes (like button-balanced)

**Comment by rajeshwarpatlolla** [comment]
There are two classes which i am already adding at the top most level. `ionic_datepicker_popup` for popup type and `ionic_datepicker_modal` for modal type. You can use the classes i mentioned at  [issue#223](https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/223).
Something like 

````
.ionic_datepicker_popup .button_set { }
````
