### ISSUE TITLE
Month selector not working as expected

### ISSUE THREAD

**Issue by jamesvsshark** [rajeshwarpatlolla/ionic-datepicker#250]
If by default it is the last day of the month or I select the last day of the month and then choose the next month in the drop down -- the calendar will skip the correct next month and go to the following.

http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/home
1. Open date picker and select October 31
2. Change dropdown to November
3. Expected - November becomes visible; Actual - December becomes visible

**Comment by jamesvsshark** [comment]
Possible fix in PR #251

**Comment by rajeshwarpatlolla** [comment]
It's not reproducing. I tested it in the demo link itself.

**Comment by dickverweij** [comment]
This is caused by the following code that appears everywhere in the code.

$scope.currentDate.setMonth(XXX)

For example:
if the currentDate = 31-Jan-2017 setting the month on februari 
will result in 31-Feb-2017. That date does not exist and will result in 03-Mar-2017

**Comment by dickverweij** [comment]
funny this error will only reproduce on 31 or 30th of the month

**Comment by postb99** [comment]
Duplicate of #297, see comments there.
