### ISSUE TITLE
Keep chosen day, after changing year or month

### ISSUE THREAD

**Issue by louisdoe** [rajeshwarpatlolla/ionic-datepicker#254]
Hi @rajeshwarpatlolla 

could you fix the following behavior:
it should be possible for the user to select a day, then to change the year or month while keeping the chosen day.

Thanks !

**Comment by rajeshwarpatlolla** [comment]
With this version, it is not possible that way. The user has to select day at the end of the selections.

**Comment by louisdoe** [comment]
Do you plan on doing this on a next version ?
Ohterwise can I fork your code ?

**Comment by rajeshwarpatlolla** [comment]
Not exactly in the next version. But might be possible in the upcoming versions. If possible please make a PR with the changes needed.

**Comment by louisdoe** [comment]
Can you give me the protocol to make my own branch and then a PR ?
