### ISSUE TITLE
Select boxes not updating at prevMonth and nextMonth

### ISSUE THREAD

**Issue by michaelargast** [rajeshwarpatlolla/ionic-datepicker#26]
Hi all,

I have the following issue with the datepicker:

Once I selected a month or a year from the select boxes and then change the months via the buttons (prevMonth and nextMonth) then the select boxes will not update to the selected month or year any longer.

Can anyone confirm this? Or know a possible solution for this?

Regards
Michael

**Comment by michaelargast** [comment]
Do you have a hint what could cause this behavior?

I'd gladly look into fixing it and contribute the solution.

**Comment by rajeshwarpatlolla** [comment]
This bug is fixed in the latest version v0.4.0.
