### ISSUE TITLE
Month Year dropdown closes 

### ISSUE THREAD

**Issue by swapnil002** [rajeshwarpatlolla/ionic-datepicker#263]
Hi,

When I open datepicker in a popup mode and click on Month or Year dropdown text, (not on the side arrow), select dropdown comes and disappers in a second. But if i keep pressing the dropdown for more than 2 seconds, dropdown comes as normal.

Can anyone help me with this? Thanks.

**Comment by rajeshwarpatlolla** [comment]
This is not reproducible in the demo page. Are you able to reproduce it in demo page also?

**Comment by swapnil002** [comment]
No. This only comes in mobile phone.

**Comment by viebig** [comment]
Its possible to reproduce the issue with chrome device inspection. It makes the dropdowns nearly unusable. The whole label should be clickable.

![selection_101](https://cloud.githubusercontent.com/assets/356510/19056223/52553900-899e-11e6-8113-74e2189cd3a1.png)

**Comment by rajeshwarpatlolla** [comment]
I tested in device too. I am able to open the dropdowns.
