### ISSUE TITLE
Set callback date in datepicker popup

### ISSUE THREAD

**Issue by inceptiveDipak** [rajeshwarpatlolla/ionic-datepicker#265]
Hello @rajeshwar-fissionhq, 
I want to set inputDate as callback date in popup.

 //date picker..
    var ipObj1 = {
      callback: function (val) {  //Mandatory
        console.info('Return value from the datepicker popup is : ' + val, new Date(val));
        var timestamp = moment(new Date(val)).format("MM/DD/YYYY");
        $scope.startDate = timestamp;
        console.log($scope.startDate);
      },
      disabledDates: [
        new Date()          //Optional
      ],
      to: new Date(2050, 6, 31), //Optional
      inputDate:new Date($scope.startDate),      //Optional
      mondayFirst: true,          //Optional
      closeOnSelect: false,       //Optional
      templateType: 'popup'       //Optional
    };

But will not working at all.
Please help me.
Thank You !!

**Comment by rajeshwarpatlolla** [comment]
Please read the documentation again. You will get callback if you select any date.
