### ISSUE TITLE
Current date unselect when change month or year

### ISSUE THREAD

**Issue by KixS** [rajeshwarpatlolla/ionic-datepicker#266]
Hi,

I have a small improvement suggestion.
When a user select first the date of the month and then proceed to change the month or the year, the prior selected date of the month disappears and the user has to select it back again.

Would it be possible to keep the current selected date ?

Cheers

**Comment by ignacio-chiazzo** [comment]
Hi @KixS  I created an extension of this project where this feature is included. I also make a Pull Request with a specific commit that implements the feature mentioned. [ionic-date-picker-extended](https://github.com/ignacio-chiazzo/ionic-datepicker-extended)

**Comment by louisdoe** [comment]
this should be implemented in the main version @rajeshwarpatlolla

**Comment by ignacio-chiazzo** [comment]
@louisdoe I created a Pull Request to Master branch of this repository. Those changes can be found here : https://github.com/rajeshwarpatlolla/ionic-datepicker/pull/278.

The repo where this issue is updated can be found here : https://github.com/ignacio-chiazzo/ionic-datepicker-extended

**Comment by rajeshwarpatlolla** [comment]
This has been fixed and merged with a PR.
