### ISSUE TITLE
hao to change the default color?   QAQ

### ISSUE THREAD

**Issue by iyibo** [rajeshwarpatlolla/ionic-datepicker#271]
excuse me ！ it`s a noob question   QAQ
 the css（lib/ionic-datepicker/src/ionic-datepicker.style.css） default color is #019688. 
 i want changge it other color.
 hao to do it

**Comment by iyibo** [comment]
I solved the problem ，so naive，dont change the src（lib/ionic-datepicker/src/ionic-datepicker.style.css） and changed it on src（lib/ionic-datepicker/dist/ionic-datepicker.bundle.min.js）

**Comment by BioPhoton** [comment]
It's also possible to override the datepicker css with your own styles in you apps css file...

**Comment by rajeshwarpatlolla** [comment]
@iyibo, please take a look at the documentation, where i have mentioned a few css classes, with which you can change the colors.

**Comment by diegolmello** [comment]
It would be awesome to config colors in js.
My app change colors by changing sex param (M/F).
My first option is to query classes.
Any other idea?

**Comment by rajeshwarpatlolla** [comment]
In master branch now

**Comment by diegolmello** [comment]
Good job, man!!
