### ISSUE TITLE
Unknown provider: ionicDatePickerProvider

### ISSUE THREAD

**Issue by coolara** [rajeshwarpatlolla/ionic-datepicker#274]
Unknown provider: ionicDatePickerProvider

**Comment by coolara** [comment]
i hav this problem how to solve it

**Comment by rajeshwarpatlolla** [comment]
I hope you didn't inject **ionic-datepicker** in the main module of your application.

**Comment by coolara** [comment]
i found the reason  it's the version . when i update it worked
