### ISSUE TITLE
datepicker - popup issue.

### ISSUE THREAD

**Issue by arshad104** [rajeshwarpatlolla/ionic-datepicker#275]
Popup is changing background color and not showing some dates and also week days. See the attachment. Please help

![error](https://cloud.githubusercontent.com/assets/16588323/19831196/778b2386-9e1d-11e6-9c6b-8e2c4b6c9f88.png)

**Comment by rajeshwarpatlolla** [comment]
You might be overriding the css somewhere in your application. Please cross check it.

**Comment by arshad104** [comment]
Thanks for your response. I fixed it.

How can I increase the width of month and year drop down? Thanks once again.

**Comment by rajeshwarpatlolla** [comment]
There are a few css classes i have added. Please take a look at them in the documentation.
