### ISSUE TITLE
Pop-up closes Automatically

### ISSUE THREAD

**Issue by PradeepSmg** [rajeshwarpatlolla/ionic-datepicker#283]
Date Picker closes automatically and prints "ionic-datepicker popup closed" message in console.

Here is my Object:
`$scope.startdatepickerObject = {
setButtonType : 'button-dark', //Optional
todayButtonType : 'button-dark', //Optional
closeButtonType : 'button-dark', //Optional
from : new Date(),

callback : function(val) {//Mandatory
// $scope.isFilingDateChanged = false;
startdatePickerCallback(val);
},
dateFormat : 'dd-MM-yyyy' //Optional
};
var startdatePickerCallback = function(val) {
if ( typeof (val) === 'undefined') {
// console.log('No date selected');
} else {
$scope.startdatepickerObject.inputDate = new Date(val);
}
};
$scope.openDatePicker = function(){
      ionicDatePicker.openDatePicker($scope.startdatepickerObject);
    }; `

HTML:

`<button class="button button-dark button-clear" ng-click="openDatePicker()">
      <i class="icon ion-calendar"></i> </button>`

When I click on the button date picker opens and closes in a flash after clicking it for 3 to 4 times it opens and stays.

**Comment by rajeshwarpatlolla** [comment]
It will not close the popup for sure. Please try to cross check the steps you did with what i mentioned in the documentation.

**Comment by PradeepSmg** [comment]
Actually i have used it in couple of other controller it works fine in them this happening in this particular controller.

**Comment by rajeshwarpatlolla** [comment]
So it is not the component specific right. Could you please cross check with the other controller code.

**Comment by PradeepSmg** [comment]
The problem arises when I add the button inside row and  make separate column for that button.

````
<div class="row">
  <div class="col col-67">
  		<input  type="text"  ng-model="startTime" required disabled/>
  </div>
   <div class="col col-33">
	<button class="button button-dark button-clear" ng-click="openDatePicker()">
      <i class="icon ion-calendar"></i> </button>  
  </div> 
</div>` 
```
