### ISSUE TITLE
Datepicker picking previous day for stringify IOS 10.0.2

### ISSUE THREAD

**Issue by MrShakes** [rajeshwarpatlolla/ionic-datepicker#284]
The datepicker seems to pick the right date when stored but upon stringifying it picks the day before, e.g. I pick 1 Dec, stringify then gives me 30 Nov (Day before). Works well on Android.
Besides this, it's a great datepicker. Please fix.

System information:
Cordova CLI: 6.4.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8

**Comment by Jesspu** [comment]
also having this issue when passing in a date for the field inputDate, the correct date is being passed in but the date picker displays the day previous. So if inputDate: is new Date(2016-01-13) the date picker will display the 12th.

**Comment by rajeshwarpatlolla** [comment]
Thanks for your solution @Jesspu
