### ISSUE TITLE
can't update plugin version

### ISSUE THREAD

**Issue by louisdoe** [rajeshwarpatlolla/ionic-datepicker#288]
Hi

I just did

    bower update ionic-datepicker --save

but when I do `ionic plugin list` it displays an old version : 

    cordova-plugin-datepicker 0.9.2 "DatePicker"

it should be the last current version 1.2.1.

Any idea ?

thanks

**Comment by rajeshwarpatlolla** [comment]
This is not a cordova plugin. It's purely ionic plugin. Try `bower cache clean` and then install again using `bower install ionic-datepicker`.
