### ISSUE TITLE
Today button returns the current Timestamp.

### ISSUE THREAD

**Issue by raphaelduartepinheiro** [rajeshwarpatlolla/ionic-datepicker#29]
Hello, the button "Today" returns the current timestamp (Ex.: "Tue Jun 30 2015 21:35:44").
If you select a date, by clicking on the day, the time epoch is 00:00:00.

**Comment by rajeshwarpatlolla** [comment]
Ye, because it is only for date picker functionality. So you will get the date completely, but not the time.

**Comment by raphaelduartepinheiro** [comment]
Ok, but these two routines generate different results and for integration purposes, with ionic-timepicker, it is more suitable.

**Comment by rajeshwarpatlolla** [comment]
Please use the latest version v0.4.0. This bug is fixed in this version.
