### ISSUE TITLE
karma error

### ISSUE THREAD

**Issue by papotte** [rajeshwarpatlolla/ionic-datepicker#290]
I am trying to test my app with karma, and I get an error generated by this plugin: 

>      TypeError: Cannot read property 'remove' of undefined

This is caused because in my tests, I call $digest on the rootScope which in turn broadcasts $destroy to everything (apparently that's normal).
I figured that if, on ionic-datepicker.provider.js (and in the compiled version respectively) you change line 204 to 
` if($scope.modal) $scope.modal.remove();`
then the problem goes away.

It would be great if you could add this, or a similar solution, to the next version :)

**Comment by rajeshwarpatlolla** [comment]
Will you be able to make a PR with your change? If so, that would be great.

**Comment by papotte** [comment]
Sorry, I was out of town for the holidays.

I could make a PR, but I don't really know how to. I tried following the instructions [here](https://help.github.com/articles/creating-a-pull-request/) but it is giving me a permission denied error, which makes total sense...

Do I need to do something different?
