### ISSUE TITLE
Problem output selected date

### ISSUE THREAD

**Issue by Compulsor** [rajeshwarpatlolla/ionic-datepicker#291]
Hello there!

I am using your plugin for a school project.
As I was testing it out, I came across something important: the output of the selected date.
It is currently displayed as: "Tue Jan 24 2017 00:00:00 GMT+0100 (Romance Standard Time)". I would like to know if it is possible to change this output to following format "yyyy-mm-dd" as I have to use this format in order to make API calls.

Thanks in advance
Compulsor

**Comment by rajeshwarpatlolla** [comment]
You can convert this date to any other format using the `Date` object. Please refer the `Date` object in javascript.

var a = new Date("Tue Jan 24 2017 00:00:00 GMT+0100")
var b = a.getFullYear() +'-' +(a.getMonth()+1) +'-'+a.getDate()
