### ISSUE TITLE
Text is aligned right in the the drop down.

### ISSUE THREAD

**Issue by NileshSystematix** [rajeshwarpatlolla/ionic-datepicker#293]
Whenever selecting the month and year from the drop down text is right aligned in it with huge width drop down.

so please provide me some solution to it.

**Comment by rajeshwarpatlolla** [comment]
Please [go here](https://github.com/rajeshwarpatlolla/ionic-datepicker#css-classes) and user the classes which are assigned for dropdowns, and change the stylings as per your need.
