### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by AgNm** [rajeshwarpatlolla/ionic-datepicker#294]
Hello,

I have created an ionic Application, While choosing the date from date picker, I'm getting date in below format in my input box :

Wed Jan 04 2017 00:00:00 GMT+0530

I want to change it to : 04-01-2017 

Will you please let me know how I can change it?

**Comment by tobeee** [comment]
Date format output seems completely broken for me. I'm continually getting epoch time, rather than any kind of string formatting :(

**Comment by NileshSystematix** [comment]
$scope.datePickerValue = $filter('date')(new Date(val),'dd-MM-yyyy');

If you want to change the date format use 

modelname= datepicker input field.
$scope.modelname = $scope.datePickerValue = $filter('date')(new Date(val),'dd-MM-yyyy');

in ipObj1 variable in controller.

**Comment by rajeshwarpatlolla** [comment]
You can use `dateFormat: 'dd MMMM yyyy'` property in the object.
