### ISSUE TITLE
Disable Today

### ISSUE THREAD

**Issue by PetruMagdeleine** [rajeshwarpatlolla/ionic-datepicker#298]
Hi,

It seems impossible to prevent an user to pick today.

With these settings :
`showTodayButton : false,
disabledDates : [
    new Date() // today
],
`
the default date (when open) is today and the user can use the Select button to pick today.

I tried with `inputDate`, but it lock to only the inputed date.

**Comment by alexandretok** [comment]
You can use the option `inputDate` and set it to another day apart from today. 
This is the option that sets the default date.

**Comment by PetruMagdeleine** [comment]
Yes, this was the solution. To be more specific, it didn't work the same depending the Date format I used. 
It worked with :
`inputDate: new Date(2017, 2, 2)`  but not using a Date from moment.js
