### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by flierville** [rajeshwarpatlolla/ionic-datepicker#299]
Hello, i only onclude this js : 
`lib/ionic-datepicker/dist/ionic-datepicker.bundle.min.js`
The Datepicker works good.

How is it possible to customize it ? I would like to modify the background color of differents elements.
(the css is not included in my app, so I can not edit this file)

Thank you

**Comment by rajeshwarpatlolla** [comment]
[Here](https://github.com/rajeshwarpatlolla/ionic-datepicker#css-classes), i have mentioned a few css classes, which will help you change the colors as per your need.
