### ISSUE TITLE
How to call date picker in index.html

### ISSUE THREAD

**Issue by akashsky44** [rajeshwarpatlolla/ionic-datepicker#303]
when i am using this html source code date picker not open.

<body ng-app="akash">

    <ion-pane>
      <ion-header-bar class="bar-stable">
        <h1 class="title">Ionic Blank Starter</h1>
      </ion-header-bar>
      <ion-content>
        <div class="card padding">
      <button class="button button-positive button-block" style="margin: 0;" ng-click="openDatePicker()">Open Date Picker Popup
      </button>
    </div>
      </ion-content>
    </ion-pane>
  </body>

**Comment by MZabih** [comment]
try calling it openDatePickerOne()

**Comment by konstantinkrassmann** [comment]
Where's your controller code ? you cant just use this without an controller actually opening the picker.

**Comment by rajeshwarpatlolla** [comment]
You should call this from a controller.
