### ISSUE TITLE
Could not Set Date Format

### ISSUE THREAD

**Issue by MZabih** [rajeshwarpatlolla/ionic-datepicker#304]
I've followed all the steps but it is showing me the date in this format Wed Mar 08 2017 00:00:00 GMT+0500 (PKT) however I need to display in 28 Feb, 17 this format . Thanks in advance

**Comment by akashsky44** [comment]
write in your controller this 
var ipObj1 = {
      callback: function (val) {  //Mandatory
        console.log('Return value from the datepicker popup is : ' + val, new Date(val));        
        $scope.selectedDate1 = new Date(val);
      }
and wtite in view in where you want to see this
{{selectedDate1 | date:'dd-MMMM-yyyy'}}

**Comment by Nitrick** [comment]
if u are using input type="text" then you should try this it will work
$scope.secondCurrentDate = $filter('date')(new Date(), 'dd MMMM,yyyy')
$scope.secondCurrentDate = $filter('date')(new Date(val), 'dd,MMMM,yyyy')
