### ISSUE TITLE
How to Store DatePicker Date in Firebase

### ISSUE THREAD

**Issue by akashsky44** [rajeshwarpatlolla/ionic-datepicker#306]
<button class="button button-icon ion-compose" ng-click="openDatePicker()">  when i click on this button date store in firebase database how ?

**Comment by postb99** [comment]
Put your code in the callback, read the documentation.

**Comment by Shuugle** [comment]
Firebase won't support Date format. So you should change it into a String format by 
getValue = val.toISOString();
