### ISSUE TITLE
Weird behavior on change month 

### ISSUE THREAD

**Issue by enricopuglia** [rajeshwarpatlolla/ionic-datepicker#311]
Hello,
I have a weird bug about date selection after month navigation:
when i move from a month to another and then close the popup with the "close button", highlighted date is selected.
I can't replicate this behavior on demo.
this happens with the new release. 
after a rollback to a previous version I have no problem.
I am not sure, but I think it is related to this #266 

Thanks a lot

**Comment by hajHajPulaj** [comment]
Hello, does the issue happen also when you change year?

**Comment by enricopuglia** [comment]
Hi hajHajPulaj
yes, it does
