### ISSUE TITLE
Ionic datepicker range

### ISSUE THREAD

**Issue by oumayma-ltaief** [rajeshwarpatlolla/ionic-datepicker#312]
Hello, I am using ionic-datepicker plugin for my ionic app. Is there any option to pick a range of dates (start date , end date) like bootstrap angularjs plugin daterangepicker https://github.com/fragaria/angular-daterangepicker? 
Thanks.

**Comment by rajeshwarpatlolla** [comment]
No, with the existing component, it is not possible.
