### ISSUE TITLE
Issue on updating object input-obj

### ISSUE THREAD

**Issue by oumayma-ltaief** [rajeshwarpatlolla/ionic-datepicker#313]
Hello I am using ionic-datepicker. In my callback function I update attribute "to" and "from" of my input-obj  object scope but when ionic -datepicker is shown again it is not updated however the object is updated from angularjs part.
How can I refresh ionic -datepicker please?

**Comment by rajeshwarpatlolla** [comment]
You also have to modify this in the object you are passing to the date picker. Please refer the attached image.
![date-picker](https://user-images.githubusercontent.com/9896335/32425723-4a64b514-c2db-11e7-9a86-fbad0f0eb670.png)
