### ISSUE TITLE
No option to change the order of buttons.

### ISSUE THREAD

**Issue by rajkumar-osm** [rajeshwarpatlolla/ionic-datepicker#317]
Hi Everyone,
I see there is no option or configuration available to set the order of buttons in the popup/modal.

In the date picker popup, set button is always left side, close button is always on the right side, but I want it other way.

Please let me know if there is an option available, if not also let me know what I can do for this requirement.

**Comment by rajeshwarpatlolla** [comment]
As of now, there is no option to change the order of the buttons.
