### ISSUE TITLE
Show last selected date in date picker

### ISSUE THREAD

**Issue by NileshSystematix** [rajeshwarpatlolla/ionic-datepicker#321]
@rajeshwarpatlolla 

Hello Guys,

As default today's date should be selected and if user selects it's value from the date picker then from next time the value which is selected should be shown selected to the user in date picker.

Please find me some solution asap.

**Comment by vibcure** [comment]
@rajeshwarpatlolla  I am also getting same issue. Waiting for your reply

**Comment by rof20004** [comment]
@NileshSystematix I did a little logic to do this:

This is my object, I initialized it with inputDate: new Date()
```
ipObj = {
			callback: function (val) {  //Mandatory
				vm.selectedDateDate = val
			},
			inputDate: new Date(),
			disabledDates: disabledDates,
			from: enabledDates[0],
			to: enabledDates[enabledDates.length - 1],
			showTodayButton: false,
			templateType: 'modal'
		}		
```

Then in method that opens my ionic date picker modal, I did this:

```
function openDatePicker () {
		ipObj.inputDate = vm.selectedDateDate ? new Date(vm.selectedDateDate) : new Date()
		ionicDatePicker.openDatePicker(ipObj);
	}
```

Then is this :dancer:

**Comment by rajeshwarpatlolla** [comment]
@rof20004 that's exactly how it is implemented. Thanks for clarifying the issue.
