### ISSUE TITLE
Similar code for Ionic 2?

### ISSUE THREAD

**Issue by sujiththakur** [rajeshwarpatlolla/ionic-datepicker#323]
Hi,
This is not an issue. I'm just wondering if there is a similar project like this in Ionic 2 as well. Please do let me know. I really need it.

**Comment by rajeshwarpatlolla** [comment]
This is where it is https://github.com/rajeshwarpatlolla/ionic2-datepicker, but it's not deployed yet, as i would like to make some changes.

**Comment by sujiththakur** [comment]
Oh when can we expect this ?
