### ISSUE TITLE
Previous and next button navigation issue

### ISSUE THREAD

**Issue by NileshSystematix** [rajeshwarpatlolla/ionic-datepicker#328]
@rajeshwarpatlolla 

I have one date picker in which I have set that use can't select the date lesser than last six month date and also the user can't select higher date as today's date. 

For ex. Today's date is 01/11/2017 so user can select max of previous date as 01/05/2017 and max higher date as 01/11/2017. After the previous and today's date all dates are disabled means the date before 01/05/2017 should be disabled and the dates after 01/11/2017 should be disabled. But they are disabled but the navigation forces are disabled after the condition fails but they are changing on the condition failure. Below is my code.

  var datePickerObj = {
        						inputDate: new Date(),
        						titleLabel: 'Select a Date',
        						setLabel: 'Set',
        						todayLabel: 'Today',
        						closeLabel: 'Close',
        						mondayFirst: false,
        						weeksList: ["S", "M", "T", "W", "T", "F", "S"],
        						monthsList: ["Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"],
        						templateType: 'popup',
                                from: new Date(2012, 8, 1), //Optional
                                to: new Date(2018, 8, 1),
        						showTodayButton: false,
        						dateFormat: 'dd-MMMM-yyyy',
        						closeOnSelect: false,
        						disableWeekdays: []
        				};
        				ionicDatePickerProvider.configDatePicker(datePickerObj);

    var ipObj2 = {

                  callback: function(val) { //Mandatory
                     $scope.toDate = val;
                     $scope.toDateChange = $filter('date')(new Date(val), 'dd-MM-yyyy');
                     $scope.delivery.toDate = $filter('date')(new Date(val), 'dd-MMM-yyyy EEE');
                      console.log('Return value from the datepicker popup is : ' + val, new Date(val));
                  },
                  disabledDates: [ //Optional
                  ],
                  from: new Date(moment().subtract(6, 'months').endOf(new Date(moment().format('YYYY-MM-DD'))).format('YYYY-MM-DD')), //Optional
                  to: new Date(moment().format('YYYY-MM-DD')), //Optional
                  inputDate: new Date(), //Optional
                  mondayFirst: true, //Optional
                  disableWeekdays: [], //Optional
                  closeOnSelect: true, //Optional
                  templateType: 'popup' //Optional
                          };

              $scope.openDatePicker1 = function() {
                 if($scope.delivery.toDate==undefined || $scope.delivery.toDate=="" ){
                 }
                 else{
                    $scope.toDateChange1 = $filter('date')(new Date($scope.toDate), 'yyyy-MM-dd');
                   //  alert("newdate" + new Date($scope.toDateChange1));
                    ipObj2.inputDate = new Date($scope.toDateChange1); //Optional
                 }
                  ionicDatePicker.openDatePicker(ipObj2);
              };

It the previous and next button navigation can't be stop it is ok but I am getting year drop down value as empty.

I will be very thankful if you will provide me quicker solution.

**Comment by rajeshwarpatlolla** [comment]
Could you please add a small video of this issue, so that i will try to understand what is going wrong.

**Comment by rajeshwarpatlolla** [comment]
Duplicate for #318
