### ISSUE TITLE
Size of month and year select boxes trimmed to 3 characters

### ISSUE THREAD

**Issue by amrigo** [rajeshwarpatlolla/ionic-datepicker#33]
The size of the month and year select boxes is trimmed to 3 characters, into Android. I just  try to edit datepicker-modal.html and set size to 26 but could not see any diference.

**Comment by rajeshwarpatlolla** [comment]
Can you send some screen shots for this issue?

**Comment by comapedrosa** [comment]
![image](https://cloud.githubusercontent.com/assets/3918797/8692888/06463e5e-2ad3-11e5-942b-3ec82ea75a26.png)

@amrigo may refer to this @rajeshwarpatlolla!

**Comment by rajeshwarpatlolla** [comment]
Thanks guys. I will add some customisable CSS classes in the upcoming releases, then you will be able to customise it easily.

**Comment by rajeshwarpatlolla** [comment]
Customisable classes added in new version v0.5.0

**Comment by amrigo** [comment]
Hi Rajeshwar wich is the file i can customize ? and wich selector  ? i try editing src/style.css but unsucessfully.

**Comment by amrigo** [comment]
i try, and it work on windows phone but did not work into android  src/style.css : 

 .month_select{
  width:60px !important;
}

.year_select{
  width:60px !important;
}

**Comment by amrigo** [comment]
i am using the version 0.6.0

**Comment by rajeshwarpatlolla** [comment]
inside `drop_down` class you will find the classes for drop downs. Please inspect the element, you will see those classes.
