### ISSUE TITLE
Close ionic-datepicker on History Back

### ISSUE THREAD

**Issue by rhoulay** [rajeshwarpatlolla/ionic-datepicker#35]
Hi, thanks your great work. 
And I find bug when open ionic-datepicker, then widows history back, the ionicPopup still shown. How can I close ionic-datepicker programmlly?

**Comment by rajeshwarpatlolla** [comment]
Hi Felix, Hope you remember me.
For now, you have to close it manually by clicking on either close or set button. Thanks for raising this bug. I will try to add this feature in the next release.

**Comment by rajeshwarpatlolla** [comment]
I hope you are using it in the web browser. But closing this component is mandatory here.

**Comment by gaterking** [comment]
How to use this feature? When I click back button on in Android WebView, only the ionic view go back,but the datepicker is showing.

**Comment by PradeepSmg** [comment]
Any updates on this issue.

**Comment by vikas0vanvi** [comment]
Any updates???

**Comment by imrealashu** [comment]
Any updates?

**Comment by vikas0vanvi** [comment]
I did workaround with this in controller

  $scope.$on('$stateChangeStart', function () {
        $('.button_close').trigger('click');
    });
