### ISSUE TITLE
Feature request: Time

### ISSUE THREAD

**Issue by Langstra** [rajeshwarpatlolla/ionic-datepicker#36]
It would be nice to be able to also input time.

**Comment by rajeshwarpatlolla** [comment]
I thought to implement this feature after got suggestion from few other guys earlier. But my concern is i am using a popup for this component. If i make the text boxes to enter values, again the users will get another popup(key board). Does this look good? What do you suggest?

**Comment by Langstra** [comment]
You could use the html5 input type 'time'. This would give you a native popup for the platform to enter the time I think. This prevents the keyboard from coming up. 

Other options would be buttons you can touch to increase/decrease the hours/(tens of) minutes (so people dont have to tick 30 times to get to 30 minutes). example: http://plnkr.co/edit/QujX5A?p=preview

Or else perhaps a dropdown, like this: http://adamalbrecht.github.io/q-date/

I think the favoured solution would be either the first or the second, but that would depend on wheter or not the keyboard comes up. I agree with you on the fact that the keyboard popping up would not be the best thing that can happen.

**Comment by rajeshwarpatlolla** [comment]
May be its good have a drop down or 5 or 10 minute increment as you said. You can expect this functionality in the next release. Thanks for your suggestion. They really make some sense.

**Comment by rajeshwarpatlolla** [comment]
The drop down functionality is implemented. You can use the latest version to have drop downs. `date` is not supported in all the browsers. So i haven't implemented such feature.
