### ISSUE TITLE
Create a webpack compatible .bundle.js

### ISSUE THREAD

**Issue by apobbati** [rajeshwarpatlolla/ionic-datepicker#37]
Hi,

It would be better to integrate with build tools like Webpack if the dist directory contained a single ionic-datepicker.bundle.js instead of multiple *.js files.

Thanks,

**Comment by rajeshwarpatlolla** [comment]
For now there are three files in the `dist` directory. So do you want to merge those three files in to one file?

**Comment by rajeshwarpatlolla** [comment]
Please use the new version i.e. `v0.7.0` This bug has been fixed.
