### ISSUE TITLE
First day of week

### ISSUE THREAD

**Issue by hakano** [rajeshwarpatlolla/ionic-datepicker#39]
In some regions, Monday is the first day of the week. So, it would be nice to be able to customize the view to start from the Monday.

**Comment by comapedrosa** [comment]
Hi @rajeshwarpatlolla yesterday you did a commit in the ionic-datepicker.js file with the name "monday as first day of week", I uploaded the file to my project but it isn't working yet. Do I have to change anything else? Thank you

**Comment by rajeshwarpatlolla** [comment]
Yes you have to mention that you need first day as Monday in your HTML.  Add `mondayfirst=true` in the HTML. It should be as the property to the `ionic-datepicker` directive.
Any ways i will add the description and i will merge few other PR s in to the next release.

**Comment by comapedrosa** [comment]
Thank you @rajeshwarpatlolla I already found it looking on the source code and I deleted the comment!Thank you anyway!

**Comment by rajeshwarpatlolla** [comment]
Ok no issues.

**Comment by miguelp77** [comment]
I think that `mondayfirst` functionallity has been removed in v0.5.0 release
I added `mondayfirst="true"` in my HTML and Sunday is the first day of week

**Comment by rajeshwarpatlolla** [comment]
I am planning to add it in the next immediate release.

**Comment by rajeshwarpatlolla** [comment]
Please use the v0.6.0. This has been fixed i this version.
