### ISSUE TITLE
Disable Particular Day In a Calender

### ISSUE THREAD

**Issue by kapilkarda** [rajeshwarpatlolla/ionic-datepicker#41]
Hello,

I am working on order booking application in which restaurant is close on monday so I have disable the every button on monday in calender. Please check it.

Thanks in Advance.

**Comment by rajeshwarpatlolla** [comment]
For now there is no such functionality to disable particular days in a week.

**Comment by kapilkarda** [comment]
Hello,
Thanks for your quick reply, so could you please guide me how to add this functionality. I will do it.
Thanks
