### ISSUE TITLE
Support for start and end date

### ISSUE THREAD

**Issue by saikilaru** [rajeshwarpatlolla/ionic-datepicker#42]
Rajesh, do you have any plans to provide attribute support for setting a start and end dates? So that user can only pickup those valid dates? My use for a time card reporting app, where user can only select a day from valid range of dates?

Thanks,
Sai.

PS: Keep up the good work.

**Comment by rajeshwarpatlolla** [comment]
Hi @saikilaru, for now i have implemented disabling previous and future dates. But there is no such feature to disable between a range of dates. May be in the upcoming releases i will work on this feature.
Thanks for your suggestions.

**Comment by saikilaru** [comment]
Thanks Rajesh. This is really handy component.

**Comment by rajeshwarpatlolla** [comment]
In the latest version you can disable specific dates. But disabling from and to dates is not yet done.

**Comment by saikilaru** [comment]
Thanks Rajeshwar, I'll try it out.

**Comment by rajeshwarpatlolla** [comment]
Please use the new version i.e. `v0.7.0` This bug has been fixed.
