### ISSUE TITLE
Datepicker broken on android and chrome - Ionic v1.0.1

### ISSUE THREAD

**Issue by adonespitogo** [rajeshwarpatlolla/ionic-datepicker#46]
![screenshot_2015-07-14-05-53-56](https://cloud.githubusercontent.com/assets/3839684/8661810/faf327ec-29ec-11e5-8e7e-cf3b6ca1e301.png)

**Comment by adonespitogo** [comment]
![screenshot from 2015-07-14 05 58 35](https://cloud.githubusercontent.com/assets/3839684/8661882/89263626-29ed-11e5-8dc3-8f7dead700ad.png)

**Comment by rajeshwarpatlolla** [comment]
Customisable classes added in new version v0.5.0

**Comment by mandadimuralidharreddy** [comment]
I am using v 0.6.0 facing same issue.any help

**Comment by rajeshwarpatlolla** [comment]
Try using the CSS classes i added and overwrite them as per your need. This will surely fix your issue.

**Comment by mandadimuralidharreddy** [comment]
thanks for your reply.which version 0.5.0 or 0.6.0?

**Comment by rajeshwarpatlolla** [comment]
Always use the latest version..

**Comment by mandadimuralidharreddy** [comment]
thanks now it working.the problem due to default  ionic popup word-wrap property set to breakword.
Another issue is  when I select month from drop down date are updating but month name not showing in dropdown menu.
