### ISSUE TITLE
Setting a date by choosing month -> day -> year doesnt work

### ISSUE THREAD

**Issue by aaronprojects** [rajeshwarpatlolla/ionic-datepicker#47]
Hey,

I have a problem setting dates:

1. open datepicker. Todays date is set (e.g. 2015-07-20)
2. change month (e.g. april)
3. change day (e.g. 10)
4. change year (e.g. 1988)

Month and day will be set correctly, but the year still is 2015. I also tested it with your demo and different variations. I have to set the day last, then it works.

**Comment by rajeshwarpatlolla** [comment]
I tested it multiple times. It is working fine at my end. 

Can you check the demo link once.
http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker

**Comment by aaronprojects** [comment]
Hey,
still not working for me! 

Tried it again with your demo:

1. opened the datepicker -> 21-july-2015
2. changed day to 22
3. changed year to 2016 -> day jumped back to 21
4. clicked on "set"

Expected result: 22-july-2016
Real result: 22-july-2015

Don't know what I am doin' wrong xD?! Sorry if this is a real stupid user mistake but I don't get it :D!

**Comment by rajeshwarpatlolla** [comment]
Thats not jumping. It is the today/s date. So where ever you go today's date will be marked by default. you should click on  the date to select any date. not just changing year. If you just change the year, it will give you today's date and selected year.

**Comment by aaronprojects** [comment]
So the user always has to select the day last? My tester didn't and this caused an issue in my app, that's why I'm asking. If you planned to do it that way, it's okay, I'll try to fix it on my own =)! Thanks for your answer!

**Comment by rajeshwarpatlolla** [comment]
Yeah, the current date in all the months and years will be shown by default.

**Comment by rajeshwarpatlolla** [comment]
This selected date and current date color issues have been fixed in the new version. Please use v0.6.0.

**Comment by aaronprojects** [comment]
Thanks a lot :)! Works fine!
