### ISSUE TITLE
Feature Request: Ability to use date instead boolean for disablePreviousDates and disableFuturesDates

### ISSUE THREAD

**Issue by mtpultz** [rajeshwarpatlolla/ionic-datepicker#48]
Great directive.  The ability to use a date for disablePreviousDates and disableFutureDates instead of a boolean so you could use two calendar directives and build a valid range.  Would allow the start date directive to use end date directive date as disableFutureDates, and end date directive to use the start date directive to as disablePreviousDates.  All sync'ed from a parent controller declaratively using controller $scoped members, so just need ability to set as a date.

**Comment by rajeshwarpatlolla** [comment]
All this functionality is in one directive only. It's just adding properties, to get those features.
