### ISSUE TITLE
Year Field becomes blank when past the end of year array

### ISSUE THREAD

**Issue by leonaburime** [rajeshwarpatlolla/ionic-datepicker#50]
Great work Rajesh.  This is beautiful.  I did have an issue though.

I restricted the years on the datepicker to only be this year in my own file(so it didnt get overwritten with any updates)...

var app = angular.module('ionic-datepicker');

app.service('DatepickerService', function () {

  var date = new Date();
  var current_year  = date.getFullYear();
  this.monthsList = ["January", "February", "March", "April", "May", "June", "July",
     "August", "September", "October", "November", "December"];
  this.yearsList = [current_year]; 
});

When this happens I can click past the end of 2015 but no year shows up. Attached is a picture of what I mean 

<img width="321" alt="screen shot 2015-07-26 at 9 21 46 pm" src="https://cloud.githubusercontent.com/assets/8000641/8898636/5bc2da7e-33dc-11e5-9d5a-6d23fcfc1b33.png">

Also is there a way to load this from an unminified source? Its virtually impossible to debug it any other way.

**Comment by rajeshwarpatlolla** [comment]
Currently it supports years from 1900 to 2100. If you wants to change this default feature, you can always use the un minified version, which you can see in the src folder of `ionic-datepicker` folder in side your lib folder or where ever it is installed.

**Comment by leonaburime** [comment]
Hi Rajesh,  I tried this and it doesnt solve the problem.  If you were to try it to - restrict years list to '2015' so the array looks like this ..

this.yearsList = [2015];

I'm sure you would find the exact same thing.  When clicking past the end of December the year field becomes blank

**Comment by rajeshwarpatlolla** [comment]
If possible, could you please attach the screen cast?

**Comment by leonaburime** [comment]
Hi Rajesh,

I attached a screencast in the first comment when I raised the issue. Are you not able to see it?

**Comment by rajeshwarpatlolla** [comment]
Its screen shot right? i Was asking about the screen cast, i mean screen recording.

**Comment by leonaburime** [comment]
Oh I dont think I have that capability.  My apologies.  If you restrict the yearsList to [2015] and simply click through all the months to the end of the year you can easily see what I am talking about though

**Comment by rajeshwarpatlolla** [comment]
This is because there is no next year.
