### ISSUE TITLE
Disable any Tuesday

### ISSUE THREAD

**Issue by happschinson** [rajeshwarpatlolla/ionic-datepicker#51]
Hi!

Is it possible to let's say disable any Tuesday, Wednesday and Friday?
So the datepicker will only accept Mondays, Thursdays, Saturdays and Sundays?

**Comment by rajeshwarpatlolla** [comment]
No, there is no such feature for now.

**Comment by justinobney** [comment]
this could perhaps be an overload to the disableDates option. Perhaps you could send in a function that will  get each date passed and determine if the date is enabled.

```js
function disableCertainDaysOfWeek(date){
  var TUE = 2;
  var WED = 3;
  var FRI = 5;
  return [TUE, WED, FRI].indexOf(date.getDay()) > -1
}

$scope.opts = {
  disabledDates: disableCertainDaysOfWeek
}
...
```

**Comment by rajeshwarpatlolla** [comment]
Thanks for your suggestion and code snippet @justinobney, I will try to implement this feature in the next release.

**Comment by rajeshwarpatlolla** [comment]
This is additional feature is not implemented in this component. But still you can specify the dates that you wish to disable. This is implemented  in the latest version of this component.
