### ISSUE TITLE
Set idate after ajax request

### ISSUE THREAD

**Issue by chrisbenseler** [rajeshwarpatlolla/ionic-datepicker#53]
How do i set idate attribute after an ajax request (and after the template gets loaded)?
If I have something like

MyService
.getSomeData()
.then(function(response)) {
   $scope.datepickerdate = response.date;
}

in my controller and

<ionic-datepicker idate="datepickerdate" ...

in my template, this datepickerdate is never set, because the idate attribute is "loaded" together withe the controller. In other words, I needed to set this attribute with a date that comes from my backend app.

**Comment by rajeshwarpatlolla** [comment]
Hi @chrisbenseler, In some cases, specifically in api calls, the view might not update with the returned value. If this is the case, may be you can use $apply. 
You can see <a href="https://www.google.co.in/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=$apply+in+angularjs">lot of posts</a>, which might help you.

**Comment by chrisbenseler** [comment]
hi @rajeshwarpatlolla 

I tried this

MyService
.getSomeData()
.then(function(response)) {
	setTimeout(function () {
		$scope.$apply(function() {
			$scope.datepickerdate = response.date;
		});
	}, 2000);
}

and the problem still happens (also, I tried to use $timeout instead of native setTimeout, no success too).

Debugging ionic-datepicker.js, I noticed some things:

scope has a ipDate attribute with the date from now, instead of those I set with idate attribute.

ipDate: Tue Aug 04 2015 07:51:25 GMT-0300 (BRT)

but __proto__ prints out "Invalid Date"

Even if I set a date in the $scope and pass it to idate, without any ajax call, like:

$scope. datepickerdate = new Date(2000, 10, 1);

the console says:

ipDate: Wed Nov 01 2000 00:00:00 GMT-0200 (BRST)
__proto__: Invalid Date

I think there are 2 different problems: one (the first I reported) is with the binding of data after the render of the element (it seems the ionin-datepicker sets the value of ipDate when it's created, instead of when user clicks to open it) and the other is with parsing dates.

**Comment by chrisbenseler** [comment]
hi @rajeshwarpatlolla

I tried this

MyService
.getSomeData()
.then(function(response)) {
  setTimeout(function () {
    $scope.$apply(function() {
    $scope.datepickerdate = response.date;
    });
  }, 2000);
}

and the problem still happens (also, I tried to use $timeout instead of native setTimeout, no success too).

Debugging ionic-datepicker.js, I noticed that inside element.on("click", function () { }) that scope.ipDate is null.
In line 193, there is:
refreshDateList(angular.copy(scope.ipDate));

console.log(scope.ipDate); prints "Tue Aug 04 2015 08:05:50 GMT-0300 (BRT)" instead $scope.datepicker's new value. It seems that there's something happening with the binding of the value after the ionic-datepicker is rendered.

I'll take a look further, if there's something I'm implementing wrong. Thanks for the help.

**Comment by rajeshwarpatlolla** [comment]
Please try with the new version `v0.7.0`

**Comment by vinothkbest** [comment]
destroy the datepicker inside the success & call again with beforeShowDay function outside the ajax function:
(Note: dynamicCalender fn is called when select dropdown in other select input)

var holidays = '{!! $holidays !!}';
   $( "#appmnt_date" ).datepicker({
            beforeShowDay: nationalDays,
            minDate: "+1D",
            dateFormat:"dd-mm-yy",     
            changeMonth: true,
            changeYear: true,
            maxDate: "+1D +3M",
            
   });
   var booked_dates = '';
   function dynamicCalender(){
      const service = jQuery("#service option:selected").val();
      jQuery.ajax({
         method : 'GET',
         url: `{{ url('filled-dates/${service}') }}`,
         async: false,
         cache: false,
         success : function(response){
            booked_dates = response.booked_dates
            console.log(booked_dates)
            
         }
      })
      $("#appmnt_date").datepicker("destroy");
          
   }
   $('#appmnt_date').datepicker({
         beforeShowDay: nationalDays,
   }); 
   function nationalDays(date) {
      var string = $.datepicker.formatDate('yy-mm-dd', date);

      if((date.getDay()==0 || date.getDay()==5 || date.getDay()==6) || holidays.indexOf(string)!=-1){
         if(date.getDay()==0 || date.getDay()==5 || date.getDay()==6){
            return  [!(date.getDay()==0||date.getDay()==5||date.getDay()==6), 'weekend-date'] 
         }
         return [holidays.indexOf(string) == -1, 'holidays'] 
      }
      else if(booked_dates.indexOf(string) != -1){
            return [booked_dates.indexOf(string) == -1, 'booked-dates'];
      }
      return [true, 'no-slots'];
   }


Please try this!
