### ISSUE TITLE
Automatically select the actual date without need to tap the date day

### ISSUE THREAD

**Issue by amrigo** [rajeshwarpatlolla/ionic-datepicker#54]
Hi !

Today when i do open the calendar the actual day is selected and it shows in gray background, and i know i need to tap into the actual day to select it.

If i did not choose a day and close the calendar, this error message is fired: "Please select a day" . Can we in turn modify this behaviour? if the user opens the calendar and select no day at all, the actual day will be the selected day ?

**Comment by rajeshwarpatlolla** [comment]
Yes, you are right. But i was thinking about those who wants to selects a date for sure. Let me keep this thing in my to do. 
And let me know your suggestion, which should help everyone using this component.

**Comment by amrigo** [comment]
Yes is not a big deal is just a feature, seems trivial but happens that users do not look at the button that already have the actual day, then they open the calendar, when they got back the date is not selected by default.

**Comment by amrigo** [comment]
Hi Rajeshwar

Hoepe everything is alright with you , again thank´s for the datepicker
plugin .

I just would like to point some issues i discover on android 4.5 already in
red on the image i atach

I upgrade to the latest version using bower

The month and year do no appear at the android device.

When in landscape the buttons appear out of the calendar box.

The calendar does not behave renponsive at all, some areas appear out of
the screen

I think these are easy ones to handle editing the css.

Just like to show you as a feedback of the project wich is a very good one.

Thank you and Best regards.
Ângelo Rigo



 +-------------------------------
    Ângelo Marcos Rigo
    http://www.u4w.com.br
  ------------------------------+

2015-08-04 11:19 GMT-03:00 Rajeshwar <notifications@github.com>:

**Comment by rajeshwarpatlolla** [comment]
Please use the new version i.e. `v0.7.0` This bug has been fixed.
