### ISSUE TITLE
View not updating when selecting month after prev month clicked

### ISSUE THREAD

**Issue by asue** [rajeshwarpatlolla/ionic-datepicker#55]
Hi Rajesh, great job!  I found an issue though and I am able to reproduce this on your demo.  Using the 2nd one where future dates are disabled.

1. Select January from the month select.
2. Click Prev month to go to December 2014.
3. Change the month select to January.
4. It seems the monthChanged event doesn't fire so the view doesn't update.
5. In the code, it still think it's December 2014 because click the Next month will go to January 2015 instead of February 2014 as expected.

**Comment by rajeshwarpatlolla** [comment]
Seems like this is an event issue. In the scenario you have mentioned, the event is not getting triggered.
