### ISSUE TITLE
Start and end date, opening without a button

### ISSUE THREAD

**Issue by gregor-srdic** [rajeshwarpatlolla/ionic-datepicker#56]
Hi, first thanks for your work. I have some suggestions. 

To me, it is more useful to be able to set start and end date, not only disable previous or future dates. For instance, I would like to enable user to choose any date from tomorrow to one year in the future.

Another suggestion is to enable adding and opening a date picker dialog without adding a button that displays the date. I've solved this by hidding a button and initiating onClick event with jquery but I guess it is not a proper angular approach.

**Comment by rajeshwarpatlolla** [comment]
Please use the new version i.e. `v0.7.0` This bug has been fixed.
