### ISSUE TITLE
Cannot disable today's date

### ISSUE THREAD

**Issue by kofronpi** [rajeshwarpatlolla/ionic-datepicker#58]
Hi,

I have two problems : 

1) 

I am not able to disable today's date in the datepicker:

```
$scope.disabledDates = [
     new Date()
];
```
Today's date can still be picked.

2) Because I do not want users to be able to select today's date, is there a way to remove the "today" button with a directive ?

Thank you for your help !

**Comment by rajeshwarpatlolla** [comment]
Please use the new version i.e. `v0.7.0` This bug has been fixed.

**Comment by kofronpi** [comment]
Thanks for your hard work !
