### ISSUE TITLE
After clicking today, clicking set returns an error

### ISSUE THREAD

**Issue by loomtronic** [rajeshwarpatlolla/ionic-datepicker#6]
If the first time you load the datepicker you click "Today" and then click "Set" I get the following:

![image](https://cloud.githubusercontent.com/assets/1706404/7553173/83a25846-f69a-11e4-9780-d481a7713940.png)

**Comment by rajeshwarpatlolla** [comment]
When you click on today it will just navigate to the current month. It wont select the date.  Again you have to click on the today's date to get it selected.
