### ISSUE TITLE
ios is selected not work

### ISSUE THREAD

**Issue by match08** [rajeshwarpatlolla/ionic-datepicker#61]
ios is selected not work

**Comment by rajeshwarpatlolla** [comment]
Could you please explain briefly.

**Comment by match08** [comment]
android is working，but ios is bug。when me selected date is not work，top blue date nothing。click set again click start is disable。

**Comment by rajeshwarpatlolla** [comment]
Still i didn't get your point. Please test this in your device rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker

**Comment by rajeshwarpatlolla** [comment]
Please use the same syntax as i mentioned in the description.
