### ISSUE TITLE
on iOS, seems to be an issue with disabled date cells and :hover styles

### ISSUE THREAD

**Issue by AbdellaToronto** [rajeshwarpatlolla/ionic-datepicker#62]
It seems as though there is an issue with disabling a date - where when you try tapping on this disabled date, the :hover style (which is a light blue colour) is applied to the cell, regardless of whether or not this cell is selectable. Maybe this is a feature, but the concern is this may confuse a user, letting them think this cell is selected.

To replicate, use modal version of datepicker, disable a date or date range, open up an app in iOS (simulator or device) and select this disabled date - you will see the light blue selected style applied, and it will persist until you click on another cell.

**Comment by rajeshwarpatlolla** [comment]
Hi @AbdellaToronto, The functionality is like this : The light blue is different from the dark blue. So for disabled dates it will show light blue color and for enable dates it will show dark blue color. There some difference between the disabled and enabled dates.

**Comment by AbdellaToronto** [comment]
I think I understand that, so this isn't a bug so much as it's a feature - but is there any value in letting a user know -which- date they tapped on if it's disabled? I'm not sure. There might actually be some functionality here I am not aware of though, so you'll have to take this with one, or many grains of salt, but I did have to modify this so that this light blue styling was not visible when tapping on a disabled date as per a client's request. 

I just want to say that I do very much enjoy this component though! I think it's written well and looks great, I hope I don't come off as being too nit picky.

**Comment by rajeshwarpatlolla** [comment]
You are right. May be this can come under a feature. And thanks for your suggestion.
