### ISSUE TITLE
February 2015 Starts on Monday, but should start on Sunday. March Ends on Wednesday, but should end on Tuesday.

### ISSUE THREAD

**Issue by AbdellaToronto** [rajeshwarpatlolla/ionic-datepicker#63]
In the datepicker, I'm not sure how this is happening, but there is a weird date issue for February and March - if you check these images (on your demo) you'll see it.

### January-February 2015, missing day
<img width="918" alt="screen shot 2015-08-24 at 3 45 37 pm" src="https://cloud.githubusercontent.com/assets/3640896/9450563/6140374c-4a77-11e5-8daa-302cd425201c.png">
<img width="883" alt="screen shot 2015-08-24 at 3 45 07 pm" src="https://cloud.githubusercontent.com/assets/3640896/9450562/613f3b26-4a77-11e5-965b-b95fd889a646.png">

### March-April 2015, overlapping day
<img width="909" alt="screen shot 2015-08-24 at 3 45 49 pm" src="https://cloud.githubusercontent.com/assets/3640896/9450564/6140e9e4-4a77-11e5-9f12-67cd5fd0f390.png">

<img width="925" alt="screen shot 2015-08-24 at 3 45 58 pm" src="https://cloud.githubusercontent.com/assets/3640896/9450565/61436f3e-4a77-11e5-9565-25d47441daf3.png">

**Comment by rajeshwarpatlolla** [comment]
Thank you so much for finding this bug. There was some issue, if we use Monday as the first day of the week. This has been resolved in the new version [v0.9.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v0.9.0)
