### ISSUE TITLE
Clicking on the empty cells sets dates to NaN

### ISSUE THREAD

**Issue by tsungting** [rajeshwarpatlolla/ionic-datepicker#65]
If the user clicks on the empty cells rapidly, the dates on top will be set to empty dates.

<img width="452" alt="screen shot 2015-08-25 at 5 53 24 pm" src="https://cloud.githubusercontent.com/assets/5641819/9480635/408f2f54-4b52-11e5-8ea5-f41d425b3ddf.png">

**Comment by rajeshwarpatlolla** [comment]
Which version of this component you are using?

**Comment by rajeshwarpatlolla** [comment]
Issue resolved. Code pushed to master branch. Please take a look at [this commit](https://github.com/rajeshwarpatlolla/ionic-datepicker/commit/c5fa80700864848827ccaf719b900b95b259b093)
