### ISSUE TITLE
Setting inputDate

### ISSUE THREAD

**Issue by efishman15** [rajeshwarpatlolla/ionic-datepicker#66]
Hello,
I'm using your great date picker (in popup mode).
I think there are 2 bugs I discovered.

1. If not specifying "inputDate" at the creation of the object - Setting the inputDate of the control later at "run time" - somewhere in the controller code (view beforeEnter for instance) does not do any effect - it stays on "today" (both in the SelectedDateFull and in the calendar) - I took a look at the code - I think the following lines:

      //Setting the input date for the date picker
        if (scope.inputObj.inputDate) {
          scope.ipDate = scope.inputObj.inputDate;
        } else {
          scope.ipDate = new Date();
        }
        scope.selectedDateFull = scope.ipDate;

should be moved to the "click" event - to be set just before the view pops up.

2. Even if setting the InputDate at the object creation - the selectedDateFull gets updated - but the calendar still stands on today.

I'll appreciate your fixes - or tell me if I'm doing anything wrong.

Thanks,
Eddy

**Comment by rajeshwarpatlolla** [comment]
Could you please provide a video link or a screenshot of this issue?

**Comment by efishman15** [comment]
Yes - I have set up a full reproduce at codepen:
http://codepen.io/efishman/pen/EVxPyN

Go to the "Check In" menu.
Please see my comments in the CheckIn controller code.

Eddy

**Comment by rajeshwarpatlolla** [comment]
I tested the codepen. There was an issue with the css. Please add this in you css file.

````
.item-select select{
  padding:0 !important;
}
````

**Comment by efishman15** [comment]
I added this to the css in the code pen - how does it solve the problem?
I don't see any change...

**Comment by rajeshwarpatlolla** [comment]
Check this. i forked your codepen. http://codepen.io/rajeshwarpatlolla/pen/rONxqy

**Comment by efishman15** [comment]
The css changes indeed solve the stretching issue - but do not solve the INITIAL BUG - 
I see you have added the line:
  $scope.myBirthday = new Date(1968,10,26); 
just before the date picker initialization - but I cannot do that - as explained in my comments - the date should be DYNAMIC - in my real app - it is being read from a database via API.

I think -as I mentioned in the beginning - you only INITIALIZE the date picker date - at the beginning of your directive - you should update the date picker (ipDate) value again (from the inputDate) on the CLICK event.

**Comment by rajeshwarpatlolla** [comment]
It will take whatever the value you pass into the input object. So you can't pass the date after the datepicker is called. This is not the functionality provided by this datepicker.

**Comment by efishman15** [comment]
But even if I re-initialize the entire object in the "beforeEnter" event - with the value set before - it still does not work.

**Comment by rajeshwarpatlolla** [comment]
Before invoking the datepicker you should make the api call to get the date from the server. And then you will be able to invoke the datepicker with the date returned by the server. But after invoking the date picker its not possible to re assign the value to the datepicker input object.

**Comment by efishman15** [comment]
I understand what you're saying - but I can't make this work.
Please look at my modified codepen:
http://codepen.io/efishman/pen/EVxPyN

The click won't even popup the date picker.

**Comment by rajeshwarpatlolla** [comment]
It's bcz of `$ionicView.beforeEnter`. Once you enter the page where you need the date from the server just make the call on entering the page and set the value to the datepicker object. Then if the user tries to click on the datepicker then it will work fine.

**Comment by efishman15** [comment]
I changed that:
http://codepen.io/efishman/pen/EVxPyN

Still does not work - this was my code from the beginning - the value is set only once - as the view is created.

**Comment by rajeshwarpatlolla** [comment]
Still u r using the same `$ionicView.beforeEnter`. I already told you that when you enter the `check-in` page then make the api call to get the date from the server, then if the user clicks on the date picker you already have the date with you, which you have received from the server, so that u can assign that to the input object.

**Comment by efishman15** [comment]
When I go to the "check in " page in my real app - I am NOT RELOADING the view each time
( e.g $state.go("app.checkin", {}, {reload : false})
Thus, the code put in the controller does not get executed each time, rather than beforeEnter/enter/afterEnter events are meant only to change the model data (retrieve via api from server) - and not RE-CREATE the view each time - which is "expensive" in performance for me - my view is very complicated.

**Comment by franciswagner** [comment]
I'm having similar problem. I have a service that returns the date to be placed in the inputDate, but it shows the error message "Cannot read property 'titleLabel' of undefined".

**Comment by aheadzen** [comment]
I had the same problem, and here's how I solved it.

The directive code is executed in the regular flow and doesn't stops for any $http calls thus it always takes default values for datepicker. To make it run after $http request we should wrap the directive within a div and use ng-if to control execution.

```html
<div ng-if="loadingDone">
          <ionic-datepicker input-obj="birthdayDatePicker">
            <button class="button button-block button-positive">{{myBirthday| date:'dd-MM-yyyy'}}
            </button>
          </ionic-datepicker>
 </div>
```

and in controller -
```javascript
$scope.loadingDone = false;
   $http.get('http://www.example.com/', { params: {"country_code":"IN","s":"hjh"} }).
  then(function(response) {
    $scope.birthdayDatePicker = {
      titleLabel: "Choose your birthday",
      setButtonType: 'button-assertive',
      mondayFirst: false,
      templateType: 'popup',
      modalHeaderColor: 'bar-positive',
      modalFooterColor: 'bar-positive',
      from: new Date(), //do not allow past dates
    inputDate : new Date(2017, 11, 26),
      callback: dateCallback
    }; 
     $scope.loadingDone = true;
  }, function(response) {
    // called asynchronously if an error occurs
    // or server returns response with an error status.
  });
```

**Comment by rajeshwarpatlolla** [comment]
Thanks for sharing this @aheadzen.

**Comment by oumayma-ltaief** [comment]
Hello, 

I'm using your date picker in popup mode.
I have a problem when adding two buttons right and left the date picker ; any click on those <a> displays the popup, can you help me please this is the code:

<div class="list list-inset">
             <label class="item item-input">
                 <img alt="" src="img/calender.png"> 
                 <span class="input-label">&nbsp;Data:</span>
                 <a><i class="ion ion-chevron-left balanced"></i></a>&nbsp;&nbsp;&nbsp;
                 <ionic-datepicker input-obj="datepickerObject">
                   <button class="button button-small button-light dark-date">
                      {{datepickerObject.inputDate | date:'dd - MM - yyyy'}}
                   </button>
                 </ionic-datepicker>
                 &nbsp;&nbsp;&nbsp;<a><i class="ion ion-chevron-right balanced"></i></a>
             </label>
         </div>
