### ISSUE TITLE
The weekDaysList is shifting when it is customized

### ISSUE THREAD

**Issue by aleleux** [rajeshwarpatlolla/ionic-datepicker#68]
Hi,

First of all, thanks a lot for your great work !

I found a problem with the weekDaysList. I use you DatePicker to create several events, and each time I set a new date the weekDays are shifting one day to the left.

The first time I use it the list goes from Monday to Sunday (I set mondayFirst to true), the second from Tuesday to Monday, the next one from Wednesday to Tuesday etc.

The dates in the calendar stay in the good columns, only the  letters above are shifting (so the second day I have the Tuesday letter above the Monday column).

I don't have this issue with the default weekDaysList, only when I customized it. I encounter this on both device and ionic serve.

Do you have an idea of where it could come from ? I'll work on it and keep you updated if I find something.

Thanks.

**Comment by rajeshwarpatlolla** [comment]
Could please share a video link if possible?

**Comment by punknroll** [comment]
I found out that error occurs if you have two datepickers using the same variable as weekDaysList and use the option mondyFirst:true because variables are passed by reference.

Configuration to reproduce:
http://pastebin.com/FgTW28rZ

I simply copied the object.

```javascript
var myList = ['S', 'S', 'M', 'T', 'W', 'T', 'F']; 
$scope.startDatePickerObject = {
    weekDaysList: myList
}
$scope.endDatePickerObject = {
    weekDaysList: angular.copy(myList)
}
```

**Comment by rajeshwarpatlolla** [comment]
Yes, if you use more than one datepicker then you need create those many variables.
