### ISSUE TITLE
Selecting year on iOS not working. Also Today button not picking date

### ISSUE THREAD

**Issue by jeudyx** [rajeshwarpatlolla/ionic-datepicker#69]
When you select the year in iOS, nothing happens. You need to tap outside the select component to get the year select reflect in the picked date.

![image](https://cloud.githubusercontent.com/assets/1454280/9539492/7b20a95e-4d0f-11e5-8fea-056ffb2bd255.png)

Also, when you select the Today button, the date gets picked in the calendar, but not in the selected date, which, for me, was the expected behaviour:

![image](https://cloud.githubusercontent.com/assets/1454280/9539508/b26d5434-4d0f-11e5-868f-d05f2b83f062.png)

Otherwise, great component :-)

**Comment by rajeshwarpatlolla** [comment]
I have tested this in iPhone5 and android devices too. It is working fine. I have tested both the app and the website demo page. Please test the [demo web page](rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker) in your mobile. And also test this app in ionic view (App id : **34590d94**). In both the ways it's working fine.

**Comment by jeudyx** [comment]
You are right, your app works fine on my iPhone 5. Looks like my problem when picking the year, on my app, is that somehow the "Done" button is not shown.

**Comment by rajeshwarpatlolla** [comment]
You can have a look at these links. Might help you a bit. 
https://github.com/driftyco/ionic-plugin-keyboard
https://github.com/driftyco/ionic-plugin-keyboard/issues/97

**Comment by jeudyx** [comment]
You are absolutely right, the second link provided the answer. The problem is that I had this:

cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);

which was hiding the "Done" button among other things.

Thanks!

**Comment by rajeshwarpatlolla** [comment]
Thanks for using this plugin @jeudyx
