### ISSUE TITLE
Screens are taking more time to load when compared to previous versions.

### ISSUE THREAD

**Issue by girishsunkeri** [rajeshwarpatlolla/ionic-datepicker#70]
Great Job Rajesh. 

Just wanted to point out that my pages are loading bit slower after updating my code to the latest version.

**Comment by rajeshwarpatlolla** [comment]
You only need to use one single file i.e. `ionic-datepicker.bundle.min.js` which is 16.552 kB now. I don't think this will affect the performance considerably. May i know how are you saying that your app's performance is become slow?

**Comment by girishsunkeri** [comment]
I have included only one file i.e ionic-datepicker.bundle.min.js. I have a side menu and whenever I select any option, it takes few milliseconds(based on the type of device) to display the page. If I comment out the date picker html, page loads without any delay.

**Comment by rajeshwarpatlolla** [comment]
Bit strange. It also depends on the device too. By the way what you are commenting? The whole html page where you are using this component? or something else?

**Comment by girishsunkeri** [comment]
Yes, I'm testing it on Xperial L(4.2.2) and Nexus 5(lollipop). On Nexus 5 it's fast but I can still feel the lag. I'm commenting out two date picker elements i.e. <ionic-datepicker>. To be specific, this is the page https://github.com/girishsunkeri/SimpleExpenseManager/blob/master/www/templates/report.html

**Comment by rajildavda** [comment]
I agree with girish.  Using datepicker object delays page loading.  In browser delay is more (approx 2-3 seconds) but on actual device,  the delay is negligible.

**Comment by mubasshir** [comment]
fiinally i'm not alone. In iphone6 is delay of 1 second, in 5s 2-3 sec but in iphone4 is upto 5sec. I guess its drawing alot of elements or may be a lot of loops. 

But its damn slow, clients are complaining to me

**Comment by rajeshwarpatlolla** [comment]
Even i tested in iphone devices, but it's not that too delay.

**Comment by panasandu** [comment]
I have the same problem with performance in pages when datepicker is used

**Comment by milen-3web** [comment]
I have the same problem guys...
