### ISSUE TITLE
TypeError: Cannot read property 'titleLabel' of undefined

### ISSUE THREAD

**Issue by shieer** [rajeshwarpatlolla/ionic-datepicker#71]
Help!  
I keep getting this error. 

in javascript:
```
$scope.startDatePickerObject = {
            titleLabel: 'Select Date', //Optional
            todayLabel: 'Today', //Optional
            closeLabel: 'Close', //Optional
            setLabel: 'Set', //Optional
            setButtonType: 'button-assertive', //Optional
            todayButtonType: 'button-assertive', //Optional
            closeButtonType: 'button-assertive', //Optional
            inputDate: new Date(), //Optional
            mondayFirst: true, //Optional
            templateType: 'modal', //Optional
            modalHeaderColor: 'bar-energized', //Optional
            modalFooterColor: 'bar-energized', //Optional
            from: new Date(2012, 8, 2), //Optional
            to: new Date(2018, 8, 25), //Optional
            callback: function(val) { //Mandatory
                 startDatePickerCallback(val);
            }
        };

        var startDatePickerCallback = function(val) {
            if (typeof(val) === 'undefined') {
                console.log('No date selected');
            } else {
                $scope.startDatePickerObject.inputDate = val;
            }
        };
```

In html:
```
<ionic-datepicker input-obj="startDatePickerObject">
                        <button class="button button-block button-energized" id="dateButton">
                            {{startDatePickerObject.inputDate | date:'dd - MMMM - yyyy'}}</button>
                    </ionic-datepicker>
```

**Comment by rajeshwarpatlolla** [comment]
Where is the error?

**Comment by shieer** [comment]
@rajeshwarpatlolla  i got this "TypeError: Cannot read property 'titleLabel' of undefined"

**Comment by rajeshwarpatlolla** [comment]
Could you please try removing the optional properties and try once?

**Comment by shieer** [comment]
yes, I tried, and it still show that error, which is weird.

**Comment by rajeshwarpatlolla** [comment]
Please have a look at the example [here](rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker). It is working fine. I am using the same code here too. And also could you please try using the files from the `src` folder once instead of the dist folder.

**Comment by shieer** [comment]
@rajeshwarpatlolla that link got 404, if i use the files from src, which file should i include? 
there are : 
```
ionic-datepicker.app.js
ionic-datepicker.directive.js
ionic-datepicker.service.js
```

**Comment by rajeshwarpatlolla** [comment]
All the files. And also you have to change the path for the template inside the directive file.

**Comment by tsungting** [comment]
When I try to run it from the source, I am missing the module `ionic-datepicker.templates`, do you know where I find the module?

**Comment by rajeshwarpatlolla** [comment]
Remove that dependency from the `ionic-datepicker.app.js` file

**Comment by rajildavda** [comment]
One of the reason could be..  you are creating "startDatePickerObject" inside "$ionicView.enter".  This throws "Cannot read property 'titleLabel' of undefined" error due to object is not created yet and html tries to access this object properties.  To solve this i created date picker objects outside "$ionicView.enter".  

See below code:

$scope.fromDateObjPicker = UtilitySevice.getDatePickerObject('From Date', null, fromDatePickerCallback);
	$scope.toDateObjPicker = UtilitySevice.getDatePickerObject('To Date', null, toDatePickerCallback);

	$scope.$on('$ionicView.enter', function() {
		ActivityLogService.getActionQueryData().then(function (data) {
			$scope.queryData = data;
			$scope.fromDateObjPicker.inputDate = new Date($scope.queryData.fromDate);
			$scope.toDateObjPicker.inputDate = new Date($scope.queryData.toDate);
			//$scope.queryData.fromDateObj = new Date(data.fromDate);
			//$scope.queryData.toDateObj= new Date(data.toDate);
		});
	});

**Comment by rajeshwarpatlolla** [comment]
You are correct @rajildavda

**Comment by gimox** [comment]
same problem her but no solution found!

**Comment by rajeshwarpatlolla** [comment]
You are trying to do something after the DOM rendered. This component needs every thing before the directive is called.  Few are using trying to use `$ionicView.enter`, which will be called after the directive is called. So if you want to get rid of this, you need to prepare the object before the call of `$ionicView.enter`.

**Comment by franciswagner** [comment]
I am having the same problem. I have a service that returns the date to set the inputDate, but I get the error message "Cannot read property 'titleLabel' of undefined".

**Comment by rajeshwarpatlolla** [comment]
Please check the description i have mentioned in the repo. I don't have any issues with this component. I have tested this in multiple devices and browsers. Even so many people using it, without any issues. There might be something wrong in the way you are trying to use it. Few are trying to use after the DOM has rendered and few are trying to use in `$ionicView.enter`. The object should be available before the page loads, where you are using this component. Please have a look at the description once again and use as per the description.
