### ISSUE TITLE
Select wrong month

### ISSUE THREAD

**Issue by chompunut** [rajeshwarpatlolla/ionic-datepicker#72]
At [the demo] (http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker) 
At the first time, it displays today date for example August 31, 2015. 
I want to change the month to 'April' but after I selected, the month dropdown display 'May' instead.

It happens sometime. You have to refresh the page and try to select 'April' again.

**Comment by rajeshwarpatlolla** [comment]
I am not facing this issue. Could you please let me know the exact steps, you followed? And one thing i wish to let you know is, after changing the month, you need to select a date in that month to get it reflected.

**Comment by chompunut** [comment]
I think it has problem when you select the date '31'. 

1. Open the demo
2. Select the date August 31 (or July 31 or December 31)
3. Click 'Set' button
4. Click date picker button again to select month 'April'
5. The month field display 'May' instead of 'April'

This occurs on both modal and popup.

**Comment by rajeshwarpatlolla** [comment]
In some rare cases the dropdown ng-change event is not triggering. It's weird.

**Comment by S4mu3l3P** [comment]
I have the same issue in the demo. If I select the day 31 of a random month, and then I select the next month, this one is always skipped and the next of the next month is shown.

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
