### ISSUE TITLE
Date text is not showing on button

### ISSUE THREAD

**Issue by DharmendraVaishnav91** [rajeshwarpatlolla/ionic-datepicker#73]
Before clicking the current date is not showing on the ion-date picker button and same problem occurred after selecting any date.

**Comment by rajeshwarpatlolla** [comment]
Can you show me your html and js code where u r using this component?

**Comment by DharmendraVaishnav91** [comment]
Html code snippet 
`<ionic-datepicker input-obj="datepickerObjectPopup"> <button class="button button-block button-positive"> </button> </ionic-datepicker>`

Js code snippet is
`var disabledDates = [
      new Date(1437719836326),
      new Date(2015, 7, 10), //months are 0-based, this is August, 10th!
      new Date('Wednesday, August 12, 2015'), //Works with any valid Date formats like long format
      new Date("08-14-2015"), //Short format
      new Date(1439676000000) //UNIX format
    ];
    var monthList = ["Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"];
    $scope.datepickerObject = {};
    $scope.datepickerObject.inputDate = new Date();

    //ionic date-picker implementation
     var datePickerCallbackPopup = function (val) {
      if (typeof(val) === 'undefined') {
        console.log('No date selected');
      } else {
        $scope.datepickerObjectPopup.inputDate = val;
        console.log('Selected date is : ', val)
      }
    };
    $scope.datepickerObjectPopup = {
     titleLabel: 'Ionic-Datepicker', //Optional
      todayLabel: 'Today', //Optional
      closeLabel: 'Close', //Optional
      setLabel: 'Set', //Optional
      errorMsgLabel : 'Please select time.', //Optional
      setButtonType : 'button-assertive', //Optional
      modalHeaderColor:'bar-positive', //Optional
      modalFooterColor:'bar-positive', //Optional
      templateType:'popup', //Optional
      inputDate: new Date(), //Optional
      mondayFirst: true, //Optional
      monthList:monthList, //Optional
      from: new Date(2014, 5, 1), //Optional
      to: new Date(2016, 7, 1), //Optional
      callback: function (val) { //Optional
        datePickerCallbackPopup(val);
      }
    };
    `

**Comment by rajeshwarpatlolla** [comment]
In your HTML, some where please specify, where you want to show the date. Please have a look at the description.

`
<ionic-datepicker input-obj="datepickerObject">
  <button class="button button-block button-positive"> {{datepickerObject.inputDate | date:'dd - MMMM - yyyy'}}</button>
</ionic-datepicker>
`

This is how i mentioned there. Your code does not have any thing like `{{datepickerObject.inputDate | date:'dd - MMMM - yyyy'}}`, then you can't expect the date to show there right?

**Comment by DharmendraVaishnav91** [comment]
I did silly mistake.
Thanks @rajeshwar-fissionhq
