### ISSUE TITLE
CSS problems

### ISSUE THREAD

**Issue by WendellAdriel** [rajeshwarpatlolla/ionic-datepicker#76]
Hello, I had a problem customizing the CSS of some classes described in the README.md and I think it's because in some places you put "!important" and even when I put "!important" my customization don't take effect. Maybe I'm missing something, but I think it's better a plugin like yours don't use "!important".

**Comment by aaronprojects** [comment]
Same here. Had to change some styles in the library code which is really no good idea but it was the only way my wanted styles worked.

**Comment by rajeshwarpatlolla** [comment]
@aaronprojects, could you please let me know what are those classes you have modified in the source files, so that it will be easier for me to fix this issue in the next version?

**Comment by aaronprojects** [comment]
".date_selected" is the one which can't be overwritten because of the !important. ".color_blue" also uses !important. Maybe you'll find another way to set the color without using !important.

**Comment by mainalikishan** [comment]
+1

**Comment by rajeshwarpatlolla** [comment]
Issue resolved. Code pushed to master branch. You can check [this commit](https://github.com/rajeshwarpatlolla/ionic-datepicker/commit/6e634f8639f31acb93666730a90e37601cc35dbc)
