### ISSUE TITLE
Fails in an ion-modal-view

### ISSUE THREAD

**Issue by kudeiro** [rajeshwarpatlolla/ionic-datepicker#77]
The component works right in a regular ion-view, but if i try to open it from an ion-modal-view, it always give the error "Cannot read property 'titleLabel' of undefined". An ion-modal-view uses the scope of the parent ion-view, and i declare the $scope.datepickerObject in the parent ion-view controller.

**Comment by rajeshwarpatlolla** [comment]
It does not use a separate scope. If you look at the [example](rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker), it is working fine. You might be using something different way.

**Comment by kudeiro** [comment]
the link "example" gives 404

**Comment by rajeshwarpatlolla** [comment]
Check this link, it's working fine. http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker

**Comment by kudeiro** [comment]
sorry i have not explained well. I mean if i open the calendar (the calendar can be modal or popup) from an ion-modal-view, not opening the modal version of the calendar from a ion-view.
So i have an ion-view, i open an ion-modal-view from it, and then i open a calendar that is in the ion-modal-view

**Comment by rajeshwarpatlolla** [comment]
So you are saying that you are trying to use this component inside a modal instead of a page. Am i right?

**Comment by kudeiro** [comment]
yes

**Comment by rajeshwarpatlolla** [comment]
Yes, in that case the scopes will be different. And also modal over a modal doesn't look good. So you can try using it in a page. That's how this component is implemented, and it will work fine if you do so..

**Comment by kudeiro** [comment]
the previous version i used (from May) worked right in a modal

**Comment by rajeshwarpatlolla** [comment]
Oh, which version you used? If that would have worked fine, you may try using that version and give it a try once.

**Comment by kudeiro** [comment]
i revised the code but i cant' find the version, is one of the firsts (or even the first). The current version is better, but i need to use it in a modal view (a search modal view), so i go back to the previous version

**Comment by rajeshwarpatlolla** [comment]
You may try it in a page instead of a modal.
