### ISSUE TITLE
 is  date range piker scheduled?

### ISSUE THREAD

**Issue by aoslee** [rajeshwarpatlolla/ionic-datepicker#78]

**Comment by rajeshwarpatlolla** [comment]
Could you please explain it?

**Comment by aoslee** [comment]
@rajeshwarpatlolla: 
   Hi!Thanks for your reply.
  You can visit http://www.daterangepicker.com/.
                                        regards.

**Comment by rajeshwarpatlolla** [comment]
This component does not support such feature. But you can specify the starting and the ending dates for this component.

**Comment by aoslee** [comment]
@rajeshwarpatlolla : 
 Yes ,I understand that you say.I want to know if you have a plan for this feature?

**Comment by rajeshwarpatlolla** [comment]
As of now i don't have any plans for that particular feature. I have plans for improving the existing component only, in terms of bug fixes.
