### ISSUE TITLE
need release no uglify js

### ISSUE THREAD

**Issue by thm1118** [rajeshwarpatlolla/ionic-datepicker#79]
when i gulp build my app , i have to uglify all concat js files with my app js , but if one of js file is already uglified, it will spend more time , even 3 minutes

**Comment by rajeshwarpatlolla** [comment]
In that case, you can use the un minified version in your app from the `src` folder. If you wish to do so, all you need to do is remove `ionic-datepicker.templates` dependency from the `ionic-datepicker.app.js` file and also change the path of the `ionic-datepicker-popup.html` and `ionic-datepicker-modal.html` in the `ionic-datepicker.directive.js`.

**Comment by thm1118** [comment]
:), if i have to modify datepicker's src,  it is better to modify gulpfile with adding new task to build no uglify releas ?

**Comment by rajeshwarpatlolla** [comment]
I just wanted to let you know the ways how we can achieve this issue. So as you suggested, modifying the ulp tasks makes sense. You can go with that approach.

**Comment by thm1118** [comment]
thanks, but i want upgrade your datepicker when new release

**Comment by rajeshwarpatlolla** [comment]
You can do that. it won't have any conflicts with your gulp tasks right?

**Comment by thm1118** [comment]
a special task, :) , anyway , thanks your  create work and response so soon

**Comment by rajeshwarpatlolla** [comment]
You are welcome.
