### ISSUE TITLE
Not able to pass values to parent scope!!

### ISSUE THREAD

**Issue by rijine** [rajeshwarpatlolla/ionic-datepicker#8]

**Comment by rajeshwarpatlolla** [comment]
You can access in your controller from which you are using this component. From controller i think you can manipulate how ever you need.

**Comment by rijine** [comment]
Consider this case:
Added one more line in html
<button class="button button-block button-positive" ng-click="showDate()"> Show Dte </button>

added one function in controller
...
$scope.currentDate = new Date();
...
//new Block
$scope.showDate = function() {
  alert($scope.currentDate);
}

here alert always printing new Date only...y?

**Comment by rijine** [comment]
Its not updating parent controller $scope.currentDate

**Comment by rijine** [comment]
Heyyy...Its working..  I was trying using $scope.currentDate..
But its working with this.currentDate
Thanks,
Good Job @rajeshwarpatlolla

**Comment by anshulklr** [comment]
@rijine how to use the this, to get the value updated in the parent controller?

**Comment by rajeshwarpatlolla** [comment]
Thank you @rijine.

**Comment by anshulklr** [comment]
Can u help me in this, because it is not showing the selected value.

**Comment by rijine** [comment]
@anshulklr  for example your html has idate="currentDate"  within tag. In controller declare a variable like { var vm=this;  vm.currentDate=new Date(); } Try this and let me know if u face any problem

**Comment by anshulklr** [comment]
@rijine dude i'm still unable to do this,
                  idate="from_date"

in the controller
        var check=this;
        check.from_date= new Date();
now i can't see the date which earlier comes

**Comment by rijine** [comment]
can u share ur code in plunkr?

**Comment by anshulklr** [comment]
the code is too big , that i can't share everything, but as explained by @rajeshwarpatlolla  i did the same, i'm getting the date on the view but if i check by console.log(), it gives the right now date ie the value is not updating over there

**Comment by rijine** [comment]
how many controllers u r using

**Comment by anshulklr** [comment]
http://collabedit.com/fb5qw
come to this link

**Comment by rijine** [comment]
yes..!!

**Comment by rajeshwarpatlolla** [comment]
Call back function is added in `v0.3.0`. Please install this version to get the correct values in to the controller.
