### ISSUE TITLE
possible to set custom year list for every date picker?

### ISSUE THREAD

**Issue by nicon-dev** [rajeshwarpatlolla/ionic-datepicker#83]
Hi!

I have two datepicker, one for an event and one for a birthdate.
I do not want to show so much years for the event but it`s needed for the birthdate.

Is this possible?
I saw there is a "monthList" in the directive source.
Can I expose it to the angular code in any way?

Thanks!

**Comment by rajeshwarpatlolla** [comment]
Currently i am using the list for months and year from a service in this component itself. But you can customize the Month's list and the Day's list. But for now, there is no such feature to show only a few years, but still you can disable those years, which you think not need.
