### ISSUE TITLE
set validation for 2 date picker on same page that selection of 1st date picker input date user can not select previous date on 2nd date picker

### ISSUE THREAD

**Issue by kite57** [rajeshwarpatlolla/ionic-datepicker#85]
Hi I have 2 date picker on page.
1)i am using 1st date picker to set from date e.g 23/09/2015
2)based on this selection
3)now when i am click on 2nd date picker
4)user can't able to select date that is previous from 23/09/2015
5)user only select greater date from 1st datepicker selected date

**Comment by rajeshwarpatlolla** [comment]
That depends on the object you are passing. you need to use two different objects for two different date pickers. And there is an option to disable past and future dates. Cross check them.

**Comment by kite57** [comment]
Hello rajesh,

Thank you for the reply.

As u said i have already taken 2 date picker with 2 different object
1)datepickerObjectFromDate
2)datepickerObjectToDate

Set 1st datepicker date to 23-09-2015
after
now i am setting second date picker date.

now how i can restric user to not select past date from date selected date from date picker-1
is there any event that set 2nd datepicker from value when select date from1st datepicker

also i have try to set 2nd datepicker from date from callback of 1stdatepicker.
but still can't able to find out the solution.

**Comment by kite57** [comment]
Hello Rajesh,

Is there anything wrong on my implementation scenario as per above comment? and this kind of feature is available on this plugin?

**Comment by rajeshwarpatlolla** [comment]
You should dynamically create the second datepicker component. Because when you have two directives in the same age, it expects all the data available before the DOM loads. So if you wish to load the second based on the first datepicker callback, you need to create the element dynamically.

**Comment by omer-r** [comment]
Hi,
In my app I have a pickup date and a delivery date (which has to be at least one day after and at most 10 days after pickup).
I wrapped the second date picker with my own directive to reload every time pickup date changes.
In my DatePickService I have 2 methods 
onPickupDateChange(newDate) and getDeliveryDatePickerOptions()

Here's the directive, I think the rest is less complicated.
```
/*
selectDateWrapperDirective.js
*/
(function () {
    'use strict';
    angular
        .module('myApp')
        .directive('myDatePickerWrapper', [
            'DatePickService',
            '$compile',
            myDatePickerWrapper
        ]);

    function myDatePickerWrapper(DatePickService, $compile){
        return {
            restrict: 'E',
            scope: false,
            link: function(scope, elem, attrs) {
                console.log('link');
                function generateDeliveryDatePicker(){
                    scope.data = DatePickService.getDeliveryDatePickerOptions();
                    var htm =
                        '<ionic-datepicker input-obj="data">'+
                        '<button class="button button-block"> {{vm.deliveryDate | date:"dd/MM/yy"}}</button>'+
                        '</ionic-datepicker>';
                    var compiled = $compile(htm)(scope);
                    elem.replaceWith(compiled);
                    elem = compiled;
                }

                generateDeliveryDatePicker();

                scope.$watch('vm.pickupDate', function(newVal) {
                    generateDeliveryDatePicker();
                });
            }
        }
    }
})();
```

**Comment by kite57** [comment]
Hello,

Thanks a lot for your reply, and thank you for the help, trully
appriciated. Will try and let you know about this implementation.

Thank you,
Keyur Savaliya

**Comment by dmastag** [comment]
Hi @rajeshwarpatlolla ,
I have the same use case. Here is my codepen
http://codepen.io/dmastag/pen/QjdeyY

So if I change the inputDate or the from Value of the second datepicker (TOdatepickerObject), shouldn't the date and from values have changed? How would I achieve this?

I was looking at @omer-r solution, though great but I need to change the htm for every occurrence which is not very ideal.

Hoping for your advise.

**Comment by renekorss** [comment]
With my PR, you could do it like this:

````javascript
$scope.datepickerObjectFrom = {
  callback: function (val) {
    if (typeof(val) !== 'undefined') {
      $timeout(function () {
        $scope.datepickerObjectTo.from = new Date(val);
      }, 0);
    }
  }
};

$scope.datepickerObjectTo = {
  callback: function (val) {
    if (typeof(val) !== 'undefined') {
      $timeout(function () {
        $scope.datepickerObjectFrom.to = new Date(val);
      }, 0);
    }
  }
};
````

@dmastag I made minor changes to your codepen. Set both to update each other `from` and `to` dates and included my fork bundle JS. See it working at [CodePen](http://codepen.io/renekorss/pen/EVpQBb).

Hope this helps.

**Comment by renekorss** [comment]
@rajeshwarpatlolla This should have been closed with my PR too. Had wrong syntax for it.

**Comment by ravi1078** [comment]
@rajeshwarpatlolla Hi Rajeshwar, I am also facing the same issue . I tried @renekorss  solution but it is not working.

**Comment by renekorss** [comment]
@ravi1078 Are you using master branch version? My changes are only on master branch right now.

**Comment by ravi1078** [comment]
@renekorss I tried master branch then date modal is not opening. In http://codepen.io/renekorss/pen/EVpQBb also date modal is not working.

**Comment by ravi1078** [comment]
Thanks @renekorss  , I am using master branch version now ,it is working .

**Comment by PradeepSmg** [comment]
Hi Rajesh I am having same issue, I am trying to update the From and to date of my second date picker whenever Date in first date picker object is selected. First time works as expected but from second time onwards the from and to dates in second date picker remains same.

First date Picker:

$scope.startdatepickerObject = {
		setButtonType : 'button-dark', //Optional
		todayButtonType : 'button-dark', //Optional
		closeButtonType : 'button-dark', //Optional
		from : new Date(),
		callback : function(val) {//Mandatory
			startdatePickerCallback(val);
		},
		dateFormat : 'dd-MMM-yyyy' //Optional
	};

	var startdatePickerCallback = function(val) {
		// console.log("enter startdatePickerCallback");
		if ( typeof (val) === 'undefined') {
			// console.log('No date selected');
		} else {
			$scope.isStartDateSelected = true;
			$scope.startdatepickerObject.inputDate = val;
			//$scope.enddatepickerObject.from = $scope.startdatepickerObject.inputDate;
			createEndDateObject();
			// console.log('Start Date::Selected date is : ' + val);
		}


Second Date picker: 


function createEndDateObject() {
		if ($scope.isStartDateSelected == true) {
			var endDate = new Date($scope.startdatepickerObject.inputDate);
			endDate = endDate.setDate(endDate.getDate() + 1);

			$scope.enddatepickerObject = {
				setButtonType : 'button-dark', //Optional
				todayButtonType : 'button-dark', //Optional
				closeButtonType : 'button-dark', //Optional
				from : new Date($scope.startdatepickerObject.inputDate),
				to : new Date(endDate),
				callback : function(val) {//Mandatory
					enddatePickerCallback(val);
				},
				dateFormat : 'dd-MMM-yyyy' //Optional
			};
			$scope.enddatepickerObject.inputDate = $scope.startdatepickerObject.inputDate;

		}
	}

**Comment by vicky1404** [comment]
hi,

how we can reinitialize 
$scope.enddatepickerObject.disabledDates after getting reponse from server side?

**Comment by vageesans** [comment]
@omer-r Thanks for the directive, can u share the "DatePickService" service code.
