### ISSUE TITLE
How to set class and id to popup / modal

### ISSUE THREAD

**Issue by filipe-torres** [rajeshwarpatlolla/ionic-datepicker#86]
Hi,
how to set class and id attributes to ionic popup / modal using controller's `$scope.datepickerObject`?
Exemple:
```javascript
$scope.datepickerObject = {
    titleLabel: 'Title',  //Optional
    todayLabel: 'Today',  //Optional
    ...
    customId: 'idValue',  //Optional 
    customClass: 'classValue',  //Optional
    ...
    callback: function (val) {    //Mandatory
        datePickerCallback(val);
    }
};`

**Comment by rajeshwarpatlolla** [comment]
Could you please let me know how does it help you?

**Comment by filipe-torres** [comment]
Hi rajeshwarpatlolla,
These attributes would enable stylize popup / modal CSS in specific situations.

**Comment by rajeshwarpatlolla** [comment]
Already i have added the css classes, please check the description.
