### ISSUE TITLE
Retain selected date (dd) on change of year/month

### ISSUE THREAD

**Issue by niyando** [rajeshwarpatlolla/ionic-datepicker#88]
Hi @rajeshwarpatlolla,
Thanks for this awesome tool :+1:   It was really smooth integrating it with my app.

Not really an issue,
But I am wondering if there is a way to retain date (dd) on change of month/year. Sometimes it feels confusing that changing the yy/mm removes the selected date. What do you think?

**Comment by rajeshwarpatlolla** [comment]
It seems, a minor change is needed to get this fixed. I will work on it. Thanks.

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
