### ISSUE TITLE
Set date on day select, feature request

### ISSUE THREAD

**Issue by patrioticcow** [rajeshwarpatlolla/ionic-datepicker#89]
Right now, one needs to click the "Set" button to set the date. I was thinking on a option so i can set the date when i tap on a day from the calendar.

thanks

**Comment by rajeshwarpatlolla** [comment]
Considering the user's aspect, one may click on some date, but he may not want to set it. So in that case the user might feel weird, if we set the clicked date. So i feel it's better to have a button, which the user will be able to select it, if wish to set the date.

if you have any other thoughts let me know.

**Comment by ndudenhoeffer** [comment]
I just came across this plugin, and it looks great overall. But I can say that this feature is a must if we use it in our app. Make it an option, as the OP states, then it is up to the developer. 

The reason for not using the native datepicker is that it takes too many user actions to set. Setting on "day select" as the OP requests, would allow setting a date with a single touch.

**Comment by rajeshwarpatlolla** [comment]
You can fork this repo, and just call the function ( currently which i am calling on the set button click), when the user clicks on the one of the date slot.

**Comment by renekorss** [comment]
@patrioticcow and @AgDude. Take a look if my PR fits for you.

**Comment by patrioticcow** [comment]
@renekorss ill give it a try. thanks

**Comment by domharrington** [comment]
Has this been published into a new release?
