### ISSUE TITLE
Ability to set text as input date

### ISSUE THREAD

**Issue by jamesamuir** [rajeshwarpatlolla/ionic-datepicker#90]
It would awesome to have the ability to default the selection button text to 'Select Date' if the inputDate option is null. Currently it defaults to a blank button.

**Comment by rajeshwarpatlolla** [comment]
May i know what you are expecting here. Without having any description, how one can understand the need?

**Comment by jamesamuir** [comment]
sorry, fat fingered the details when i was entering. I have updated it. Also, thank you for creating such an awesome component.

**Comment by jamesamuir** [comment]
![image](https://cloud.githubusercontent.com/assets/1069834/10369842/5b5a87a0-6daa-11e5-80af-2548c0565935.png)

**Comment by jamesamuir** [comment]
![image](https://cloud.githubusercontent.com/assets/1069834/10369879/845c8fae-6daa-11e5-8c87-a4c2140757f7.png)

**Comment by rajeshwarpatlolla** [comment]
It's pretty simple. In side a button you can check some thing like
````
<button ionic-datepicker input-obj="datepickerOptions">
    <span ng-if="datepickerOptions.inputDate == null">Select Date</span>
    <span ng-if="datepickerOptions.inputDate != null"> {{datepickerOptions.inputDate | date:'dd - MMMM - yyyy'}}</span>
<button>
````

**Comment by jamesamuir** [comment]
That worked perfectly, thank you.

**Comment by rajeshwarpatlolla** [comment]
You are welcome.
