### ISSUE TITLE
Performance issues when used inside ng-repeat

### ISSUE THREAD

**Issue by ammichael** [rajeshwarpatlolla/ionic-datepicker#91]
Hello!

This datepicker is awesome. Thanks!

I have a list, which has dates for each item. Unfortunately it gets really slow to render all items.

Is there any better way to use it instead of using a <ionic-datepicker> inside the repeat? Or am I missing something?

Thanks

**Comment by rajeshwarpatlolla** [comment]
May be you can give it a try for modal instead of a popup. The modal is working fast than the popup.

**Comment by ammichael** [comment]
Actually I'm already using modal

**Comment by rajeshwarpatlolla** [comment]
Instead of using the component multiple times, you can use it only in one place and you can reuse the same for the other places.
