### ISSUE TITLE
Error: undefined is not an object (evaluating 'a.inputObj.titleLabel')

### ISSUE THREAD

**Issue by jeni27** [rajeshwarpatlolla/ionic-datepicker#93]
I got this error while running an app.
Error: undefined is not an object (evaluating 'a.inputObj.titleLabel')
plz let me know where i mistake?

**Comment by rajeshwarpatlolla** [comment]
Could you please share the code, how you are using this component. Also could you please cross check the instruction once again. It should work fine. But still let me take a look at your code once.

**Comment by rajeshwarpatlolla** [comment]
You can take a look at the [demo](rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker). Its working fine. If you still have any issues, let me know the code you have implemented.

**Comment by Zozos** [comment]
For anyone who encounters this error, the error is happening because when the html is loaded, the input-obj doesnt exist.
