### ISSUE TITLE
inputDate does not get highlighted

### ISSUE THREAD

**Issue by jscheeler** [rajeshwarpatlolla/ionic-datepicker#94]
I'm having an issue when I open the datepicker for the first time, the date that I have set as the inputDate (in this instance July 30, 2015), does not get selected automatically.  

It is only when I finally select a date for the first time, will the date that I set remain highlighted each time I open the popup. 

My question is: how can I get the inputDate to be selected the first time the datepicker modal or popup is opened? 

I duplicated your demo and changed the $scope.datepickerObject.inputDate to July 30th 2015.

http://codepen.io/metercat/pen/MaEope

**Comment by rajeshwarpatlolla** [comment]
Please take a look at this demo. It selects the time even before the user selects the time for the first time.

**Comment by jscheeler** [comment]
I'm not seeing that action happening.  I am only seeing the current day being selected.

**Comment by rajeshwarpatlolla** [comment]
As i mentioned did you had a look at the demo? If still you are facing the same issue, could you please send me the screen cast?

**Comment by jscheeler** [comment]
Your demo selected the CURRENT DAY. Upon initialization, if you were to change the inputdate to be a date OTHER THAN the current day, it does not highlight that date.  I don't believe I need to send you a screencast, the demo I have set up in codepen should be enough to demonstrate the issue I am having. Please let me know what you are not understanding.

If you look at my codepen demo. I have July 30th, 2015 set as the input date.  When you open the datepicker, that date is NOT highlighted.

**Comment by chompunut** [comment]
+1

When I set inputDate to what ever date, the picker doesn't highlight on that date.

For example,
in controller.js
```
$scope.dateObject = {
     inputDate: new Date('2015-10-15),
     templateType: 'popup'
};
```
in view.html
```
<div ionic-datepicker input-obj="dateObject">{{dateObject.inputDate}}</div>
```

When the popup show, the date 15th on October isn't be highlighted.

**Comment by renekorss** [comment]
@jscheeler and @chompunut. Can you check if my PR fixed it. Just update from master. Then it could be closed.

**Comment by chompunut** [comment]
@renekorss I tested with 1e251592328dd79565c4c6611a1bd1a4a18bf22f of your PR and it works. Thank you!

**Comment by Habeeb-mohamed** [comment]
I tested with 1e25159 it is not working if set one date at initialization and changed to different date after ajax success. It is showing only initialized date.

**Comment by sebrojas14** [comment]
Please fix this!

**Comment by Habeeb-mohamed** [comment]
Bower version has issue. Just download the main branch and try.

**Comment by sebrojas14** [comment]
I use bower in my workflow, there's no way to get it OK?

**Comment by renekorss** [comment]
`bower install ionic-datepicker#master --save` will get you master branch version.

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.
