### ISSUE TITLE
Feature request: Swipe support

### ISSUE THREAD

**Issue by smajl** [rajeshwarpatlolla/ionic-datepicker#95]
Swipe support (preferably horizontal) on calendar to swipe through months. This combined with https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/89 will be a huge UX boost.

**Comment by leschirmeur** [comment]
+1

**Comment by Arxi** [comment]
+1

**Comment by stanleygomesdasilva** [comment]
+1

**Comment by Vercryger** [comment]
+1

**Comment by NBAMj** [comment]
+1

**Comment by Arxi** [comment]
+1

**Comment by jdnichollsc** [comment]
+1

**Comment by rajeshwarpatlolla** [comment]
Currently i am focusing on `ionic2-datepicker`. If anyone wish to raise a PR with this feature that will be really great. May be we can try this feature in `ionic2-datepicker` down the line.
